<div class="tabs">
	<ul>
		<li>
			<a href="#tab-tags" id="tags"><?php echo $this->translate('Tags'); ?></a>
		</li>
	</ul>
	
	<div id="tab-tags">
		<div class="tab-content">
		
			<div class="toolbar ui-corner-bottom">
				<button id="delete-tag" class="type-delete deny"><?php echo $this->translate('Delete selected tags'); ?></button>
			</div>		
		
			<div class="sized-content" id="tag-list">
				<?php echo $this->partial('taglist.phtml', array('tags' => $this->tags)); ?>
			</div>
			
		</div>
	</div>
		
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

	$('div#tab-tags table tbody tr').live('click', function() {
		$(this).toggleClass('selected');
	});
	
	$('button#delete-tag').click(function() {
		var selectedTags = new Array();
  		$("div#tab-tags table tbody tr.selected").each(function() {
  			selectedTags.push($(this).attr("id"));
  		});
  		$('<div></div>')
  			.html('<?php echo $this->translate('You are about to delete the selected tags. Are you sure?'); ?>')
  			.dialog({
				title: '<?php echo $this->translate('Delete tags'); ?>',
				modal: true,
				buttons: {
					'<?php echo $this->translate('Yes, delete the tags'); ?>': function() {
						$('#tag-list').load('<?php echo $this->url(array('paction' => 'delete')); ?>', {
  							'tags': selectedTags.join(",")
  						});
  						$(this).dialog('close');
					},
					'<?php echo $this->translate('No'); ?>': function() {
						$(this).dialog('close');
					}
				}
			});  		
	});

});
<?php $this->inlineScript()->captureEnd(); ?>