<table border="0" cellpadding="0" cellspacing="0" class="full">
	<thead>
		<tr>
			<th scope="col" style="width:70px;"><?php echo $this->translate('ID'); ?></th>
			<th scope="col"><?php echo $this->translate('Tag'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $counter = 0; foreach ($this->tags as $tag) : $counter++; ?>
			<tr id="tagid-<?php echo $tag->tagid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
				<td><?php echo $tag->tagid; ?></td>
				<td><?php echo $tag->tag; ?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>