<div class="subcolumns">
	<div class="c50l">
		<div class="subcl">
			<form action="<?php echo $this->url(); ?>" method="post" style="display:inline; width:120px;">
				<select name="setCurrentClient" class="topleft">
					<?php foreach (Zend_Registry :: get('clients') as $client) : ?>
						<option value="<?php echo $client->idclient; ?>"<?php if ($client->idclient == Aitsu_Registry :: get()->session->currentClient) : ?> selected="selected"<?php endif; ?>><?php echo $client->name; ?></option>
					<?php endforeach; ?>
				</select>
			</form>
		</div>
	</div>
	<div class="c50r">
		<div class="subcl">
			<form action="<?php echo $this->url(); ?>" method="post" style="display:inline; width:120px;">
				<select name="setCurrentLanguage" class="topleft">
					<?php foreach (Zend_Registry :: get('langs') as $lang) : ?>
						<option value="<?php echo $lang->idlang; ?>"<?php if ($lang->idlang == Aitsu_Registry :: get()->session->currentLanguage) : ?> selected="selected"<?php endif; ?>><?php echo $lang->name; ?></option>
					<?php endforeach; ?>
				</select>
			</form>
		</div>
	</div>
</div>