<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		
		<title>aitsu Administration area</title>
		
		<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/ext-all-notheme.css'); ?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/ux-all.css'); ?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/xtheme-gray.css'); ?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/css/extjs-aitsu.css'); ?>" />
              
        <?php if (true) : /* change to false in production */ ?>
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/debug.css'); ?>" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/adapter/ext/ext-base-debug.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ext-all-debug-w-comments.js'); ?>"></script>   
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ux-all-debug.js'); ?>"></script>
        <?php else : ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/adapter/ext/ext-base.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ext-all.js'); ?>"></script>   
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ux-all.js'); ?>"></script>
        <?php endif; ?>
    		
		<?php echo $this->headLink(); ?>
		<?php echo $this->headStyle(); ?>

    <script type="text/javascript"> 
    Ext.onReady(function(){
    
        Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
        
        var viewport = new Ext.Viewport({
            layout: 'border',
            items: [
            {
            	region: 'north',
            	split: true,
            	margins: '0 0 0 0',
            	height: 28,
            	items: [
            		new Ext.Toolbar({
            			items: [
            				{
					            text: 'Pages',
					            iconCls: 'page'
        					},
            				{
					            text: 'Categories',
					            iconCls: 'folder'
        					}
            			]
            		})
            	]
        	}, {
                region: 'south',
                split: true,
                height: 0,
                margins: '0 0 0 0',
				bbar: new Ext.ux.StatusBar({
		            id: 'basic-statusbar',
		            defaultText: '',
		            text: '',
		            iconCls: 'x-status-valid',
		            items: [
		                'aitsu 2.1.0.1',
		                '-',
		                '&copy; 2010 - aitsu.org'
		            ]
		        })                
            }, {
                region: 'east',
                title: 'Configuration',
                collapsible: true,
                split: true,
                width: 225,
                minSize: 175,
                maxSize: 400,
                margins: '0 5 0 0',
                layout: 'fit',
                items: 
                new Ext.TabPanel({
                    border: false,
                    activeTab: 0,
                    tabPosition: 'bottom',
                    items: [new Ext.grid.PropertyGrid({
                        title: 'Property Grid',
                        closable: false,
                        source: {
                            "Status": "online",
                            "Published": false
                        }
                    })]
                })
            }, {
                region: 'west',
                id: 'west-panel',
                title: 'Navigation',
                split: true,
                width: 200,
                minSize: 175,
                maxSize: 400,
                collapsible: true,
                margins: '0 0 0 5',
                layout: {
                    type: 'accordion',
                    animate: true
                },
                items: [{
                    contentEl: 'west',
                    title: 'Navigation',
                    border: false,
                    iconCls: 'nav' // see the HEAD section for style used
                }, {
                    title: 'Settings',
                    html: '<p>Some settings in here.</p>',
                    border: false,
                    iconCls: 'settings'
                }]
            },
            new Ext.TabPanel({
                region: 'center',
                deferredRender: false,
                activeTab: 0,
                items: [{
                    contentEl: 'center',
                    title: 'Center Panel',
                    autoScroll: true
                }]
            })]
        });
    });
    </script> 
</head> 

<body> 
    <!-- use class="x-hide-display" to prevent a brief flicker of the content --> 
    <div id="west" class="x-hide-display"> 
        <p>Hi. I'm the west panel.</p> 
    </div> 
    <div id="center" class="x-hide-display">  
        <p>hier kommt der editierbereich hin.</p> 
    </div> 
    <div id="props-panel" class="x-hide-display" style="width:200px;height:200px;overflow:hidden;"> 
    </div> 
</body> 
</html>