<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		
		<meta http-equiv="Content-type" content="text/html; charset=utf-8" />
		
		<title>aitsu Administration area</title>
		
		<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/ext-all-notheme.css'); ?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/ux-all.css'); ?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/xtheme-gray.css'); ?>" />
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/css/extjs-aitsu.css'); ?>" />
              
        <?php if (true) : /* change to false in production */ ?>
        <link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl('/js/ext-3.3.1/resources/css/debug.css'); ?>" />
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/adapter/ext/ext-base-debug.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ext-all-debug-w-comments.js'); ?>"></script>   
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ux-all-debug.js'); ?>"></script>
        <?php else : ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/adapter/ext/ext-base.js'); ?>"></script>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ext-all.js'); ?>"></script>   
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ux-all.js'); ?>"></script>
        <?php endif; ?>
        <script type="text/javascript" src="<?php echo $this->baseUrl('/js/ext-3.3.1/ext-aitsu.js'); ?>"></script>
    		
    <script type="text/javascript"> 
    Ext.onReady(function(){

    	Ext.QuickTips.init();
		Ext.getBody().on("contextmenu", Ext.emptyFn, null, {preventDefault: true});
        Ext.state.Manager.setProvider(new Ext.state.CookieProvider());
        
        var sessionClock = new Ext.Toolbar.TextItem('');
                
        var viewport = new Ext.Viewport({
            layout: 'border',
            id: 'viewport',
            items: [
            {
            	region: 'north',
            	split: true,
            	margins: '0 0 0 0',
            	height: 50,
            	layout: 'border',
            	items: [{
            		region: 'center',
            		margins: '0 0 0 0',
            		border: false,
            		items:
	            		new Ext.Toolbar({
	            			layout: 'hbox',
	            			style: 'padding-top:15px; padding-left:10px;',
	            			height: '100%',
	            			items: [
	            				<?php echo $this->partial('layout/navigation/top.phtml'); ?>
	            				<?php echo $this->partial('layout/navigation/languagechooser.phtml'); ?>
	            				{
						            text: 'Logout',
						            iconCls: 'tm-logout',
						            listeners: {
						            	click: function() {
						            		window.location.href = '<?php echo $this->url(array('controller' => 'acl', 'action' => 'logout'), 'default'); ?>';
						            	}
						            }
	        					}
	            			]
	            	})
            	}, {
            		region: 'east',
            		margins: '0 0 0 0',
            		border: false,
            		width: 200,
            		html: '<div class="x-toolbar" style="height:50px; padding:10px 10px 0 0; text-align:right;"><img src="<?php echo $this->baseUrl('/images/wbm_aitsu_ec7537_146x30.png'); ?>"</div>'
            	}
            ]}, {
                region: 'south',
                split: true,
                height: 0,
                margins: '0 0 0 0',
				bbar: new Ext.ux.StatusBar({
		            id: 'basic-statusbar',
		            defaultText: '',
		            text: '',
		            iconCls: 'x-status-valid',
		            items: [
		            	{
		            		xtype: 'tbtext',
		            		id: 'session-clock',
		            		text: 'das ist ein test'
		            	},
		            	'-',
		                'aitsu 2.1.0.1',
		                '-',
		                '&copy; 2010 - aitsu.org'
		            ]
		        })                
            }, {
                region: 'east',
                id: 'viewport-east',
                collapsible: true,
                split: true,
                width: 225,
                minSize: 175,
                maxSize: 400,
                margins: '0 5 0 0'
            }, {
                region: 'west',
                id: 'viewport-west',
                layout: 'fit',
                split: true,
                width: 200,
                minSize: 175,
                maxSize: 400,
                collapsible: true,
                margins: '0 0 0 5'
            },{
            	region: 'center',
            	id: 'viewport-center',
            	unstyled: true,
            	layout: 'fit',
            	split: false
            }]
        });
        
        /* SESSION MANAGEMENT */
        var sessionPeriod = <?php echo Aitsu_Registry :: get()->session->sessionPeriod > 300 ? Aitsu_Registry :: get()->session->sessionPeriod : 300; ?>;
        var remainingSessionPeriod = sessionPeriod;
		Ext.TaskMgr.start({
		    run: function() {
		    	remainingSessionPeriod--;
		    	var h = Math.floor(remainingSessionPeriod / 60 / 60);
		    	var m = Math.floor((remainingSessionPeriod - h * 60 * 60) / 60);
		    	var s = Math.floor(remainingSessionPeriod - h * 60 * 60 - m * 60);
		    	m = m < 10 ? '0' + m : m;
		    	s = s < 10 ? '0' + s : s;
		    	Ext.getCmp('session-clock').update('<?php echo Aitsu_Translate :: translate('Remaining session time'); ?>: ' + h + ' h ' + m + ' m ' + s + ' s');
		    },
		    interval: 1000
		});
		Ext.getBody().on('keydown', function() {
			remainingSessionPeriod = sessionPeriod;
		});
		Ext.getBody().on('mousedown', function() {
			remainingSessionPeriod = sessionPeriod;
		});
		Ext.TaskMgr.start({
		    run: function() {
		    	Ext.Ajax.request({
				   url: '<?php echo $this->url(array('controller' => 'acl', 'action' => 'refreshsession'), 'default'); ?>',
				   success: function(response, opts) {
				      var res = Ext.decode(response.responseText);
				      if (res.success) {
				      	Ext.getCmp('basic-statusbar').setStatus('<?php echo Aitsu_Translate :: translate('Session refreshed at'); ?> ' + res.time);
				      } else {
				      	window.location.href = '<?php echo $this->url(array('controller' => 'acl', 'action' => 'logout'), 'default'); ?>';
				      }
				   },
				   failure: function(response, opts) {
				      alert('ERROR');
				   }
				});
		    },
		    interval: 300000
		});
        
        <?php echo $this->layout()->content; ?>
    });
    </script> 
</head> 

<body>
</body> 
</html>