<?php $user = Aitsu_Adm_User :: getInstance(); ?>
<div id="subnav-accordion">
	<div class="accordion">
		<h3><a href="#"><?php echo $this->translate('Menu'); ?></a></h3>
		<div>
			<ul class="vlist">
				<?php $counter = 0; $amount = count(Zend_Registry :: get('nav')); foreach (Zend_Registry :: get('nav') as $pos) : $counter++; ?>
					<?php if ($pos->isActive(true) && count($pos->pages) > 0) : ?>
						<?php foreach ($pos->pages as $page) : ?>
							<?php if (!isset($page->ac) || $user->isAllowed($page->ac)) : ?>
								<li>
									<a href="<?php echo $page->getHref(); ?>"><?php echo $page->label; ?></a>
									<?php if ($page->isActive(true) && count($page->pages) > 0) : ?>
										<ul>
										<?php foreach ($page->pages as $subPage) : ?>
											<?php if (!isset($subPage->ac) || $user->isAllowed($subPage->ac)) : ?>
												<li>
													<a href="<?php echo $subPage->getHref(); ?>"><?php echo $subPage->label; ?></a>
													<?php if ($subPage->isActive(true) && count($subPage->pages) > 0) : ?>
														<ul>
														<?php foreach ($subPage->pages as $subSubPage) : ?>
															<?php if (!isset($subSubPage->ac) || $user->isAllowed($subSubPage->ac)) : ?> 
																<li>
																	<a href="<?php echo $subSubPage->getHref(); ?>"><?php echo $subSubPage->label; ?></a>
																</li>
															<?php endif; // Access control level 3 ?>
														<?php endforeach; ?>
														</ul>
													<?php endif; ?>
												</li>
											<?php endif; // Access control level 2 ?>
										<?php endforeach; ?>
										</ul>
									<?php endif; ?>
								</li>
							<?php endif; // Access control level 1 ?>
						<?php endforeach; ?>
					<?php endif; ?>
				<?php endforeach; ?>
			</ul>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

	$('#subnav-accordion').relativeSize(window, null, '-132');
	
});
<?php $this->inlineScript()->captureEnd(); ?>