<!-- Produkt -->
<div class="hide-for-small">
    <div id="featured" data-orbit>
        <?php foreach ($this->selectedImages as $image) : ?>
            <?php
            $image = (object) $image;

            $this->attributes->alt = $image->subline;

            echo Moraso_Html_Helper_Image::getHtml($image->idart, $image->filename, 320, 320, $this->render, $this->attributes);
            ?>
        <?php endforeach; ?>
    </div>
</div>