<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
	<thead>
		<tr>
			<th scope="col"><?php echo $this->translate('ID'); ?></th>
			<th scope="col"><?php echo $this->translate('Title'); ?></th>
			<th scope="col"><?php echo $this->translate('Category'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $counter = 0; foreach ($this->crosslinks as $cl) : $cl = (object) $cl; $counter++; ?>
			<tr id="crosslink-<?php echo $cl->idartlang; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
				<td><?php echo $cl->idart; ?> [<?php echo $cl->idartlang; ?>]</td>
				<td><?php echo $cl->title; ?></td>
				<td><?php echo $cl->category; ?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>