<div id="Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>" class="flexeditor aee">
	<ul class="flexcontent no-edit" style="padding:0; margin:0;">
	<?php if (count($this->content) == 0) : ?>
		<li style="list-style-type:none; margin:0; position:relative;">
			<a href="0" class="position" style="display:none"></a>
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
			</div>
			<div class="content">
				Add text here...
			</div>
			<div class="editor">
				<textarea name="content textile"></textarea>
			</div>
		</li>
	<?php else : ?>
	<?php foreach ($this->content as $content) : ?>
		<li style="list-style-type:none; margin:0; position:relative;">
			<a href="<?php echo $content->position; ?>" class="position" style="display:none"></a>
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<?php if ($content->isShortcodeBlock) : ?>
				<button class="flex-ui-button configure"><span /></button>
				<?php endif; ?>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<div class="content">
				<?php echo $content->html; ?>
				<?php if (substr(trim($content->html), 0, 3) != '<p>') : ?>
				<p style="height:0px;"></p>
				<?php endif; ?>
			</div>
			<div class="editor aee">
				<textarea name="content textile"><?php echo $content->textile; ?></textarea>
			</div>
		</li>
	<?php endforeach; ?>
	<?php endif; ?>
	</ul>
	<div class="flexcontent no-edit">
	<?php if (count($this->content) == 0) : ?>
		Add text here...
	<?php else : ?>
		<?php foreach ($this->content as $content) : ?>
			<div>
				<?php echo $content->html; ?>
				<?php if (substr(trim($content->html), 0, 3) != '<p>') : ?>
				<p style="height:0px;"></p>
				<?php endif; ?>
			</div>
		<?php endforeach; ?>
	<?php endif; ?>
	</div>
	<ul style="display:none;">
		<li class="modules" style="list-style-type:none; margin:0; position:relative;">
			<a href="" class="position" style="display:none"></a>
			<div class="content modules" style="padding:40px 0 0 10px;">
				<div style="position:absolute; top:5px; left:0px;">
					<button class="flex-ui-button cancel"><span /></button>
					<div style="clear:left;"></div>
				</div>
				<button value="" class="text">
					<div class="name">Text block</div>
					<div class="description">...</div>
				</button>
				<?php foreach ($this->modules as $module) : ?>
				<button value="<?php echo $module->shortcode; ?>" class="shortcode">
					<div class="name"><?php echo $module->name; ?></div>
					<div class="description"><?php echo $module->description; ?></div>
				</button>
				<?php endforeach; ?>
				<div style="clear:left;"></div>
			</div>
		</li>
	</ul>
</div>