var center = Ext.getCmp('viewport-center');
center.removeAll();

var translationGrid = new Ext.grid.GridPanel({
	title: '<?php echo Aitsu_Translate :: translate('Translatations'); ?>',
	store: new Ext.data.JsonStore({
        autoDestroy: true,
        url: '<?php echo $this->url(array('action' => 'store')); ?>',
        remoteSort: false,
        storeId: 'translationStore',
        idProperty: 'translationid',
        root: 'data',
        fields: [{
            name: 'translationid'
        }, {
            name: 'tkey'
        }, {
            name: 'tvalue'
        }]
    }),
    columns: [
    	{dataIndex: 'translationid', header: 'ID', menuDisabled: false, sortable: false, width: 20},
    	{dataIndex: 'tkey', header: '<? echo Aitsu_Translate :: translate('Key'); ?>', menuDisabled: false, sortable: true},
    	{dataIndex: 'tvalue', header: '<? echo Aitsu_Translate :: translate('Value'); ?>', menuDisabled: false, sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Refresh list'); ?>',
	            iconCls: 'tb-refresh',
	            handler: function(b, e) {
	            	translationGrid.getStore().load({
	            		params: {
	            			refresh: 1
	            		}
	            	});
	            }
	        }
	    ]
	},
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		},
		rowclick: function(grid, rowIndex, event) {
			var id = this.getStore().getAt(rowIndex).get('translationid');
			Ext.aitsu.load(['<?php echo $this->url(array('action' => 'edit')); ?>?translationid=' + id]);
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete translation'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected translation?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('action' => 'delete')); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Translation removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected translation has been removed.'); ?>');
					            			var store = grid.getStore().remove(record); 
				            			}
				            		},
				            		params: { translationid: record.get('translationid') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}	
	},
	plugins: [
		new Ext.ux.grid.GridFilters({
			encode: false,
	        local: false,
	        filters: [{
	            type: 'string',
	            dataIndex: 'tkey'
	        }, {
	            type: 'string',
	            dataIndex: 'tvalue'
	        }]
		})
	]
});

center.add(translationGrid);

Ext.getCmp('viewport').doLayout();
