<div class="toolbar ui-corner-bottom">
	<button id="top-cancel" class="deny" title="<?php echo $this->translate('cancel'); ?>"><?php echo $this->translate('cancel'); ?></button>
	<button id="top-save" class="confirm" title="<?php echo $this->translate('save'); ?>"><?php echo $this->translate('save'); ?></button>
</div>

<div class="sized-content">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">
$(function() {
	
	$('#top-cancel').button({icons: {primary: 'ui-icon-circle-close'}, text:false});
	$('#top-cancel').click(function() {
		$(this).parents('.tab-content').find('button#cancel').trigger('click');
	});

	$('#top-save').button({icons: {primary: 'ui-icon-circle-check'}, text:false});
	$('#top-save').click(function() {
		$(this).parents('.tab-content').find('form button[type=submit]').trigger('click');
	});

});
</script>