<form action="/adm/translation/filtertranslation" method="post" style="display:inline;">	
	<div class="toolbar ui-corner-bottom">
		<button id="refresh-translation" class="type-refresh" title="<?php echo $this->translate('Refresh list'); ?>"><?php echo $this->translate('Refresh list'); ?></button>
		<input type="text" name="filter-translation" value="<?php echo $this->filterterm; ?>" class="button-input ui-button ui-corner-all" />
		<button id="filter-user" class="filter-button" title="<?php echo $this->translate('Filter'); ?>"><?php echo $this->translate('Filter'); ?></button>
	</div>
</form>	

<div class="sized-content">	
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Key'); ?></th>
				<th scope="col"><?php echo $this->translate('Value'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $counter = 0; foreach ($this->translations as $translation) : $counter++; ?>
				<tr id="translate-<?php echo $translation->translationid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
					<td><?php echo $translation->translationid; ?></td>
					<td><?php echo $translation->tkey; ?></td>
					<td><?php echo $translation->tvalue; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>