<?php
Aitsu_Util_Javascript :: addReference('/skin/js/jquery.fancybox-1.3.1.pack.js');
Aitsu_Util_Javascript :: add($this->render('js_fancybox.phtml'));
?>
<?php
foreach($this->images as $image) {
	(int)$counter = substr($image->filename,0,-(strlen($image->filename) - 3));
	$img[$counter] = $image;
}
ksort($img);
?>
<div id="thumbs">
	<ul class="thumbs noscript clearfix">
<?php foreach($img as $value) : ?>
	<?php
		$imagePath = Aitsu_Registry :: get()->config->sys->webpath . 'image/94/94/0/' . $value->idart . '/' . $value->filename;
		list($calWidth,$calHeight) = getimagesize($imagePath);
	?>
		<li>
			<a class="fancybox" rel="fancybox" href="/image/1024/1024/0/<?php echo $value->idart; ?>/<?php echo $value->filename; ?>" title="<?php echo $value->name; ?>: <?php echo $value->description; ?>">
				<img <?php if($calWidth) : ?> width="<?php echo $calWidth; ?>"<?php endif; ?><?php if($calHeight) : ?> height="<?php echo $calHeight; ?>" <?php endif; ?> src="/image/94/94/0/<?php echo $value->idart; ?>/<?php echo $value->filename; ?>" alt="<?php echo $value->name; ?>" />
			</a>
			<p><?php echo $value->name; ?></p>
		</li>
	<?php endforeach; ?>
	</ul>
</div>