<?php
Aitsu_Util_Javascript :: addReference('/skin/js/jquery.galleriffic.js');
Aitsu_Util_Javascript :: add($this->render('js.phtml'));
?>
<?php
foreach($this->images as $image) {
	(int)$counter = substr($image->filename,0,-(strlen($image->filename) - 3));
	$img[$counter] = $image;
}
ksort($img);
?>
<div id="thumbs">
	<ul class="thumbs noscript clearfix">
<?php foreach($img as $value) : ?>
	<?php
		$imagePath = Aitsu_Registry :: get()->config->sys->webpath . 'image/94/94/0/' . $value->idart . '/' . $value->filename;
		list($calWidth,$calHeight) = getimagesize($imagePath);
	?>
		<li>
			<a class="thumb corner" href="/image/702/702/0/<?php echo $value->idart; ?>/<?php echo $value->filename; ?>" title="<?php echo $value->name; ?>: <?php echo $value->description; ?>">
				<img <?php if($calWidth) : ?> width="<?php echo $calWidth; ?>"<?php endif; ?><?php if($calHeight) : ?> height="<?php echo $calHeight; ?>" <?php endif; ?> src="/image/94/94/0/<?php echo $value->idart; ?>/<?php echo $value->filename; ?>" alt="<?php echo $value->name; ?>" />
			</a>
			<!-- 
			<a class="fancybox" rel="fancybox" href="/image/1024/1024/0/<?php echo $value->idart; ?>/<?php echo $value->filename; ?>" title="<?php echo $value->name; ?>: <?php echo $value->description; ?>">x</a> 
			-->
			<div class="caption">
				<?php if($value->subline) : ?>
				<h3><?php echo $value->subline; ?></h3>
				<?php endif; ?>
				<?php if($value->description) : ?>
				<p><?php echo $value->description; ?></p>
				<?php endif; ?>
			</div>
		</li>
	<?php endforeach; ?>
	</ul>
</div>
<div id="controls"></div>
<div id="loading"></div>
<div id="slideshow"></div>
<div id="caption"></div>