<div itemscope itemtype="http://schema.org/PostalAddress" class="SchemaOrg PostalAddress">
	<link itemprop="url" href="<?php echo $this->url; ?>" />
	<?php if (!empty($this->image)) : ?>
		<img itemprop="image" src="<?php echo Aitsu_Config :: get('sys.mainDir'); ?>image/100/100/2/<?php echo $this->idart; ?>/<?php echo $this->image; ?>" width="100" height="100" style="float:right; margin: 0 0 5px 5px;" />
	<?php endif; ?>
	<?php if (!empty($this->description)) : ?>
	<div itemprop="description" style="margin-bottom:10px;"><?php echo htmlentities($this->description, ENT_COMPAT, 'UTF-8'); ?></div>
	<?php endif; ?>
	<dl>
		<?php if (!empty($this->name)) :?>
		<dt>Name:</dt>
			<dd itemprop="name"><?php echo htmlentities($this->name, ENT_COMPAT, 'UTF-8'); ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->email)) :?>
		<dt>Email:</dt>
			<dd>
				<a href="mailto:<?php echo $this->email; ?>" itemprop="email"><?php echo $this->email; ?></a>
			</dd>
		<?php endif; ?>
		<?php if (!empty($this->faxnumber)) :?>
		<dt>Fax:</dt>
			<dd itemprop="faxnumber"><?php echo $this->faxnumber; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->telefone)) :?>
		<dt>Phone:</dt>
			<dd itemprop="telefone"><?php echo $this->telefone; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->addressCountry)) :?>
		<dt>Country:</dt>
			<dd itemprop="addressCountry"><?php echo $this->addressCountry; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->addressLocality)) :?>
		<dt>Locality:</dt>
			<dd itemprop="addressLocality"><?php echo $this->addressLocality; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->addressRegion)) :?>
		<dt>Region:</dt>
			<dd itemprop="addressRegion"><?php echo $this->addressRegion; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->postOfficeBoxNumber)) :?>
		<dt>P.O. Box:</dt>
			<dd itemprop="postOfficeBoxNumber"><?php echo $this->postOfficeBoxNumber; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->postalCode)) :?>
		<dt>Postal Code:</dt>
			<dd itemprop="postalCode"><?php echo $this->postalCode; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->streetAddress)) :?>
		<dt>Street:</dt>
			<dd itemprop="streetAddress"><?php echo $this->streetAddress; ?></dd>
		<?php endif; ?>
	</dl>
</div>