<div class="toolbar ui-corner-bottom">
	<button id="save-<?php echo $this->pluginId; ?>" class="confirm" title="<?php echo $this->translate('save'); ?>"><?php echo $this->translate('save'); ?></button>
</div>

<div class="sized-content">
	<?php echo $this->form; ?>
</div>

<script type="text/javascript">

$('button#save-<?php echo $this->pluginId; ?>').button({icons: {primary: 'ui-icon-circle-check'}, text:false});
$('button#save-<?php echo $this->pluginId; ?>').click(function() {
	$(this).parents('.tab-content').find('form button[type=submit]').trigger('click');
});

$('#content-<?php echo $this->pluginId; ?> button.save').button({icons: {primary: 'ui-icon-circle-check'}});

$('#content-<?php echo $this->pluginId; ?> button#submit').bind('click', function() {
	var form = $(this).closest('form');
	$.post("<?php echo $this->url(array('plugin' => 'properties', 'paction' => 'index'), 'aplugin'); ?>", form.serialize(), function(data) {
		if (data.status == 'validationfailure') {
			$("#content-<?php echo $this->pluginId; ?>").html(data.message);
		} else if (data.status == 'success') {
			$('#status').html(data.message);
			$('li#idart-' + data.data.idart + ' a').html('<ins class="jstree-icon">&nbsp;</ins>' + data.data.title);
			$("#content-<?php echo $this->pluginId; ?>").html(data.html);
		} else {
			$('#status').html(data.message);
		}
		
		$(document).trigger('article-properties-changed');
	});
	return false;
});

$('#content-<?php echo $this->pluginId; ?> form .date').datepicker({
	numberOfMonths: 3,
	showButtonPanel: true,
	dateFormat: 'yy-mm-dd'
});

</script>