<h3><?php echo Aitsu_Translate :: _('Meistgelesene Artikel'); ?></h3>
<ol>
	<?php foreach ($this->articles as $art) : $art = (object) $art; ?>
	<li>
		<?php if ($art->isstart) : ?>
		<a href="{ref:idcat-<?php echo $art->idcat; ?>}" title="<?php echo $art->pagetitle; ?>">
		<?php else : ?>
		<a href="{ref:idart-<?php echo $art->idart; ?>}" title="<?php echo $art->pagetitle; ?>">
		<?php endif; ?>
			<?php echo $art->pagetitle; ?>
		</a>
	</li>
	<?php endforeach; ?>
</ol>