<!-- index -->
<a<?php echo 
$this->id . 
$this->class . 
$this->style . 
$this->target . 
$this->title; ?> 
href="<?php echo preg_match('/^(idcat|idart)\s[0-9]+$/', $this->href) ? '{ref:' . str_replace(' ', '-', $this->href) . '}' : $this->href; ?>">
	<img
<?php echo $this->id; ?>
<?php echo $this->class; ?>
<?php echo $this->style; ?>
src="<?php echo Aitsu_Registry :: get()->config->sys->webpath; ?>image/<?php echo $this->width; ?>/<?php echo $this->height; ?>/<?php echo $this->transform; ?>/<?php echo $this->images[0]->idart; ?>/<?php echo $this->images[0]->filename; ?>" 
<?php echo $this->title; ?> 
<?php if(isset($this->alt)) : ?>
<?php echo $this->alt; ?>
<?php else : ?>
alt="<?php echo $this->images[0]->name; ?>"
<?php endif; ?>
 />
</a>