<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
        <script type="application/x-moraso" src="HTML.Meta.PageTitle">
            suffix = " | moraso CMS"
        </script>

        <!-- BaseHref :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.BaseHref"></script>
        <!-- BaseHref :: End -->

        <!-- CanonicalTag :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.CanonicalTag"></script>
        <!-- CanonicalTag :: End -->

        <!-- Meta Tags :: Start -->
        <script type="application/x-moraso" src="HTML.Meta.Tags"></script>
        <!-- Meta Tags :: End -->

        <!-- Meta Geo Tags :: Start -->
        <meta name="geo.region" content="DE-NI" />
        <meta name="geo.placename" content="Hoya" />
        <meta name="geo.position" content="52.80912;9.14234" />
        <meta name="ICBM" content="52.80912, 9.14234" />
        <!-- Meta Geo Tags :: End -->

        <!-- Windows 8 Tile :: Start -->
        <meta name="application-name" content="moraso CMS" /> 
        <!--<meta name="msapplication-TileImage" content="<?php echo Aitsu_Config::get('sys.webpath'); ?>skin/gfx/tileImage.png" />-->
        <meta name="msapplication-TileColor" content="#FFFFFF" />
        <!-- Windows 8 Tile :: End -->

        <!-- CSS :: Start -->
        <link rel="stylesheet" href="/skin/css/normalize.css" />
        <link rel="stylesheet" href="/skin/css/foundation.min.css">
        <link rel="stylesheet" href="/skin/css/compiled/app.css">
        <!-- CSS :: End -->

        <!-- JS :: Start -->
        <script src="/skin/js/vendor/prefixfree.min.js"></script>
        <script src="/skin/js/vendor/custom.modernizr.js"></script>
        <!-- JS :: End -->

        <!-- IE Fix for HTML5 Tags -->
        <!--[if lt IE 9]>
                <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
    </head>
    <body>

        <!-- Google Tag Manager -->
        <script type="application/x-moraso" src="Google.Tag.Manager">
            container = XYZ-123
        </script>
        <!-- End Google Tag Manager -->

        <!-- Header :: Start -->
        <script type="application/x-moraso" src="Template:Header">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/header/default.phtml 
        </script>
        <!-- Header :: End -->
        
        <!-- Content :: Start -->
        <script type="application/x-moraso" src="Template:Content">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/content/default.phtml 
        </script>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <script type="application/x-moraso" src="Template:Footer">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/footer/default.phtml 
        </script>
        <!-- Footer :: End -->

        <!-- JS :: Start -->
        <script>
            document.write('<script src=' +
            ('__proto__' in {} ? '/skin/js/vendor/zepto' : '/skin/js/vendor/jquery') +
            '.js><\/script>');
        </script>
        <script src="/skin/js/foundation.min.js"></script>
        <script>
            $(document).foundation();
        </script>
        <!-- JS :: End -->
        
        <div id="contactModal" class="reveal-modal">
            <h2>Awesome. I have it.</h2>
            <p class="lead">Your couch.  It is mine.</p>
            <p>Im a cool paragraph that lives inside of an even cooler modal. Wins</p>
            <a class="close-reveal-modal">&#215;</a>
        </div>
    </body>
</html>
