<!-- 
Copyright 2011 by Babett Ammari
For demonstration purpose only! 
-->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
	<head>
		<script type="application/x-aitsu" src="Template:Head">
			defaultTemplate = templates/head/head.phtml
		</script>
		<script type="application/x-aitsu" src="Template:Google">
			defaultTemplate = templates/google.phtml
		</script>
	</head>
	<script type="application/x-aitsu" src="HTML.Body"></script>
		<script type="application/x-aitsu" src="Template:Body">
			defaultTemplate = templates/body/body.phtml
		</script>
		<script type="application/x-aitsu" src="Template:Javascripts">
			defaultTemplate = templates/javascripts.phtml
		</script>
	</body>
</html>