<!DOCTYPE html>
<html lang="de">
    <head>
        <meta charset="utf-8" />
        <script type="application/x-aitsu" src="HTML.Meta.PageTitle">
            suffix = " | aitsu CMS &mdash; forked by webtischlerei &mdash; Die Agentur für Online-Marketing aus Hoya an der Weser"
        </script>
        <script type="application/x-aitsu" src="HTML.Meta.BaseHref"></script>
        <script type="application/x-aitsu" src="HTML.Meta.CanonicalTag"></script>
        <script type="application/x-aitsu" src="HTML.Meta.Tags"></script>

        <script type="application/x-aitsu" src="HTML.Meta.ResourceBundle:CSS">
            type = css
            res.1 = /css/style.css
        </script>

        <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
    </head>
    <body>

        <h1><!-- filled by jQuery --></h1>

        <script type="application/x-aitsu" src="Image:Test">
            width = config
        </script>

        <script type="application/x-aitsu" src="HTML.Meta.ResourceBundle:JS">
            type = js
            res.1 = /js/init.js
        </script>
    </body>
</html>