<div class="row">    
	<div class="large-9 push-3 columns">
    	<script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
        	tag = h1
        </script>
        <script type="application/x-moraso" src="HTML.Meta.TeasertitleAsHeadline:Teasertitle">
            tag = h2
        </script>
        <script type="application/x-moraso" src="Image:Bilder">
        	width = 720
            height = 720
            render = 1
            template = produkt
        </script>
        <script type="application/x-moraso" src="HTML.Content:Teaser"></script>
        <script type="application/x-moraso" src="HTML.Content:Content"></script>
    </div>
</div>