<table border="0" cellpadding="0" cellspacing="0" class="full">
	<thead>
		<tr>
			<th scope="col"><?php echo $this->translate('Name'); ?></th>
			<th scope="col" style="text-align:right;"><?php echo $this->translate('Size'); ?></th>
			<th scope="col" style="text-align:right;"><?php echo $this->translate('Date'); ?></th>
		</tr>
	</thead>
	<tbody style="cursor:pointer;">
		<?php $counter = 0; foreach ($this->files as $file) : $counter++; ?>
			<tr class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
				<td>
					<?php echo $file->basename; ?>
					<input type="hidden" name="basename" value="<?php echo $file->basename; ?>" />
				</td>
				<?php if ($file->size > 1024) : ?>
					<td style="text-align:right;"><?php echo number_format($file->size / 1024, 2); ?> MB</td>
				<?php else : ?>
					<td style="text-align:right;"><?php echo number_format($file->size, 2); ?> KB</td>
				<?php endif; ?>
				<?php if (date('d.m.y', $file->timestamp) == date('d.m.y')) : ?>
					<td style="text-align:right;"><?php echo date('H:i', $file->timestamp); ?></td>
				<?php else : ?>
					<td style="text-align:right;"><?php echo date('d.m.y H:i', $file->timestamp); ?></td>
				<?php endif; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>

<div id="dialog-delete-makenew">
	<?php echo $this->translate('Add new asset entry based on the selected file? Or delete the selected resource?'); ?>
</div>