<div class="toolbar ui-corner-bottom">
</div>

<div class="subcolumns">
	<div class="c50l">
		<div class="subcl">
			<div id="inbox-content" class="rounded-corners sized-content" style="border:1px solid #CCC;">
				<div style="margin:10px;">
					<?php echo $this->partial('inbox/content.phtml', array('files' => $this->files)); ?>
				</div>
			</div>
		</div>
	</div>

	<div class="c50r">
		<div class="subcr">
			<div class="rounded-corners sized-content" style="border:1px solid #CCC;">
				<div id="inbox-upload" style="margin:8px;"></div>
			</div>
		</div>
	</div>
</div>
