<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>

			<script type="application/x-aitsu" src="PageTitle"></script>

			<script type="application/x-aitsu" src="ResourceBundle">
				type = css
				res.1 = /yaml/core/base.css
				res.2 = /yaml/navigation/nav_shinybuttons.css
				res.3 = /css/screen/basemod.css
				res.4 = /css/screen/basemod_2col_right_13.css
				res.5 = /css/screen/content.css
				res.6 = /yaml/print/print_100_draft.css
				res.7 = /css/style.css
			</script>

			<!--[if lte IE 7]>
				<link href="/skin/css/patches/patch.css" rel="stylesheet" type="text/css" />
			<![endif]-->
	</head>

	<body>
		
		<script type="application/x-aitsu" src="Template:Body">
			defaultTemplate = templates/body.phtml
		</script>
		
		<script src="/skin/yaml/core/js/yaml-focusfix.js" type="text/javascript"></script>
		
	</body>
</html>
