var pageConfigurationHandler = function(formId) {
	Ext.getCmp(formId).getForm().submit({
		success: function(form, action) {
			Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Saved'); ?>', '<?php echo Aitsu_Translate :: translate('Configuration has been saved.'); ?>');
			setUnpublished();
			Ext.aitsu.load(['<?php echo $this->url(array('controller' => 'data', 'action' => 'edit'), 'default'); ?>'], function() {
				Ext.getCmp('viewport').doLayout();
				Ext.getCmp('page-edit-tab').activate(0);
				Ext.getCmp('rop').getStore().load();
			}, {id: <?php echo $this->idart; ?>});
		}, 
		failure: function() {
			Ext.aitsu.errmsg('<?php echo Aitsu_Translate :: translate('Form failure'); ?>', '<?php echo Aitsu_Translate :: translate('Form data have not been saved due to errors.'); ?>');
		}
	});
}

Ext.getCmp('page-plugin-accordion').add({
	id: 'article-plugin-config',
	title: '<?php echo Aitsu_Translate :: translate('Configuration'); ?>',
	autoScroll: true,
	border: false,
	items: <?php echo $this->form->render('ExtJs'); ?>
});
