<div class="tabs">
	<ul>
		<li>
			<a href="#tab-script"><?php echo $this->scriptName; ?></a>
		</li>
	</ul>
	
	<div id="tab-script">
		<div class="tab-content">
		
			<?php if ($this->scriptName != 'Scripts') : ?>
				<div class="toolbar ui-corner-bottom">
					<button id="start-execution" class="type-exec" title="<?php echo $this->translate('Execute script'); ?>"><?php echo $this->translate('Execute script'); ?></button>
				</div>	

				<div id="console-window" class="sized-content">
					<div id="console-window-content"></div>
				</div>
			<?php else : ?>
				<div class="toolbar ui-corner-bottom"></div>
				
				<div class="sized-content">
					<?php echo $this->translate('Please choose the script to be executed from the list on the left hand side.'); ?>
				</div>	
			<?php endif; ?>	
					
		</div>
	</div>
	
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {
	
	$(document).bind('executeScript', function(event, step) {
		$.post("<?php echo str_replace('/show/', '/exec/', $this->url()); ?>", { step: step },
   			function(data){
   				setTimeout(function() {
   					$('#console-window-status').remove();
   					if (data.status == 'success') {
   						message = '<div><span class="status success">done</span>' + data.message + '</div>';
   					} else {
   						message = '<div><span class="status failure">' + data.status + '</span>' + data.message + '</div>';
   					}
   					$('#console-window-content').append(message);
   					if (data.nextStep != '') {
	   					$('#console-window-content').append('<div id="console-window-status">' + data.nextStep + '...</div>');
	   					$('#console-window').scrollTop($('#console-window-content').height());
   						$(document).trigger('executeScript', [step + 1])
   					} else {
   						$('#console-window-content').append('<div id="console-window-status"><?php echo $this->translate('Script terminated.'); ?></div>');
   						$('#console-window').scrollTop($('#console-window-content').height());
   					}
   				}, 100);
   		}, 'json');
	});	
	
	$('#start-execution').live('click', function() {
		$('#console-window-content').html('<div id="console-window-status"><?php echo $this->translate('Script starts...'); ?></div>');
		$(document).trigger('executeScript', [1]);
	});			

});
<?php $this->inlineScript()->captureEnd(); ?>