var west = Ext.getCmp('viewport-west');
west.removeAll();
west.setVisible(true);
west.expand(false);
west.removeAll();

west.add(new Ext.tree.TreePanel({
	id: 'pageview-cattree',
	title: '<?php echo $this->translate('Scripts'); ?>',
	useArrows: true,
	autoScroll: true,
	animate: true,
	containerScroll: true,
	border: false,
	dataUrl: '<?php echo $this->url(array('action' => 'tree')); ?>',
	rootVisible: false,
	singleExpand: true,
	stopRestoring: false,
	root: {
		nodeType: 'async',
		text: 'Root',
		draggable: false,
		id: '0'
	}
}));

Ext.getCmp('viewport').doLayout();
