

<?php return; ?>
<div class="tabs">
	<ul>
		<li>
			<a href="#tab-script"><?php echo $this->translate('Scripts'); ?></a>
		</li>
	</ul>
	
	<div id="tab-script">
		<div class="tab-content">
			<div class="toolbar ui-corner-bottom"></div>
			
			<div class="sized-content">
				<?php echo $this->translate('Please choose the script to be executed from the list on the left hand side.'); ?>
			</div>
		</div>
	</div>
		
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {
	
	$(document).bind('refreshButtons', function() {
		$('.filter-button').button({icons: {primary: 'ui-icon-search'}});		
	});
	$(document).trigger('refreshButtons');
	
	$(document).bind('listload', function(event, area, data) {
		if (data != null) {
			$(area).html(data)
		}
		$('.toolbar').button();
     	$(area).find('.filter-button').button({icons: {primary: 'ui-icon-search'}});
     	$(document).trigger('contextmenu');
     	$(document).trigger('formload');
	});	

	$(document).bind('bindclicks', function() {
		$('#refresh-translation').live('click', function() {
			$('#tab-translate div.tab-content').load('<?php echo $this->url(); ?>/refresh', function() {
				$(document).trigger('formload');		
			});
			return false;
		});		
	});
	$(document).trigger('bindclicks');
		
});
<?php $this->inlineScript()->captureEnd(); ?>