var dashboard = Ext.getCmp('dashboard');

dashboard.add({
	columnWidth: 1/3,
	baseCls:'x-plain',
	bodyStyle:'padding:6px 4px 0 4px',
	items: {
		unstyled: true,
		height: 370,
		layout: 'fit',
		items: new Ext.grid.PropertyGrid({
			title: '<?php echo Aitsu_Translate :: translate('Site analyzer'); ?>',
			hideHeaders: true,
			source: {
				'<?php echo Aitsu_Translate :: translate('Number of categories'); ?>': '<?php echo $this->numberOfCategories; ?>',
				'<?php echo Aitsu_Translate :: translate('Number of pages'); ?>': '<?php echo $this->numberOfArticles; ?>',
				'<?php echo Aitsu_Translate :: translate('Categories without index'); ?>': '<?php echo $this->categoriesWithoutIndex; ?>',
				'<?php echo Aitsu_Translate :: translate('Duplicate URL'); ?>': '<?php echo $this->duplicateUrls; ?>'
			},
			viewConfig : {
				forceFit: true,
				scrollOffset: 2
			},
			listeners: {
				beforeedit: function(e) {
					e.cancel = true;
				}
			}
		})
	}
});
