<div id="Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>" class="flexeditor" style="border:1px dotted #CCC; padding:4px 4px 4px 4px; overflow:auto;">
	<div style="height:15px; background-color: #CCC; color: white; font-size: 11px; padding:2px 5px 0 5px; margin-bottom:10px;">
		<span style="float:right;">Flex :: <?php echo $this->id; ?></span>
	</div>
	<div class="buttonbar" style="display:none;">
		das ist die button-bar.
	</div>
	<ul class="flexcontent no-edit" style="padding:0; margin:0;">
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:1" class="module" style="display:none;"></a>
			_[Link:1]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:2" class="module" style="display:none;"></a>
			_[Link:2]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<p>Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:4" class="module" style="display:none;"></a>
			_[Link:4]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:5" class="module" style="display:none;"></a>
			_[Link:5]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:6" class="module" style="display:none;"></a>
			_[Link:6]
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0;">
			<a href="Link:Last" class="module" style="display:none;"></a>
			_[Link:Last]
		</li>
	</ul>
</div>