<div id="Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>" class="flexeditor" style="border:1px dotted #CCC; padding:4px 4px 4px 4px; overflow:auto;">
	<div style="height:15px; background-color: #CCC; color: white; font-size: 11px; padding:2px 5px 0 5px; margin-bottom:10px;">
		<span style="float:right;">Flex :: <?php echo $this->id; ?></span>
	</div>
	<ul class="flexcontent no-edit" style="padding:0; margin:0;">
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="position:absolute; height:25px; top:-25px;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0 0 3px 0; position:relative;">
			<div class="buttonbar" style="display:none; position:absolute;">
				das ist die button-bar.
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
	</ul>
</div>