<div id="Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>" class="flexeditor">
	<ul class="flexcontent no-edit" style="padding:0; margin:0;">
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
		<li style="list-style-type:none; margin:0; position:relative;">
			<div class="buttonbar">
				<button class="flex-ui-button add"><span /></button>
				<button class="flex-ui-button edit"><span /></button>
				<button class="flex-ui-button trash"><span /></button>
			</div>
			<p>_[Link:1]Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. Das ist ein Test. </p>
		</li>
	</ul>
</div>