function enableFlex<?php echo $this->id; ?>() {
	$("ul#flexcontent<?php echo $this->id; ?>").sortable({
		update: function(event, ui) {
			var modules = $('#flexcontent<?php echo $this->id; ?> > li > a.module').map(function(index) {
				return $(this).attr('href');
			}).get();
			$.post(location.href, {
				renderOnly: "Flex:<?php echo $this->id; ?>",
				edit: 1,
				modules: modules
			},function(data) {
				var flexcontent = $("#Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>", data).html();
				$("#Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>").html(flexcontent);
				parent.$(parent.document).trigger('edit-page-content', [$(document)]);
				enableFlex<?php echo $this->id; ?>();
			});
		},
		containment: $('#Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>')
	});
	$("ul#flextemplate<?php echo $this->id; ?>").sortable({
		connectWith: 'ul#flexcontent<?php echo $this->id; ?>',
		containment: $('#Flex-<?php echo $this->id; ?>-<?php echo $this->idartlang; ?>')
	});
}
enableFlex<?php echo $this->id; ?>();