<div class="page_margins">
	<div class="page">
		<div id="header">
			<script type="application/x-aitsu" src="Template:Header">
				defaultTemplate = templates/body/header/header.phtml
			</script>
		</div>
		<!-- 
		<div id="teaser">
			<script type="application/x-aitsu" src="Template:Teaser">
	    		defaultTemplate = templates/body/teaser/teaser.phtml
    		</script>
    	</div>
    	 -->
		<div id="main">
			<script type="application/x-aitsu" src="Template:Main">
				defaultTemplate = 2cols

				template.2cols.file = templates/body/main/main2cols.phtml
				template.2cols.name = 2 columns

				template.3cols.file = templates/body/main/main3cols.phtml
				template.3cols.name = 3 columns

				template.nocols.file = templates/body/main/main.phtml
				template.nocols.name = no columns
			</script>
		</div>
		<div id="footer">
			<script type="application/x-aitsu" src="Template:Footer">
				defaultTemplate = templates/body/footer/footer.phtml
			</script>
		</div>
	</div>
</div>