<div class="tabs">
	<ul>
		<li>
			<a href="#tab-translate"><?php echo $this->translate('Translations'); ?></a>
		</li>
	</ul>
	
	<div id="tab-translate">
		<table border="0" cellpadding="0" cellspacing="0" class="full">
			<thead>
				<tr>
					<th scope="col"><?php echo $this->translate('ID'); ?></th>
					<th scope="col"><?php echo $this->translate('Key'); ?></th>
					<th scope="col"><?php echo $this->translate('Value'); ?></th>
				</tr>
			</thead>
			<tbody>
				<?php foreach ($this->translations as $translation) : ?>
					<tr>
						<td><?php echo $translation->translationid; ?></td>
						<td><?php echo $translation->tkey; ?></td>
						<td><?php echo $translation->tvalue; ?></td>
					</tr>
				<?php endforeach; ?>
			</tbody>
		</table>
	</div>
		
</div>