var center = Ext.getCmp('viewport-center');
center.removeAll();

var configGrid = new Ext.grid.GridPanel({
	id: 'configuration-grid',
	title: '<?php echo Aitsu_Translate :: translate('Config sets'); ?>',
	store: new Ext.data.JsonStore({
        autoDestroy: true,
        url: '<?php echo $this->url(array('action' => 'store')); ?>',
        remoteSort: false,
        storeId: 'configStore',
        idProperty: 'roleid',
        root: 'data',
        fields: [{
            name: 'configsetid'
        }, {
            name: 'identifier'
        }]
    }),
    columns: [
    	{dataIndex: 'configsetid', header: 'ID', menuDisabled: false, sortable: false, width: 20},
    	{dataIndex: 'identifier', header: '<? echo Aitsu_Translate :: translate('Identifier'); ?>', menuDisabled: false, sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	border: false,
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Add new configset'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	Ext.aitsu.load(['<?php echo $this->url(array('action' => 'edit')); ?>']);
	            }
	        }
	    ]
	},
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		},
		rowclick: function(grid, rowIndex, event) {
			var id = this.getStore().getAt(rowIndex).get('configsetid');
			Ext.aitsu.load(['<?php echo $this->url(array('action' => 'edit')); ?>'], null, {configsetid: id});
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete config set'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected config set?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('action' => 'delete')); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Config set removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected role has been removed.'); ?>');
					            			var store = grid.getStore().remove(record); 
				            			}
				            		},
				            		params: { configsetid: record.get('configsetid') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}
			
	}
});

center.add(configGrid);

Ext.getCmp('viewport').doLayout();
