<div class="toolbar ui-corner-bottom">
	<button id="save" class="confirm" title="<?php echo $this->translate('save'); ?>"><?php echo $this->translate('save'); ?></button>
</div>

<?php echo $this->form ?>

<script type="text/javascript">
$(function() {
	
	$('button#save').button({icons: {primary: 'ui-icon-circle-check'}, text:false});
	$('button#save').click(function() {
		$(this).parents('.tab-content').find('form button[type=submit]').trigger('click');
	});

});
</script>