<?php $art = (object) $this->articles[0]; ?>
<h3><?php echo Aitsu_Translate :: _('Aktuell'); ?></h3>
<dl>
	<dt>
		<a href="{ref:idart-<?php echo $art->idart; ?>}" title="<?php echo $art->title; ?>">
			<img title="<?php echo $art->title; ?>" src="/image/240/120/1/<?php echo $art->idart; ?>/<?php echo $art->image; ?>" width="240" height="120" alt="<?php echo $art->title; ?>" />
		</a>
	</dt>
	<dd>
		<h4>
			<a href="{ref:idart-<?php echo $art->idart; ?>}" title="<?php echo $art->title; ?>">
				<?php echo $art->title; ?>
			</a>
		</h4>
	</dd>
	<dd>
		<p>
			<a href="{ref:idart-<?php echo $art->idart; ?>}" title="<?php echo $art->title; ?>">
				<?php echo $art->teaser; ?>
				<span class="more"><?php echo Aitsu_Translate :: _('More...'); ?></span>
			</a>
		</p>
	</dd>
</dl>