var centerSouth = Ext.getCmp('center-south');
centerSouth.setVisible(true);
centerSouth.expand();

if (typeof(Ext.getCmp('system-log')) == 'undefined') {
    var expander = new Ext.ux.grid.RowExpander({
        tpl : new Ext.Template(
            '<pre>{full}</pre>'
        )
    });	
	
	Ext.getCmp('center-south-tab').add(new Ext.grid.GridPanel({
		id: 'system-log',
		title: '<?php echo Aitsu_Translate :: translate('Log'); ?>',
		closable: true,
		store: new Ext.data.JsonStore({
	        autoDestroy: true,
	        url: '<?php echo $this->url(array('paction' => 'store')); ?>',
	        remoteSort: false,
	        storeId: 'logStore',
	        root: 'data',
	        fields: [{
	            name: 'time',
	            type: 'date',
	            dateFormat: 'H:i:s'
	        }, {
	            name: 'type'
	        }, {
	            name: 'entry'
	        }, {
	            name: 'full'
	        }]
	    }),
	    columns: [
	    	expander,
	    	{dataIndex: 'time', header: '<?php echo Aitsu_Translate :: translate('Time'); ?>', menuDisabled: false, sortable: true, width: 10, renderer: Ext.util.Format.dateRenderer('H:i:s')},
	    	{dataIndex: 'type', header: '<? echo Aitsu_Translate :: translate('Type'); ?>', menuDisabled: false, sortable: false, width: 10},
	    	{dataIndex: 'entry', header: '<? echo Aitsu_Translate :: translate('Entry'); ?>', menuDisabled: false, sortable: true, width: 100}
		],
		viewConfig: {
			forceFit: true,
			autoFill: true
		},
		border: false,
		listeners: {
			render: {
				fn: function(){
					this.getStore().load();
				}
			}
		},
		plugins: expander,
		tbar: {
			items: [
				{
		            tooltip: '<?php echo Aitsu_Translate :: translate('Delete log'); ?>',
		            iconCls: 'delete',
		            handler: function(b, e) {
		            	Ext.Ajax.request({
						   url: '<?php echo $this->url(array('paction' => 'delete')); ?>',
						   success: function(response, opts) {
						      Ext.getCmp('system-log').getStore().load();
						   }
						});
		            }
		        },
				{
		            tooltip: '<?php echo Aitsu_Translate :: translate('Refresh log'); ?>',
		            iconCls: 'tb-refresh',
		            handler: function(b, e) {
		            	Ext.getCmp('system-log').getStore().load();
		            }
		        }
		    ]
		}
	}));
	Ext.getCmp('viewport').doLayout();
}

Ext.getCmp('center-south-tab').activate('system-log');
