<!-- rezepte -->
<?php foreach ($this->articles as $article) : ?>
<div id='rezept<?php echo $article->idart; ?>' class='panel' scrolling='yes' data-footer='footerui4'>
	<script>
    	function init_carousel_Rezepte<?php echo $article->idart; ?>() {
        	$('#carousel_Rezepte<?php echo $article->idart; ?>').carousel({
            	pagingDiv: 'carousel_dots_Rezepte',
            	pagingCssName: 'carousel_paging',
            	pagingCssNameSelected: 'carousel_paging_selected'
            });
        }
        document.addEventListener('DOMContentLoaded', init_carousel_Rezepte<?php echo $article->idart; ?>, false);
    </script>
	<div id="carousel_dots_Rezepte" style="margin: 0; top: 5px; left: 5px; position: absolute; height: 10px; z-index: 100; background: none; width: 320px; text-align: right"></div>

<div id='carousel_Rezepte<?php echo $article->idart; ?>' style='overflow: hidden; height: 100%; width: 100%; float: left;'>
<div class="<?php echo $article->summary; ?>" style='float: left; width: 320px; height: auto; background: white; overflow-y: auto;'>
	<div style="margin: 35px 0 0 20px; height: 100px; width: 280px; background: url(/skin/images/icons/icon-<?php echo $article->summary; ?>.png) no-repeat right top; ">
    	<h1><?php echo $article->pagetitle; ?></h1>
        <h2><?php echo $article->teasertitle; ?></h2>
	</div>
	<?php $images = unserialize($article->bild); ?>

	<div style="margin: 0;">
		<?php foreach ($images as $image) : ?>
		<div style="margin: 0 auto; text-align: center"><img src="/image/320/285/2/<?php echo $article->idart; ?>/<?php echo $image; ?>" title="<?php echo $article->pagetitle; ?>"></div>
		<?php endforeach; ?>
		</div>
	</div>
	<div class="<?php echo $article->summary; ?>" style='float: left; width: 320px; height: auto; background: white; overflow-y: auto;'>
		<div style="margin: 35px 0 0 20px; height: 100px; width: 280px; background: url(/skin/images/icons/icon-<?php echo $article->summary; ?>.png) no-repeat right top; ">
    		<h1><?php echo $article->pagetitle; ?></h1>
    		<h2><?php echo $article->teasertitle; ?></h2>
        </div>
		<div style="margin: 45px 15px 100px 20px;">
			<div style="margin: 0 50px 20px 0;">
  	    	  	 <h2 class="<?php echo $article->summary; ?>"><?php echo $article->intro; ?></h2>
  	    	</div>
  	    	<?php echo $article->content; ?>    
  	    </div>
</div>
</div>
</div>
<?php endforeach; ?>
