<!-- weineincat -->
<?php $i=1; foreach ($this->articles as $article) : ?>
<?php $idcat = Aitsu_Util::getIdCatByIdArt($article->idart); ?>
<ul  data-role="listview" data-inset="true" style="margin-top: 00px; padding-top: 0;" >
<li class="<?php echo $article->summary; ?>" style="margin-left: 75px; margin: 0; padding: 0 0 10px 0; background: none; height: 40px; border-bottom: 1px solid #000;">
<a style="margin-left: 10px; font-family: 'KieviBol'; font-size: 17px; line-height: 17px; text-transform: capitalize;" href="#wein<?php echo $article->idart; ?>" ><?php echo $article->pagetitle; ?><br />
<h2><?php echo $article->teasertitle; ?></h2></a>
</li>
</ul>	
<?php $i++; endforeach; ?>