<!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
    <head>
        <meta charset="utf-8" />

        <!-- Set the viewport width to device width for mobile -->
        <meta name="viewport" content="width=device-width" />

        <script type="application/x-aitsu" src="HTML.Meta.PageTitle">
            suffix = " | moraso CMS &mdash; by webtischlerei &mdash; Die Agentur für Online-Marketing aus Hoya an der Weser"
        </script>
        <script type="application/x-aitsu" src="HTML.Meta.BaseHref"></script>
        <script type="application/x-aitsu" src="HTML.Meta.CanonicalTag"></script>
        <script type="application/x-aitsu" src="HTML.Meta.Tags"></script>

        <!-- Included CSS Files (Compressed) -->
        <link rel="stylesheet" href="skin/stylesheets/foundation.min.css">
        <link rel="stylesheet" href="skin/stylesheets/app.css">

        <script src="skin/javascripts/modernizr.foundation.js"></script>
    </head>
    <body>
        <script type="application/x-aitsu" src="Template:Body">
            defaultTemplate = default

            template.default.name = "Standard"
            template.default.file = "templates/body/default.phtml"
        </script>
    </body>
</html>