<form action="<?php echo $_SERVER['REQUEST_URI']; ?>" method="post">
	<div>
		<script type="text/javascript" src="http://www.google.com/recaptcha/api/challenge?k=<?php echo Aitsu_Config :: get('captcha.recaptcha.key.public'); ?>"></script>
		<noscript>
			<iframe src="http://www.google.com/recaptcha/api/noscript?k=your_public_key" height="300" width="500" frameborder="0"></iframe>
			<br />
			<textarea name="recaptcha_challenge_field" rows="3" cols="40"></textarea>
			<input type="hidden" name="recaptcha_response_field" value="manual_challenge">
		</noscript>
	</div>
	<div>
		<input type="submit" name="Verifizieren" value="Verifizieren" />
	</div>
</form>

<pre><?php echo var_export($_POST, true); ?></pre>

<pre><?php echo var_export(Aitsu_User_Status :: isHuman()); ?></pre>

<pre><?php echo var_export(Aitsu_User_Status :: pageStack()); ?></pre>