<div class="tabs">
	<ul>
		<li>
			<a href="#tab-uuid"><?php echo $this->translate('UUID'); ?></a>
		</li>
	</ul>
	
	<div id="tab-uuid">
		<div class="tab-content">
			<div class="toolbar empty"></div>
		
			<div class="sized-content-empty-toolbar">
				<?php for ($i = 0; $i < 100; $i++) : ?>
					<div style="width:250px; margin-right:25px; float:left;">
						<pre><?php echo Aitsu_Util_Uuid :: generate(); ?></pre>
					</div>
				<?php endfor; ?>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>
</div>
