<script type="application/x-moraso" src="Navigation:main"></script>

<div class="hide-for-small">
    <div class="row">
        <div class="large-6 columns">
            <div id="featured" data-orbit>
                <img src="http://placehold.it/1000x400&text=Slide Image 1" alt="slide image">
                <img src="http://placehold.it/1000x400&text=Slide Image 2" alt="slide image">
                <img src="http://placehold.it/1000x400&text=Slide Image 3" alt="slide image">
            </div>
        </div>

        <div class="large-6 columns">
            <div id="featured" data-orbit>
                <img src="http://placehold.it/1000x400&text=Slide Image 4" alt="slide image">
                <img src="http://placehold.it/1000x400&text=Slide Image 5" alt="slide image">
                <img src="http://placehold.it/1000x400&text=Slide Image 6" alt="slide image">
            </div>
        </div>
    </div>
</div>

