<nav class="top-bar">
    <ul class="title-area">
        <li class="name">
            <h1><a href="{ref:idcat-0}">moraso CMS</a></h1>
        </li>
        <li class="toggle-topbar menu-icon">
            <a href="#"><span>menu</span></a>
        </li>
    </ul>

    <section class="top-bar-section">
        <?php echo Moraso_Html_Helper_Navigation_Foundation_Topbar::getHtml($this->nav, null, array('right')); ?>
    </section>
</nav>