var center = Ext.getCmp('viewport-center');
center.removeAll();

var tabs = new Ext.TabPanel({
	resizeTabs: false,
	minTabWidth: 115,
	tabWidth:135,
	enableTabScroll:true,
	defaults: {
		autoScroll:true
	}
});

center.add(tabs);

<?php echo $this->partial('acl/userlist.phtml', array('users' => $this->users)); ?>
<?php echo $this->partial('acl/rolelist.phtml', array('roles' => $this->roles)); ?>
<?php echo $this->partial('acl/privilegelist.phtml', array('privileges' => $this->privileges)); ?>

tabs.setActiveTab(0);

Ext.getCmp('viewport').doLayout();
