<div class="toolbar">
	<button id="add-new-privilege" class="type-new confirm"><?php echo $this->translate('Add new privilege'); ?></button>
</div>

<div class="sized-content">		
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col" style="width:70px;"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Identifier'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $counter = 0; foreach ($this->privileges as $privilege) : $counter++; ?>
				<tr id="privilege-<?php echo $privilege->privilegeid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
					<td><?php echo $privilege->privilegeid; ?></td>
					<td><?php echo $privilege->identifier; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>