<div class="toolbar ui-corner-bottom">
	<button id="add-new-resource" class="type-new confirm"><?php echo $this->translate('Add new resource'); ?></button>
</div>
		
<div class="sized-content">
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col" style="width:70px;"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Name'); ?></th>
				<th scope="col"><?php echo $this->translate('Type'); ?></th>
				<th scope="col"><?php echo $this->translate('Identifier'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $type = array('cat' => 'Category', 'art' => 'Article / dataset'); ?>
			<?php $counter = 0; foreach ($this->resources as $resource) : $counter++; ?>
				<tr id="resource-<?php echo $resource->resourceid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
					<td><?php echo $resource->resourceid; ?></td>
					<td><?php echo $resource->name; ?></td>
					<?php if ($resource->resourcetype == 'other') : ?>
						<td><?php echo $resource->specifictype; ?></td>
					<?php else : ?>
						<td><?php echo $type[$resource->resourcetype]; ?></td>
					<?php endif; ?>
					<td><?php echo $resource->identifier; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>