var resources = new Ext.grid.GridPanel({
	title: '<?php echo Aitsu_Translate :: translate('Resources'); ?>',
	store: new Ext.data.JsonStore({
        autoDestroy: true,
        url: '<?php echo $this->url(array('controller' => 'store', 'action' => 'resources'), 'default'); ?>',
        remoteSort: false,
        storeId: 'resourceStore',
        idProperty: 'resourceid',
        root: 'data',
        fields: [{
            name: 'resourceid'
        }, {
            name: 'resourcetype'
        }, {
            name: 'name'
        }]
    }),
    columns: [
    	{dataIndex: 'resourceid', header: 'ID', menuDisabled: false, sortable: false, width: 20},
    	{dataIndex: 'name', header: '<?php echo Aitsu_Translate :: translate('Identifier'); ?>', menuDisabled: false, sortable: true},
    	{dataIndex: 'resourcetype', header: '<?php echo Aitsu_Translate :: translate('Type'); ?>', menuDisabled: false, sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	border: false,
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Add new resource'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	Ext.Loader.load(['<?php echo $this->url(array('controller' => 'acl', 'action' => 'editresource'), 'default'); ?>?'], null, this, false);
	            }
	        }
	    ]
	},
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		},
		rowclick: function(grid, rowIndex, event) {
			var id = this.getStore().getAt(rowIndex).get('resourceid');
			Ext.Loader.load(['<?php echo $this->url(array('controller' => 'acl', 'action' => 'editresource'), 'default'); ?>?resourceid=' + id], null, this, false);
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete resource'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected resource?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('controller' => 'acl', 'action' => 'deleteresource'), 'default'); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Resource removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected resource has been removed.'); ?>');
					            			var store = grid.getStore().remove(record); 
				            			}
				            		},
				            		params: { resourceid: record.get('resourceid') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}
			
	},
	plugins: [
		new Ext.ux.grid.GridFilters({
			encode: false,
	        local: false,
	        filters: [{
	            type: 'numeric',
	            dataIndex: 'resourceid'
	        }, {
	            type: 'string',
	            dataIndex: 'resourcetype'
	        }, {
	            type: 'string',
	            dataIndex: 'name'
	        }]
		})
	]
});

tabs.add(resources);
<?php return; ?>
<div class="toolbar ui-corner-bottom">
	<button id="add-new-resource" class="type-new confirm"><?php echo $this->translate('Add new resource'); ?></button>
</div>
		
<div class="sized-content">
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col" style="width:70px;"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Name'); ?></th>
				<th scope="col"><?php echo $this->translate('Type'); ?></th>
				<th scope="col"><?php echo $this->translate('Identifier'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $type = array('cat' => 'Category', 'art' => 'Article / dataset'); ?>
			<?php $counter = 0; foreach ($this->resources as $resource) : $counter++; ?>
				<tr id="resource-<?php echo $resource->resourceid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
					<td><?php echo $resource->resourceid; ?></td>
					<td><?php echo $resource->name; ?></td>
					<?php if ($resource->resourcetype == 'other') : ?>
						<td><?php echo $resource->specifictype; ?></td>
					<?php else : ?>
						<td><?php echo $type[$resource->resourcetype]; ?></td>
					<?php endif; ?>
					<td><?php echo $resource->identifier; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>