var resources = new Ext.grid.GridPanel({
	title: '<?php echo Aitsu_Translate :: translate('Resources'); ?>',
	store: new Ext.data.JsonStore({
        autoDestroy: true,
        url: '<?php echo $this->url(array('controller' => 'store', 'action' => 'resources'), 'default'); ?>',
        remoteSort: false,
        storeId: 'resourceStore',
        idProperty: 'resourceid',
        root: 'data',
        fields: [{
            name: 'resourceid'
        }, {
            name: 'resourcetype'
        }, {
            name: 'name'
        }]
    }),
    columns: [
    	{dataIndex: 'resourceid', header: 'ID', menuDisabled: false, sortable: false, width: 20},
    	{dataIndex: 'name', header: '<?php echo Aitsu_Translate :: translate('Identifier'); ?>', menuDisabled: false, sortable: true},
    	{dataIndex: 'resourcetype', header: '<?php echo Aitsu_Translate :: translate('Type'); ?>', menuDisabled: false, sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	border: false,
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Add new resource'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	Ext.aitsu.load(['<?php echo $this->url(array('controller' => 'acl', 'action' => 'editresource'), 'default'); ?>?']);
	            }
	        }
	    ]
	},
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		},
		rowclick: function(grid, rowIndex, event) {
			var id = this.getStore().getAt(rowIndex).get('resourceid');
			Ext.aitsu.load(['<?php echo $this->url(array('controller' => 'acl', 'action' => 'editresource'), 'default'); ?>?resourceid=' + id]);
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete resource'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected resource?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('controller' => 'acl', 'action' => 'deleteresource'), 'default'); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Resource removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected resource has been removed.'); ?>');
					            			var store = grid.getStore().remove(record); 
				            			}
				            		},
				            		params: { resourceid: record.get('resourceid') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}
			
	},
	plugins: [
		new Ext.ux.grid.GridFilters({
			encode: false,
	        local: false,
	        filters: [{
	            type: 'numeric',
	            dataIndex: 'resourceid'
	        }, {
	            type: 'string',
	            dataIndex: 'resourcetype'
	        }, {
	            type: 'string',
	            dataIndex: 'name'
	        }]
		})
	]
});

tabs.add(resources);
