<div class="toolbar ui-corner-bottom">
	<button id="add-new-role" class="type-new confirm"><?php echo $this->translate('Add new role'); ?></button>
</div>
		
<div class="sized-content">
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col" style="width:70px;"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Identifier'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $counter = 0; foreach ($this->roles as $role) : $counter++; ?>
				<tr id="role-<?php echo $role->roleid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
					<td><?php echo $role->roleid; ?></td>
					<td><?php echo $role->identifier; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>