<!-- all right -->
<p class="icaption_right">
<img<?php echo $this->id; ?><?php echo $this->class; ?><?php echo $this->style; ?> src="<?php echo Aitsu_Registry :: get()->config->sys->webpath; ?>image/150/150/1/<?php echo $this->images[0]->idart; ?>/<?php echo $this->images[0]->filename; ?>" 
<?php echo $this->title; ?> <?php if(isset($this->alt)) : ?><?php echo $this->alt; ?><?php else : ?> alt="<?php echo $this->images[0]->name; ?>" /><?php endif; ?>
<?php if(isset($this->images[0]->name)) : ?>
	<strong><?php echo $this->images[0]->name; ?></strong>
<?php endif; ?>
<?php if(isset($this->images[0]->subline)) : ?>
	<strong><?php echo $this->images[0]->subline; ?></strong>
<?php endif; ?>
<?php if(isset($this->images[0]->description)) : ?>
	<strong><?php echo $this->images[0]->description; ?></strong>
<?php endif; ?>
</p>