<div id="modul_config_images_<?php echo $this->config->name; ?>">
	<?php foreach ($this->config->files as $file) : $name = empty($file->name) ? $file->filename : $file->name;?>
	<?php $currentValue = $this->config->currentValue() == null ? array() : (array) $this->config->currentValue(); ?>
	<div style="width: 55px; height: 55px; float: left;">
		<input type="hidden" name="configType[<?php echo $this->config->name; ?>]" value="<?php echo $this->config->type; ?>" />

		<input name="config[<?php echo $this->config->name; ?>][<?php echo $file->mediaid; ?>]" type="hidden" value="" />		
		<?php if (in_array($file->mediaid, $currentValue)) : ?>
		<input id="checkbox_<?php echo $this->config->name; ?>_<?php echo $file->mediaid; ?>" name="config[<?php echo $this->config->name; ?>][<?php echo $file->mediaid; ?>]" type="checkbox" value="<?php echo $file->mediaid; ?>" style="display: none"; checked="checked" />
		<img id="<?php echo $this->config->name; ?>_<?php echo $file->mediaid; ?>" src="<?php echo $this->url(array('controller' => 'image', 'action' => 'media', 'width' => 55, 'height' => 55, 'boxed' => 1, 'id' => $file->mediaid), 'default'); ?>" alt="<?php echo $name ?>" title="<?php echo $name ?>" style="width: 35px; height: 35px; top: 10px; left: 10px; position: relative;" />
		<?php else: ?>
		<input id="checkbox_<?php echo $this->config->name; ?>_<?php echo $file->mediaid; ?>" name="config[<?php echo $this->config->name; ?>][<?php echo $file->mediaid; ?>]" type="checkbox" value="<?php echo $file->mediaid; ?>" style="display: none"; />
		<img id="<?php echo $this->config->name; ?>_<?php echo $file->mediaid; ?>" src="<?php echo $this->url(array('controller' => 'image', 'action' => 'media', 'width' => 55, 'height' => 55, 'boxed' => 1, 'id' => $file->mediaid), 'default'); ?>" alt="<?php echo $name ?>" title="<?php echo $name ?>" style="width: 35px; height: 35px; top: 10px; left: 10px; position: relative;" />
		<?php endif; ?>
	</div>
	<?php endforeach; ?>
</div>

<script type="text/javascript">
$(document).ready(function() {
	setTimeout(function() { 	
		images = $("#modul_config_images_<?php echo $this->config->name; ?>").find("img");

		zoomOut(images);
		selectedImages = $(images).attr("checked");
		zoomIn(selectedImages);
		
		$(images).hover(function () {
			zoomIn(this);
		}, function () {
			if ($(this).attr("checked") != "checked") {
				zoomOut(this);
			}
		});

		function zoomIn (element) {
			$(element).animate({
			    opacity: 1,
			    width: 55,
			    height: 55,
			    top: 0,
			    left: 0
			  }, 150);
		}

		function zoomOut (element) {
			$(element).animate({
			    opacity: 0.4,
			    width: 35,
			    height: 35,
			    top: 10,
			    left: 10
			}, 50);
		}
		
		$(images).each(function() {
			checked = $("#checkbox_" + $(this).attr("id")).is(':checked');
			
			if (checked) {
				zoomIn(this);
				$(this).attr("checked", "checked");
			}
			
			$(this).bind("click", function() {
				if ($("#checkbox_" + $(this).attr("id")).is(':checked')) {
					$("#checkbox_" + $(this).attr("id")).removeAttr("checked");
					$(this).removeAttr("checked");
				} else {
					$("#checkbox_" + $(this).attr("id")).attr("checked", "checked");
					$(this).attr("checked", "checked");
				}
		    });
		});
	}, 500);
});
</script>