<div class="type-select">
	<input type="hidden" name="configType[<?php echo $this->config->name; ?>]" value="<?php echo $this->config->type; ?>" />
	
	<label for="<?php $id = uniqid(); echo $id; ?>"><?php echo $this->config->label; ?></label>
	<select id="<?php echo $id; ?>" name="config[<?php echo $this->config->name; ?>]" size="1">
	<?php foreach ($this->config->keyValuePairs as $key => $value) : ?>
		<?php if ($this->config->currentValue() == $value) : ?>
		<option value="<?php echo $value; ?>" selected="selected"><?php echo $key; ?></option>
		<?php else : ?>
		<option value="<?php echo $value; ?>"><?php echo $key; ?></option>
		<?php endif; ?>
	<?php endforeach; ?>
	</select>
</div>