<div class="type-text">
	<input type="hidden" name="configType[<?php echo $this->config->name; ?>]" value="<?php echo $this->config->type; ?>" />
		
	<label for="<?php echo $this->config->index; ?>_<?php echo $this->config->name; ?>"><?php echo $this->config->label; ?></label>
	<input id="<?php echo $this->config->index; ?>_<?php echo $this->config->name; ?>" name="config[<?php echo $this->config->name; ?>]" type="text" value="<?php echo $this->config->currentValue(); ?>" />
</div>