<!-- 25% | 25% | 25% | 25% -->
<div<?php echo $this->id . $this->class . $this->style; ?>>
	<div class="c25l">
		<div class="subcl">
			<script type="application/x-aitsu" src="HTML:Copy<?php echo $this->index; ?>1"></script>
		</div>
	</div>
	<div class="c25l">
		<div class="subc">
			<script type="application/x-aitsu" src="HTML:Copy<?php echo $this->index; ?>2"></script>
		</div>
	</div>
	<div class="c25l">
		<div class="subc">
			<script type="application/x-aitsu" src="HTML:Copy<?php echo $this->index; ?>3"></script>
		</div>
	</div>
	<div class="c25r">
		<div class="subcr">
			<script type="application/x-aitsu" src="HTML:Copy<?php echo $this->index; ?>4"></script>
		</div>
	</div>
</div>