Ext.getCmp('viewport-east').setVisible(false);
Ext.getCmp('viewport-west').setVisible(false);

var center = Ext.getCmp('viewport-center');
center.removeAll();

center.add({
	id: 'dashboard',
	unstyled: true,
	layout: 'column',
	bodyStyle:'padding:4px',
	items: [
		{
			columnWidth: 1/3,
			baseCls:'x-plain',
			bodyStyle:'padding:6px 4px 0 4px',
			items: {
				unstyled: true,
				height: 370,
				layout: 'fit',
				items: {
					html: 'das ist ein test'
				}
			}
		}
	]
});

<?php for ($i = 0; $i < count($this->plugins); $i++) : $plugin = $this->plugins[$i]; ?>
Ext.Loader.load(['<?php echo $this->url(array('controller' => 'plugin')); ?>'], null, this, false);
<?php endfor; ?>

Ext.getCmp('viewport').doLayout();
