<div id="file-accordion" class="left-accordion">
	<div class="accordion">
		<h3>
			<a href="#">
				<?php echo $this->translate('File selection'); ?>
			</a>
		</h3>
		<div>
			<div id="file-tree"></div>
		</div>		
	</div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {
	
	$('#file-tree').jstree({
		"themes" : {
            "theme" : "aitsu",
            "dots" : false,
            "icons" : true
        },
        "json_data" : {
            "ajax" : {
                "url" : "<?php echo $this->url(array('area' => 'layout', 'plugin' => 'skin', 'paction' => 'fscontent'), 'plugin'); ?>",
                "data" : function (n) {
                    return { id : n.attr ? n.attr("id") : 0 };
                },
                "progressive_render" : true
            }
        },
        "cookies" : {
        	"save_opened" : "file_tree_opened",
        	"save_selected" : false
        },
        "plugins" : [ "themes", "json_data", "dnd", "ui", "cookies" ]
    });
	
});
<?php $this->inlineScript()->captureEnd(); ?>