<?php if ($this->articles) : ?>
	<?php foreach ($this->articles as $article) : $article = (object) $article; ?>
	<div class="subcolumns news<?php if ($this->class !== null) {echo ' ' . $this->class;} ?>">
		<div class="c40l">
			<div class="subcl">
				<img title="<?php echo $article->title; ?>" src="/image/240/120/1/<?php echo $article->idart; ?>/<?php echo $article->image; ?>" width="240" height="120" alt="<?php echo $article->title; ?>" />
			</div>
		</div>
		<div class="c60r">
			<div class="subcr">
				<h4><?php echo $article->title; ?></h4>
				<p>
					<?php echo $article->teaser; ?>
					<a href="{ref:idart-<?php echo $article->idart; ?>}">
						<?php echo Aitsu_Translate :: _('More...'); ?>
					</a>
				</p>
			</div>
		</div>
	</div>
	<?php endforeach; ?>
<?php endif; ?>