<div class="row">
    <div class="large-12 columns">
        <script type="application/x-moraso" src="Navigation:main"></script>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <div class="hide-for-small">
            <div id="featured" data-orbit>
                <img src="http://placehold.it/1000x400&text=Slide Image 1" alt="slide image">
                <img src="http://placehold.it/1000x400&text=Slide Image 2" alt="slide image">
                <img src="http://placehold.it/1000x400&text=Slide Image 3" alt="slide image">
            </div>
        </div>
    </div>
</div>

