<div class="row">
    <div class="large-12 columns">
        <script type="application/x-moraso" src="Navigation:main"></script>
    </div>
</div>

<div class="row">
    <div class="large-12 columns">
        <div class="hide-for-small">
            <div id="featured" data-orbit>
                <script type="application/x-moraso" src="Image:featured">
                    width = 1000
                    height = 400
                </script>
            </div>
        </div>

        <div class="show-for-small">
            <img src="http://placehold.it/1200x400&text=Mobile Header">
        </div>
    </div>
</div>

