CKEDITOR.config.toolbar_normal=[
	['Source','Templates'],
	['Cut','Copy','Paste','PasteText'],
	['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
	['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
	['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],
	'/',
	['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
	['Link','Unlink','Anchor'],
	['Image','Flash','Table','HorizontalRule','SpecialChar'],
	['Styles','Format'],
	['Maximize', 'ShowBlocks','-','About']
];