<div itemscope itemtype="http://schema.org/GeoCoordinates" class="SchemaOrg GeoCoordinates">
	<link itemprop="url" href="<?php echo $this->url; ?>" />
	<?php if (!empty($this->image)) : ?>
		<img itemprop="image" src="<?php echo Aitsu_Config :: get('sys.mainDir'); ?>image/100/100/2/<?php echo $this->idart; ?>/<?php echo $this->image; ?>" width="100" height="100" style="float:right; margin: 0 0 5px 5px;" />
	<?php endif; ?>
	<?php if (!empty($this->description)) : ?>
	<div itemprop="description" style="margin-bottom:10px;"><?php echo htmlentities($this->description, ENT_COMPAT, 'UTF-8'); ?></div>
	<?php endif; ?>
	<dl>
		<?php if (!empty($this->name)) :?>
		<dt>Name:</dt>
			<dd itemprop="name"><?php echo htmlentities($this->name, ENT_COMPAT, 'UTF-8'); ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->elevation)) :?>
		<dt>Elevation:</dt>
			<dd itemprop="elevation"><?php echo $this->elevation; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->latitude)) :?>
		<dt>Latitude:</dt>
			<dd itemprop="latitude"><?php echo $this->latitude; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->longitude)) :?>
		<dt>Longitude:</dt>
			<dd itemprop="longitude"><?php echo $this->longitude; ?></dd>
		<?php endif; ?>
	</dl>
</div>