<div class="row">    
    <div class="large-12 columns">
        <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            tag = h2
        </script>
        
        <hr />
    </div>
</div>

<div class="row"> 
    <div class="large-6 columns">
        <script type="application/x-moraso" src="HTML.Content:Content"></script>
    </div>

    <div class="large-6 columns">        
        <script type="application/x-moraso" src="HTML.Content:Content_2"></script>

        <div class="row">
            <div class="large-6 columns">
                <img src="http://placehold.it/500x500&amp;text=Thumbnail">
            </div>

            <div class="large-6 columns">
                <img src="http://placehold.it/500x500&amp;text=Thumbnail">
            </div>
        </div>
    </div>
</div>