<div class="row">    
    <div class="large-12 columns">
        <script type="application/x-moraso" src="HTML.Meta.PagetitleAsHeadline:Headline">
            tag = h2
        </script>

        <hr />
    </div>
</div>

<div class="row"> 
    <div class="large-6 columns">
        <script type="application/x-moraso" src="HTML.Content:Content"></script>

        <script type="application/x-moraso" src="Search.Lucene"></script>
    </div>

    <div class="large-6 columns">        
        <script type="application/x-moraso" src="HTML.Content:Content_2"></script>

        <div class="row">
            <div class="large-6 columns">
                <script type="application/x-moraso" src="Image:Thumb_1">
                    width = 720
                    height = 720
                    render = 1
                </script>
            </div>

            <div class="large-6 columns">
                <script type="application/x-moraso" src="Image:Thumb_2">
                    width = 720
                    height = 720
                    render = 1
                </script>
            </div>
        </div>
    </div>
</div>