<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
   "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">

	<head>
		<title>Navigation ambassador-immo.ch</title>
		
		<style type="text/css">
			ul.horizontal-top-down {
				list-style-type:none;
				margin:0;
				padding:0;
			}
			ul.horizontal-top-down li {
				width:200px;
				float:left;
				margin-right:10px;
			}
			ul.horizontal-top-down ul {
				list-style-type:none;
				margin:0;
				padding:0;
			}
		</style>
		
	</head>
	
	<body>
	
		<h2>Navigation ambassador-immo.ch</h2>
		
		<p>
			Horizontale Anordnung der Hauptnavigationspunkte ohne Verlinkung und darunter
			vertikal angeordnet eine Ebene mit Link.
		</p>
	
		<script type="application/x-aitsu" src="Navigation">
			idcat = 31
			template = top
		</script>
	
	</body>
	
</html>
