<!-- all right -->
<dl style="float: right; margin: 0 0 0 1em;">
	<dt>
		<img<?php echo $this->id . $this->class . $this->style; ?> src="<?php echo Aitsu_Registry :: get()->config->sys->webpath; ?>image/<?php echo $this->width; ?>/<?php echo $this->height; ?>/<?php echo $this->transform; ?>/<?php echo $this->images[0]->idart; ?>/<?php echo $this->images[0]->filename; ?>" 
<?php echo $this->title; ?> <?php if(isset($this->alt)) : ?><?php echo $this->alt; ?><?php else : ?> alt="<?php echo $this->images[0]->name; ?>" /><?php endif; ?>
	</dt>
<?php if(isset($this->images[0]->name)) : ?>
	<dd class="medianame"><?php echo $this->images[0]->name; ?></dd>
<?php endif; ?>
<?php if(isset($this->images[0]->subline)) : ?>
	<dd class="mediasubline"><?php echo $this->images[0]->subline; ?></dd>
<?php endif; ?>
<?php if(isset($this->images[0]->description)) : ?>
	<dd class="mediadescription"><?php echo $this->images[0]->description; ?></dd>
<?php endif; ?>
</dl>