<!-- image slider -->
<div class="slide">
	<div class="items">
<?php $i=0; foreach($this->images as $image) : ?>
		<div class="imageslider">
			<img<?php echo $this->id . $this->class . $this->style; ?> src="<?php echo Aitsu_Registry :: get()->config->sys->webpath; ?>image/<?php echo $this->width; ?>/<?php echo $this->height; ?>/<?php echo $this->transform; ?>/<?php echo $this->images[$i]->idart; ?>/<?php echo $this->images[$i]->filename; ?>" 
<?php echo $this->title; ?> <?php if(isset($this->alt)) : ?><?php echo $this->alt; ?><?php else : ?> alt="<?php echo $this->images[$i]->name; ?>" /><?php endif; ?>
		</div>
<?php $i++; endforeach; ?>
        </div>
    </div>
	<ul class="imageslider">
<?php $i=0; foreach($this->images as $image) : ?>
		<li>
			<a id="t<?php echo ($i+1); ?>" href="#image<?php echo ($i+1); ?>">
				<img<?php echo $this->id . $this->class . $this->style; ?> src="<?php echo Aitsu_Registry :: get()->config->sys->webpath; ?>image/<?php echo $this->thumbWidth; ?>/<?php echo $this->thumbHeight; ?>/<?php echo $this->thumbTransform; ?>/<?php echo $this->images[$i]->idart; ?>/<?php echo $this->images[$i]->filename; ?>" 
<?php echo $this->title; ?> <?php if(isset($this->alt)) : ?><?php echo $this->alt; ?><?php else : ?> alt="<?php echo $this->images[$i]->name; ?>" /><?php endif; ?>
            </a>
        </li>
<?php $i++; endforeach; ?>
</ul>