<div class="toolbar">
	<button id="add-new-mapping" class="type-new confirm" title="<?php echo $this->translate('New'); ?>"><?php echo $this->translate('New'); ?></button>
</div>

<?php if (empty($this->mappings) || empty($this->mappings->item)) : ?>
	<?php echo $this->translate('The mappings table is currently empty.'); ?>
<?php else : ?>		
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Name'); ?></th>
				<th scope="col"><?php echo $this->translate('Environment'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php foreach ($this->mappings->item as $id => $item) : ?>
				<tr id="mapping-<?php echo $id; ?>">
					<td><?php echo $id; ?></td>
					<td><?php echo $item->name; ?></td>
					<td><?php echo $item->env; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
<?php endif; ?>