<?php
if (is_string($this->media)) {
	$source = $this->media;
} elseif (is_array($this->media)) {
	$media = (object) $this->media[0];
	$source = '/image/640/360/1/' . $media->idart . '/' .  $media->filename;
}
?>
<div id="teaser" style="background-image:url(<?php echo (isset($source) ? $source : ''); ?>);">
	<img title="Teaser" src="/skin/images/wave/empty.png" width="640" height="104" alt="Teaser" />
</div>