<h3>$this->copy</h3>
<pre><?php echo var_export($this->copy, true); ?></pre>
<h3>$this->images</h3>
<pre><?php echo var_export($this->images, true); ?></pre>
<h3>$this->contentConfig</h3>
<pre><?php echo var_export($this->contentConfig, true); ?></pre>
<h3>$this->environment</h3>
<pre><?php echo var_export($this->environment, true); ?></pre>
<?php if(Aitsu_Application_Status :: isEdit()) : ?>
<h3>$this->config</h3>
<pre><?php echo var_export($this->config, true); ?></pre>
<?php endif; ?>
