var east = Ext.getCmp('viewport-east');
east.setVisible(true);
east.expand(false);
east.removeAll();

var comboConfigSet = new Ext.form.ComboBox({
	store: <?php echo json_encode($this->configSets); ?>,
	typeAhead: true,
    mode: 'local',
    triggerAction: 'all',
    emptyText: '[inherit]',
    selectOnFocus: true,
    forceSelection: true
   });

var propsGrid = new Ext.grid.PropertyGrid({
	autoHeight: true,
	source: {
		Name: '<?php echo $this->cat['name']; ?>',
		IdCat: <?php echo $this->cat['idcat']; ?>,
		IdCatLang: <?php echo $this->cat['idcatlang']; ?>,
		Online: <?php echo ($this->cat['visible'] == 1) ? 'true' : 'false'; ?>,
		Public: <?php echo ($this->cat['public'] == 1) ? 'true' : 'false'; ?>,
		Created: new Date(<?php echo $this->cat['createdts'] * 1000; ?>),
		Lastmodified: new Date(<?php echo $this->cat['modifiedts'] * 1000; ?>),
		Urlname: '<?php echo $this->cat['urlname']; ?>',
		ConfigSet: <?php echo empty($this->cat['configsetid']) ? 0 : $this->cat['configsetid']; ?>
	},
	customEditors: {
		ConfigSet: new Ext.grid.GridEditor(comboConfigSet)
	},
	customRenderers: {
        ConfigSet: function(v) {
        	var store = comboConfigSet.getStore();
            return store.getAt(store.findBy(function(record, id) {
            	return record.get('field1') == v;
            })).get('field2');
        }
    },
	viewConfig : {
		forceFit: true,
		scrollOffset: 2
	},
	listeners: {
		beforeedit: function(e) {
			if (/^name|configset|online|public|urlname$/.test(e.record.id.toLowerCase())) {
				return;
			}
			e.cancel = true;
		},
		afteredit: function(e) {
			alert(e.record.id + ' has to be saved. (idcatlang: <?php echo $this->cat['idcatlang']; ?>)');
		}
	}
});
    
east.add(propsGrid);

var center = Ext.getCmp('viewport-center');
center.removeAll();

var tabs = new Ext.TabPanel({
	resizeTabs: false,
	minTabWidth: 115,
	tabWidth:135,
	enableTabScroll:true,
	defaults: {
		autoScroll:true
	}
});

center.add(tabs);

Ext.getCmp('viewport').doLayout();

<?php foreach ($this->plugins as $plugin) : ?>
	Ext.Loader.load(['<?php echo $this->url(array('plugin' => $plugin->name, 'paction' => 'index', 'idcat' => $this->idcat), 'cplugin'); ?>'], null, this, false);
<?php endforeach; ?>

tabs.doLayout();