<div id="article-accordion">
	<div class="accordion">
		<h3><a href="#"><?php echo $this->translate('Synchronisation language'); ?></a></h3>
		<div>
			<form id="sync-lang-form" action="">
				<?php if (count($this->langs) > 1) : ?>
					<div style="margin-bottom:5px;">
						<input type="radio" name="sync-lang" value="" checked="checked" id="sync-lang-0" />
						<label for="sync-lang-0"><?php echo $this->translate('No synchronization'); ?></label>
					</div>
					<?php foreach ($this->langs as $lang) : ?>
						<?php if ($lang->idlang != Aitsu_Registry :: get()->session->currentLanguage) : ?>
							<div style="margin-bottom:5px;">
								<input type="radio" name="sync-lang" value="<?php echo $lang->idlang; ?>" id="sync-lang-<?php echo $lang->idlang; ?>" />
								<label for="sync-lang-<?php echo $lang->idlang; ?>"><?php echo $lang->name; ?> [<?php echo $lang->idlang; ?>]</label>
							</div>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php else : ?>
					<?php echo $this->translate('There is only one language availabe. Therefore there is no language availabe to synchronize from.'); ?>
					<div style="display:none;">
						<input type="radio" name="sync-lang" value="" checked="checked" id="sync-lang-0" />
					</div>
				<?php endif; ?>
			</form>
		</div>		
	
		<h3><a href="#"><?php echo $this->translate('Article tree'); ?></a></h3>
		<div>
			<p id="art-tree"></p>
		</div>
		
		<h3><a href="#"><?php echo $this->translate('Last opened articles'); ?></a></h3>
		<div id="lastopened-articles"></div>
	
		<h3><a href="#"><?php echo $this->translate('Favorits'); ?></a></h3>
		<div id="category-favorites"></div>
	</div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

	$('#article-accordion').relativeSize(window, null, '-105');
	
	window.setTimeout("$('#article-accordion div.accordion').accordion('option', 'active', 1);",1000);
	
	$('#art-tree').jstree({
		"core" : {
			"animation" : 200
		},
		"themes" : {
            "theme" : "aitsu",
            "dots" : false,
            "icons" : true
        },
        "json_data" : {
            "ajax" : {
                "url" : "<?php echo $this->url(array('controller' => 'data', 'action' => 'treecontent'), 'default'); ?>",
                "data" : function (n) {
                    return { id : n.attr ? n.attr("id") : 0, sync : $("#sync-lang-form input[name='sync-lang']:checked").val() };
                },
                "progressive_render" : true
            }
        },
        "cookies" : {
        	"save_opened" : "art-tree-opened",
        	"save_selected" : "art-tree-selected"
        },
        "plugins" : [ "themes", "json_data", "ui", "cookies" ]
    });
	
	$('#art-tree li:not(.article) > a').live('click', function() {
		$.jstree._reference('#art-tree').open_node(this);
		$(document).data('current-category', $(this).closest('li').attr('id'));
		$(document).trigger('load-category-overview');
	});
	
	$(document).bind('refresh-category-overview', function() {
		$('#category-overview').tabs();
		$('.tab-content').relativeSize(window, null, '-200');
		$('#add-new-article').button({icons: {primary: 'ui-icon-circle-plus'}, text:false}); 
		$('#add-to-favorites').button({icons: {primary: 'ui-icon-star'}, text:false}); 
		$('#paste-article').button({icons: {primary: 'ui-icon-clipboard'}, text:false}); 
		$('#remove-from-favorites').button({icons: {primary: 'ui-icon-star'}, text:false}); 
		$('.init-disabled').button('disable');
		$(document).trigger('ctx-article');		
	});
	
	$('#add-new-article').live('click', function() {
		$("#col3_content div.floatbox").load("<?php echo $this->url(array('controller' => 'data', 'action' => 'newarticle')); ?>", {id: $(document).data('current-category')}, function(){
			$(document).trigger('refresh-category-overview');
			$.jstree._reference('#art-tree').refresh($('#' + $(document).data('current-category')));			
		});
	});
	
	$('#add-to-favorites:not(".ui-state-disabled")').live('click', function() {
		var button = $(this);
		$('#category-favorites').load('<?php echo $this->url(array('action' => 'addtofavorites')); ?>', {id: $(this).val()}, function() {
			$('#remove-from-favorites').button('enable');
			button.button('disable');			
		});
	});
	
	$('#remove-from-favorites:not(".ui-state-disabled")').live('click', function() {$
		var button = $(this);
		$('#category-favorites').load('<?php echo $this->url(array('action' => 'removefromfavorites')); ?>', {id: $(this).val()}, function() {
			$('#add-to-favorites').button('enable');
			button.button('disable');
		});		
	});
	
	$('a.article.online, a.article.offline').live('click', function() {
		var item = $(this);
		var id = $(this).attr('href');
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'toggleonline')); ?>", { id: id },
   			function(data){
     			if (data.online == 1) {
     				item.removeClass('offline').addClass('online');
     				$('li#idart-' + id).removeClass('offline').addClass('online');
     			} else {
     				item.removeClass('online').addClass('offline');
     				$('li#idart-' + id).removeClass('online').addClass('offline');     				
     			}
     			item.parent().find('a.article.published').first()
     				.removeClass('published').addClass('unpublished')
     				.attr('title', '<?php echo $this->translate('Publish current version'); ?>');
   		});
   		item.blur();
   		return false;
	});
	
	$('a.article.unpublished').live('click', function() {
		var item = $(this);
		var id = $(this).attr('href');
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'startpublishing')); ?>", { id: id },
   			function(data){
     			if (data.published == 1) {
     				item.removeClass('unpublished').addClass('published');
     				item.attr('title', '<?php echo $this->translate('Current version is online'); ?>');
     			}
   		});
   		item.blur();
   		return false;
	});
	
	$('a.article.published').live('click', function() {
		var item = $(this);
   		item.blur();
   		return false;
	});
	
	$(document).bind('ctx-article', function() {
		$(".editduplicatedelete tr").contextMenu({menu: 'editduplicatedelete'},
		    function(action, el, pos) {
		    	id = $(el).attr('id');
		    	if (action == 'delete') {
			        $("#confirm-delete").dialog({
						resizable: false,
						modal: true,
						buttons: {
							'<?php echo $this->translate('No'); ?>': function() {
								$(this).dialog('close');
							},
							'<?php echo $this->translate('Yes'); ?>': function() {
								$(document).trigger('delete-article', [id]);
								$(this).dialog('close');
							}
						}
					});
		    	} else if (action == 'edit') {
		    		$(document).trigger('edit-article', [id]);
		    	} else if (action == 'duplicate') {
		    		$(document).trigger('duplicate-article', [id]);
		    	} else if (action == 'make-index') {
		    		$(document).trigger('make-index-article', [id]);
		    	} else if (action == 'cut') {
		    		$.post('<?php echo $this->url(array('controller' => 'clipboard', 'action' => 'addarticle'), 'default'); ?>', { id: id },
   						function(data){
     						$('#status').html(data.message);
   						});
		    	}
		        $(document).trigger('bindclicks');
	    }, function() {
	    	$(document).trigger('bindclicks');
	    });
	});	
	
	$(document).bind('delete-article', function(event, id) {
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'delete')); ?>", { id: id },
   			function(data){
   				if (data.status == 'success') {
	   				$('#art-tree li#' + id).remove();
	   				$('tr#' + id).remove();
   				}
   				$('#status').html(data.message);
   		});
	});
	
	$(document).bind('edit-article', function(event, id) {
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'edit')); ?>", { id: id },
   			function(data){
   				$('#col3_content > .floatbox').empty();
   				$('#col3_content > .floatbox').html(data);
   				$('.tabs').tabs();
   				$('.tab-content').relativeSize(window, null, '-200');
   		});
	});
	
	$(document).bind('duplicate-article', function(event, id) {
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'duplicate')); ?>", { id: id },
   			function(data){
   				if (data.status == 'success') {
	   				$(document).trigger('load-category-overview');
					$.jstree._reference('#art-tree').refresh($('#' + $(document).data('current-category')));
   				}
   				$('#status').html(data.message);
   		});
	});
	
	$(document).bind('make-index-article', function(event, id) {
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'makeindex')); ?>", { id: id },
   			function(data){
   				if (data.status == 'success') {
	   				$(document).trigger('load-category-overview');
					$.jstree._reference('#art-tree').refresh($('#' + $(document).data('current-category')));
   				}
   				$('#status').html(data.message);
   		});
	});
	
	$('#sync-lang-form input[type="radio"]').live('change', function() {
		$(document).trigger('load-category-overview');
		$('#article-accordion .accordion').accordion('activate', 1);
	});
	
	$(document).bind('load-category-overview', function() {
		$("#col3_content div.floatbox").load("<?php echo $this->url(array('controller' => 'data', 'action' => 'categoryoverview')); ?>", {id: $(document).data('current-category'), sync : $("#sync-lang-form input[name='sync-lang']:checked").val() }, function(){
			$(document).trigger('refresh-category-overview');			
		});
	});
	
	$('tbody tr.unsynced').live('click', function() {
		$.post("<?php echo $this->url(array('controller' => 'data', 'action' => 'sync')); ?>", { id: $(this).attr('id'), sync: $("#sync-lang-form input[name='sync-lang']:checked").val() },
   			function(data){
   				if (data.status == 'success') {
	   				$(document).trigger('load-category-overview');
					$.jstree._reference('#art-tree').refresh($('#' + $(document).data('current-category')));
   				}
   				$('#status').html(data.message);
   		});
	});

	$('.editduplicatedelete tbody tr:not(.unsynced)').live('click', function() {
		$(document).trigger('edit-article', [$(this).attr('id')]);
	});
	
	$('#art-tree li.article').live('click', function() {
		$(document).trigger('edit-article', [$(this).attr('id')]);
	});
	
	$('#lastopened-articles').load("<?php echo $this->url(array('action' => 'lastopened')); ?>");
	$('#category-favorites').load("<?php echo $this->url(array('action' => 'favorites')); ?>");
	
	$('#lastopened-articles table tr').live('click', function() {
		$(document).trigger('edit-article', [$(this).attr('id')]);
	});

	$('#lastopened-overview tr').live('click', function() {
		$(document).trigger('edit-article', [$(this).attr('id')]);
	});
	
	$('#category-favorites tr').live('click', function() {
		$('#article-accordion div.accordion').accordion('activate', 1);
		jQuery.jstree._reference($('#art-tree')).close_all();
		$.post('<?php echo $this->url(array('action' => 'catpath')); ?>', {id: $(this).attr('id')}, function(data) {
  			$('#art-tree').openNode(data, 0);
		});
	});
	
});
<?php $this->inlineScript()->captureEnd(); ?>