Ext.getCmp('viewport-east').setVisible(false);

var center = Ext.getCmp('viewport-center');
center.removeAll();

center.add(new Ext.TabPanel(
	{
		id: 'page-edit-tab',
		resizeTabs: false,
		minTabWidth: 115,
		tabWidth:135,
		enableTabScroll:true,
		defaults: {
			autoScroll:true
		},
		tabPosition: 'top'
	}
));

Ext.getCmp('page-edit-tab').add({
	title: '<?php echo Aitsu_Translate :: translate('Meta data'); ?>',
	layout: 'border',
	items: [
		{
			region: 'center',
			split: true,
			html: 'hier kommen die notizen hin.'
		},
		{
			region: 'east',
			split: true,
			width: 350,
			layout: 'fit',
			items: new Ext.Panel({
				layout: 'accordion',
				border: false,
				id: 'page-plugin-accordion',
				layoutConfig: {
					titleCollapse: true,
			        hideCollapseTool: true,
			        animate: true
			    }
			})
		}
	]
});