<table border="0" cellpadding="0" cellspacing="0" class="full">
	<tbody>
		<?php $counter = 0; foreach ($this->articles as $article) : $article = (object) $article; $counter++; ?>
			<tr id="idart-<?php echo $article->idart; ?>" class="<?php echo ($counter % 2 == 0 ? 'odd' : 'even'); ?>" style="cursor:pointer;">
				<td>
					<div style="font-weight:bold;">
						<?php echo $article->title; ?>
					</div>
					<div style="font-size:80%;">
						(<?php echo $article->idart; ?> [<?php echo $article->idartlang; ?>], <?php echo $article->name; ?>)
					</div>
				</td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>