<div id="hcard-<?php echo $this->index; ?> class="vcard">
<?php if($this->company) : ?>
	<div class="org"><?php echo $this->company;?></div>
<?php endif; ?>
<?php if($this->webaddress) : ?>
	<a class="url fn" href="<?php echo $this->webaddress;?>"><?php echo $this->firstname;?> <?php echo $this->lastname;?></a>
<?php else : ?>
	<span class="url fn"><?php echo $this->firstname;?> <?php echo $this->lastname;?></span>
<?php endif; ?>
<?php if($this->email) : ?>
	<a class="email" href="mailto:<?php echo $this->email;?>"><?php echo $this->email;?></a>
<?php endif; ?>
<?php if($this->street || $this->city || $this->state || $this->zip  || $this->country) : ?>
	<div class="adr">
	<?php if($this->street) : ?>
		<div class="street-address"><?php echo $this->street;?></div>
	<?php endif; ?>
		<div>
	<?php if($this->zip) : ?>
			<span class="postal-code"><?php echo $this->zip;?></span>
	<?php endif; ?>
	<?php if($this->city) : ?>
			<span class="locality"><?php echo $this->city;?></span>
	<?php endif; ?>
		</div>
	<?php if($this->state) : ?>
		<div class="region"><?php echo $this->state;?></div>
	<?php endif; ?>
	<?php if($this->country) : ?>
		<div class="country-name"><?php echo $this->country;?></div>
	<?php endif; ?>
	</div>
<?php endif; ?>
<?php if($this->telephone) : ?>
	<div class="tel">Tel: <?php echo $this->telephone;?></div>
<?php endif; ?>
</div>