<h2>End of year</h2>
<div><?php echo Aitsu_Util_Date :: secondsUntilEndOf('year'); ?> seconds</div>
<div><?php echo floor(Aitsu_Util_Date :: secondsUntilEndOf('year') / 24 / 60 / 60); ?> days</div>

<h2>End of month</h2>
<div><?php echo Aitsu_Util_Date :: secondsUntilEndOf('month'); ?> seconds</div>
<div><?php echo floor(Aitsu_Util_Date :: secondsUntilEndOf('month') / 24 / 60 / 60); ?> days</div>

<h2>End of day</h2>
<div><?php echo Aitsu_Util_Date :: secondsUntilEndOf('day'); ?> seconds</div>
<div><?php echo floor(Aitsu_Util_Date :: secondsUntilEndOf('day') / 60 / 60); ?> hours</div>

<h2>End of week</h2>
<div><?php echo Aitsu_Util_Date :: secondsUntilEndOf('week'); ?> seconds</div>
<div><?php echo floor(Aitsu_Util_Date :: secondsUntilEndOf('week') / 24 / 60 / 60); ?> days</div>
