<?php foreach ($this->files as $file) : $name = empty($file->name) ? $file->filename : $file->name; ?>
	<div style="width: 57px; height: 57px; float: left;">
		<img id="articleimage-image_<?php echo $file->mediaid ?>" src="<?php echo $this->url(array('controller' => 'image', 'action' => 'media', 'width' => 55, 'height' => 55, 'boxed' => 1, 'id' => $file->mediaid), 'default'); ?>" alt="<?php echo $name; ?>" title="<?php echo $name; ?>" style="width: 35px; height: 35px; top: 10px; left: 10px; position: relative;" />
	</div>
<?php endforeach;?>


<?php foreach ($this->files as $file) : ?>
	<input type="radio" class="articleimage-image_<?php echo $file->mediaid ?>" name="articleimage" value="<?php echo $file->filename; ?>"/>
<?php endforeach;?>