{
	region: 'south',
	id: 'center-south',
	unstyled: true,
	layout: 'fit',
	split: true,
	collapsible: true,
	collapseMode: 'mini',
	hideCollapseTool: true,
	minHeight: 150,
	height: 250,
	items: new Ext.TabPanel({
		id: 'center-south-tab',
		resizeTabs: false,
		minTabWidth: 115,
		tabWidth:135,
		enableTabScroll:true,
		defaults: {
			autoScroll:true
		},
		tabPosition: 'top',
		listeners: {
			tabchange: function(panel, tab) {
				if (panel.items.getCount() == 0) {
					var dim = registry.get('center-south-dim');
					if (typeof dim != 'undefined' && dim.westIsVisible) {
						Ext.getCmp('viewport-west').setVisible(true);
					}
					Ext.getCmp('viewport-inner-centerarea').setVisible(true);
					Ext.getCmp('center-south').setVisible(false);
					Ext.getCmp('viewport').doLayout();
				}
			},
			render: function(p) {
            	p.header.on('dblclick', function(e, el, o) {
            		var dim = registry.get('center-south-dim');
            		if (typeof dim == 'undefined') {
            			dim = {
            				isBig: false,
							height: 250,
							westIsCollapsed: Ext.getCmp('viewport').layout.west.isCollapsed,
							westIsVisible: Ext.getCmp('viewport').layout.west.isVisible()
            			}
            		}
            		if (dim.isBig) {
            			/* reduce */
            			dim.isBig = false;
            			Ext.getCmp('viewport-inner-centerarea').setVisible(true);
            			if (dim.westIsVisible) {
            				Ext.getCmp('viewport-west').setVisible(true);
            			}
            			Ext.getCmp('center-south').setHeight(dim.height);
            		} else {
            			/* maximize */
            			dim.isBig = true;
            			Ext.getCmp('viewport-inner-centerarea').setVisible(false);
            			dim.westIsVisible = Ext.getCmp('viewport').layout.west.isVisible();
            			Ext.getCmp('viewport-west').setVisible(false);
            			dim.height = Ext.getCmp('center-south').getHeight();
            			Ext.getCmp('center-south').setHeight(Ext.getCmp('viewport-centerarea').getHeight());
            		}
            		Ext.getCmp('viewport').doLayout();
            		registry.add('center-south-dim', dim);
            	}, this);
        	}
		}
	})
}