{
	region: 'south',
	id: 'center-south',
	unstyled: true,
	layout: 'fit',
	split: true,
	collapsible: true,
	collapseMode: 'mini',
	hideCollapseTool: true,
	minHeight: 300,
	height: 300,
	items: new Ext.TabPanel({
		id: 'center-south-tab',
		resizeTabs: false,
		minTabWidth: 115,
		tabWidth:135,
		enableTabScroll:true,
		defaults: {
			autoScroll:true
		},
		tabPosition: 'top',
		listeners: {
			tabchange: function(panel, tab) {
				if (panel.items.getCount() == 0) {
					Ext.getCmp('center-south').setVisible(false);
					Ext.getCmp('viewport').doLayout();
				}
			}
		}
	})
}