{
	region: 'south',
	split: true,
	height: 0,
	margins: '0 0 0 0',
	bbar: new Ext.ux.StatusBar({
		id: 'basic-statusbar',
		defaultText: '',
		text: '',
		iconCls: 'x-status-valid',
		items: [
			{
				xtype: 'tbtext',
				id: 'session-clock',
				text: ''
			},
			'-',
			'moraso <?php echo Moraso_Status::version(); ?> (powered by aitsu <?php echo Aitsu_Application_Status :: version(); ?>)',
			'-',
			'&copy; 2012 - <a href="http://www.webtischlerei.de" target="_blank">webtischlerei</a>'
		]
	})                
}