<div class="googleplus">
	<?php foreach ($this->data->items as $item) : ?>
	<div class="activity">
		<?php echo $this->partial('metainfo.phtml', array('item' => $item)); ?>
		<?php if ($item->object->objectType == 'note') : ?>
			<?php echo $this->partial('note.phtml', array('item' => $item->object)); ?>
		<?php endif; ?>
		<?php if (isset($item->object->attachments)) : ?>
			<?php foreach ($item->object->attachments as $att) : ?>
				<?php if ($att->objectType == 'photo') : ?>
					<?php echo $this->partial('photo.phtml', array('item' => $att)); ?>
				<?php elseif ($att->objectType == 'article') : ?>
					<?php echo $this->partial('article.phtml', array('item' => $att)); ?>
				<?php endif; ?>
			<?php endforeach; ?>
		<?php endif; ?>
	</div>
<?php endforeach; ?>
</div>
