<div class="tabs">
	<ul>
		<li>
			<a href="#tab-category"><?php echo $this->translate('Categories'); ?></a>
		</li>
	</ul>
	
	<div id="tab-category">
		<div class="tab-content">
		
			<div class="toolbar ui-corner-bottom">
				<button id="cat-new" title="<?php echo $this->translate('New'); ?>" class="type-new confirm"><?php echo $this->translate('New'); ?></button>
				<button id="cat-edit" title="<?php echo $this->translate('Edit'); ?>" class="type-edit"><?php echo $this->translate('Edit'); ?></button>
				<button id="cat-set-online" title="<?php echo $this->translate('Visiblity'); ?>" class="type-online"><?php echo $this->translate('Visiblity'); ?></button>
				<button id="cat-set-lock" title="<?php echo $this->translate('Lock'); ?>" class="type-lock"><?php echo $this->translate('Lock'); ?></button>
				<button id="cat-delete" title="<?php echo $this->translate('Delete'); ?>" class="type-delete deny"><?php echo $this->translate('Delete'); ?></button>
				<button id="cat-sync" title="<?php echo $this->translate('Sync'); ?>" class="type-sync"><?php echo $this->translate('Sync'); ?></button>
			</div>		
				
			<div class="sized-content">	
				<div id="cat-tree"></div>
			</div>
		</div>
	</div>
		
</div>

<?php echo $this->partial('dialog/setcategoryonline.phtml'); ?>
<?php echo $this->partial('dialog/setcategorylocked.phtml'); ?>

<?php $form = new Aitsu_Form(new Zend_Config_Ini(APPLICATION_PATH . '/adm/forms/category/category.ini', 'edit')); ?>
<?php
$configSetOptions = array('0' => '');
foreach (Aitsu_Persistence_ConfigSet :: getAsArray() as $key => $value) {
	$configSetOptions[$key] = $value;
}
?>
<?php $form->getElement('configset')->setMultiOptions($configSetOptions); ?>
<?php echo $this->partial('dialog/editcategory.phtml', array('form' => $form)); ?>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {
	
	$('#sync-lang-form input[type="radio"]').live('change', function() {
		$('#cat-tree').jstree('refresh',-1);
	});
	
	$('#cat-tree').jstree({
		"themes" : {
            "theme" : "aitsu",
            "dots" : false,
            "icons" : true
        },
        "json_data" : {
            "ajax" : {
                "url" : "/adm/category/treecontent",
                "data" : function (n) {
                    return { id : n.attr ? n.attr("id") : 0, sync : $("#sync-lang-form input[name='sync-lang']:checked").val() };
                },
                "progressive_render" : true
            }
        },
        "cookies" : {
        	"save_opened" : "category-tree-opened",
        	"save_selected" : "category-tree-selected"
        },
        "plugins" : [ "themes", "json_data", "dnd", "ui", "cookies" ]
    });
    
    $('#cat-tree').bind("move_node.jstree", function (e, data) {
		$.post("/adm/category/movecat", { id: data.rslt.o.attr('id'), type: data.rslt.p, relative: data.rslt.r.attr('id'), parent: data.rslt.np.attr('id') }, function(data) {
			// nothing
		}, "json");  	
	}); 
    
	$(document).bind('bindclicks', function() {
		$('#cat-new').live('click', function() {
			if ($(this).button( "option", "disabled" )) {
				return false;
			}
			var node = $.jstree._reference('#cat-tree')._get_node(null, false);
			var id = 0;
			if (node) {
				id = node.attr('id');
			}
			$.post("/adm/category/addnew", { id: id },
   				function(data){
   					if (data.status == 'success') {
     					$('#status').html('<?php echo $this->translate('Category added'); ?> (ID ' + data.idcat + ')');
     					if (node) {
     						$('#cat-tree').jstree('refresh', node);
     					} else {
     						$('#cat-tree').jstree('refresh',-1);
     					}
   					}
   			});
			return false;
		});
		$('#cat-delete').live('click', function() {
			if ($(this).button( "option", "disabled" )) {
				return false;
			}
			var node = $.jstree._reference('#cat-tree')._get_node(null, false);
			if (node) {
				$("#confirm-delete").dialog({
					resizable: false,
					modal: true,
					buttons: {
						'<?php echo $this->translate('No'); ?>': function() {
							$(this).dialog('close');
						},
						'<?php echo $this->translate('Yes'); ?>': function() {
							$(document).trigger('delete-category', [node.attr('id')]);
							$(this).dialog('close');
						}
					}
				});				
			} else {
				$("#no-selection-made").dialog({
					resizable: false,
					modal: true,
					buttons: {
						'<?php echo $this->translate('OK'); ?>': function() {
							$(this).dialog('close');
						}
					}
				});				
				return false;
			}
		});
		$('#cat-set-online').live('click', function() {
			if ($(this).button( "option", "disabled" )) {
				return false;
			}
			var node = $.jstree._reference('#cat-tree')._get_node(null, false);
			var id = 0;
			if (node) {
				id = node.attr('id');
			} else {
				return false;
			}
			var status = node.hasClass('online') ? '0' : '1'; 
			$("#confirm-set-category-online").dialog({
				resizable: false,
				modal: true,
				buttons: {
					'<?php echo $this->translate('Cancel'); ?>': function() {
						$(this).dialog('close');
						return false;
					},
					'<?php echo $this->translate('No'); ?>': function() {
						$(document).trigger('cat-set-online', [id, status, 0, node]);
						$(this).dialog('close');
						return false;
					},
					'<?php echo $this->translate('Yes'); ?>': function() {
						$(document).trigger('cat-set-online', [id, status, 1, node]);
						$(this).dialog('close');
						return false;
					}
				}
			});
		});
		$('#cat-set-lock').live('click', function() {
			if ($(this).button( "option", "disabled" )) {
				return false;
			}
			var node = $.jstree._reference('#cat-tree')._get_node(null, false);
			var id = 0;
			if (node) {
				id = node.attr('id');
			} else {
				return false;
			}
			var status = node.hasClass('public') ? '0' : '1'; 
			$("#confirm-set-category-locked").dialog({
				resizable: false,
				modal: true,
				buttons: {
					'<?php echo $this->translate('Cancel'); ?>': function() {
						$(this).dialog('close');
						return false;
					},
					'<?php echo $this->translate('No'); ?>': function() {
						$(document).trigger('cat-set-locked', [id, status, 0, node]);
						$(this).dialog('close');
						return false;
					},
					'<?php echo $this->translate('Yes'); ?>': function() {
						$(document).trigger('cat-set-locked', [id, status, 1, node]);
						$(this).dialog('close');
						return false;
					}
				}
			});
		});
		$('#cat-edit').live('click', function() {
			if ($(this).button( "option", "disabled" )) {
				return false;
			}
			var node = $.jstree._reference('#cat-tree')._get_node(null, false);
			var id = 0;
			if (node) {
				id = node.attr('id');
			} else {
				return false;
			}
			$.post("/adm/category/getcatdata", { id: id }, function(data) {
				$("#cat-edit-name").val(data.data.name);
				$("#cat-edit-urlname").val(data.data.urlname);
				$("#cat-edit-configset").val(data.data.configsetid);
				$("#cat-edit-configuration").val(data.data.config);
				$("#cat-edit-idcat").val(id);
			}, "json");
			$("#edit-category").dialog({
				modal: true,
				minWidth: 600,
				buttons: {
					'<?php echo $this->translate('Cancel'); ?>': function() {
						$(this).dialog('close');
						return false;
					},
					'<?php echo $this->translate('Save'); ?>': function() {
						$(this).dialog('close');
						$.post("/adm/category/save", $("#category-edit-form").serialize(), function(data) {
							$('#status').html('<?php echo $this->translate('Category saved'); ?> (ID ' + data.idcat + ')');
							$.jstree._reference('#cat-tree').refresh(node.closest('ul'));
						}, "json");
						return false;
					}
				}
			});
			return false;
		});
		$('#cat-sync').live('click', function() {
			if ($(this).button( "option", "disabled" )) {
				return false;
			}
			var node = $.jstree._reference('#cat-tree')._get_node(null, false);
			var id = 0;
			if (node) {
				id = node.attr('id');
			} else {
				return false;
			}			
			$.post("/adm/category/sync", {id: id, syncLang: $("#sync-lang-form input[name='sync-lang']:checked").val() }, function(data) {
				$('#status').html('<?php echo $this->translate('Category synchronized'); ?> (ID ' + data.idcat + ')');
				$.jstree._reference('#cat-tree').refresh(node.closest('ul'));
			}, "json");	
			return false;				
		});
		$('#cat-tree li').live('click', function() {
			if ($(this).hasClass('unsynced')) {
				$('#cat-new').button('disable');
				$('#cat-edit').button('disable');
				$('#cat-set-online').button('disable');
				$('#cat-set-online').button('disable');
				$('#cat-set-lock').button('disable');
				$('#cat-delete').button('disable');
				if ($(this).parents('li').first() != null && $(this).parents('li').first().hasClass('unsynced')) {
					$('#cat-sync').button('disable');
				} else {
					$('#cat-sync').button('enable');
				}
			} else {
				$('#cat-new').button('enable');
				$('#cat-edit').button('enable');
				$('#cat-set-online').button('enable');
				$('#cat-set-online').button('enable');
				$('#cat-set-lock').button('enable');
				$('#cat-delete').button('enable');
				$('#cat-sync').button('disable');
			}
			if ($(this).hasClass('online')) {
				$('#cat-set-online .ui-button-text').html('<?php echo $this->translate('Offline'); ?>');
				$('#cat-set-online').addClass('deny').removeClass('confirm').attr('title', '<?php echo $this->translate('Offline'); ?>');
			} else {
				$('#cat-set-online .ui-button-text').html('<?php echo $this->translate('Online'); ?>');
				$('#cat-set-online').addClass('confirm').removeClass('deny').attr('title', '<?php echo $this->translate('Online'); ?>');
			}
			if ($(this).hasClass('public')) {
				$('#cat-set-lock .ui-button-text').html('<?php echo $this->translate('Lock'); ?>');
				$('#cat-set-lock').attr('title', '<?php echo $this->translate('Lock'); ?>');
				$('#cat-set-lock > span').addClass('ui-icon-locked').removeClass('ui-icon-unlocked');
			} else {
				$('#cat-set-lock .ui-button-text').html('<?php echo $this->translate('Release'); ?>');
				$('#cat-set-lock').attr('title', '<?php echo $this->translate('Release'); ?>');
				$('#cat-set-lock > span').addClass('ui-icon-unlocked').removeClass('ui-icon-locked');
			}
			return false;
		});
	});
	$(document).trigger('bindclicks');
	
	$(document).bind('cat-set-online', function(event, id, status, propagate, node) {
		$.post("/adm/category/setonline", { id: id, status: status, propagate: propagate },
			function(data){
   				if (data.status == 'success') {
     				$('#status').html('<?php echo $this->translate('Category set online/offline'); ?> (ID ' + data.idcat + ', Status: ' + status + ')');
   					$.jstree._reference('#cat-tree').refresh(node.closest('ul'));
   				}
   		});		
	});

	$(document).bind('cat-set-locked', function(event, id, status, propagate, node) {
		$.post("/adm/category/setlocked", { id: id, status: status, propagate: propagate },
			function(data){
   				if (data.status == 'success') {
     				$('#status').html('<?php echo $this->translate('Category locked / released'); ?> (ID ' + data.idcat + ', Status: ' + status + ')');
   					$.jstree._reference('#cat-tree').refresh(node.closest('ul'));
   				}
   		});		
	});

	$(document).bind('delete-category', function(event, id) {
		$.post("/adm/category/delete", { id: id },
			function(data){
   				if (data.status == 'success') {
     				$('#status').html('<?php echo $this->translate('Category removed'); ?> (ID ' + data.idcat + ')');
   					$.jstree._reference('#cat-tree').delete_node($('#' + id));
   				}
   			});
	});
	
});
<?php $this->inlineScript()->captureEnd(); ?>