<ul data-role="listview" data-inset="true" >
	<li><a href="/de/weingut/" data-transition="slidedown"> <img src="sushis.jpg"/> <h3>Weingut</h3></a></li>
	<li><a href="choose_town.html" data-transition="slidedown"> <img src="pizza.jpg"/> <h3> A Pizza </h3></a></li>
	<li><a href="choose_town.html" data-transition="slidedown"> <img src="kebap.jpg"/> <h3> A Kebap</h3></a></li>
	<li><a href="choose_town.html" data-transition="slidedown"> <img src="burger.jpg"/> <h3> A Burger</h3></a></li>
	<li><a href="choose_town.html" data-transition="slidedown"> <img src="nems.jpg"/> <h3> Some Nems </h3></a></li>
	<li><a href="choose_town.html" data-transition="slidedown"> <img src="tradi.jpg"/> <h3> Something more traditional</h3></a></li>	
</ul>