<div class="subcolumns">
	<div class="c33l">
		<div class="subcl">
			<script type="application/x-aitsu" src="HTML:Sub1"></script>
		</div>
	</div>
	<div class="c33l">
		<div class="subc">
			<script type="application/x-aitsu" src="HTML:Sub2"></script>
		</div>
	</div>
	<div class="c33r">
		<div class="subcr">
			<script type="application/x-aitsu" src="HTML:Sub3"></script>
		</div>
	</div>
</div>