$(function() {
	
	$(document).unbind('edit-page-content');
	$(document).bind('edit-page-content', function(event, obj) {
		var oBody = obj.contents().find("body");
		$(document).data('edit-frame-content', oBody);
		
		/* Stop links working. */
		$('a', oBody).click(function(e) {
			e.preventDefault();
		});
		
		/* Unbind potential events in elements inside .aitsu_editable elements. */
		$('.aitsu_editable', oBody).find().unbind();
		
		/* Unbind previosly made bindings. */
		$('.aitsu_editable', oBody).unbind();
		$('.show-on-demand', oBody).unbind();
		$(document).unbind('edit-save');
		$(document).unbind('toogle-sub-templates');
		
		/* Hover and edit binding normal .aitsu_editables (except on-domand). */
		$('.aitsu_editable:not(.on-demand)', oBody).bind('mouseenter', function (e){
			e.stopPropagation();
			$('.aitsu_editable', oBody).css({
				'background': 'none',
				'border': 'none',
				'margin': '0',
				'cursor': 'auto'
			});
			$(this).css({
				'background-color': '#ec7537',
				'border': '5px solid #ec7537',
				'margin': '-5px',
				'cursor': 'pointer'
			});
			$('.aitsu_editable', oBody).unbind('click');
			$(this).bind('click', function(e) {
				$(this).triggerHandler('doEdit');
			});
		});
		$('.aitsu_editable:not(.on-demand)', oBody).bind('mouseleave', function (e){
			$(this).css({
				'background': 'none',
				'border': 'none',
				'margin': '0'
			});
			$(this).unbind('click');
			$(this).parents('.aitsu_editable').first().trigger('mouseenter');
		});
		
		$('.aitsu_editable.on-demand .show-on-demand', oBody).bind('mouseenter', function() {
			$('.aitsu_editable', oBody).css({
				'background': 'none',
				'cursor': 'auto'
			});
			$('.aitsu_editable', oBody).unbind('click');
			$(this).bind('click', function(e) {
				$(this).parents('.aitsu_editable').triggerHandler('doEdit'); 
			});
		});
		$('.aitsu_editable.on-demand .show-on-demand', oBody).bind('mouseleave', function() {
			$(this).unbind('click');
			$(this).parents('.aitsu_editable').first().next().trigger('mouseenter');
		});
		
		$(document).bind('toogle-sub-templates', function() {
			if ($(document).data('show-sub-templates') == '1') {
				$('.show-on-demand', oBody).css({
					'display': 'none',
					'border': 'none',
					'padding': '0'
				});
				$(document).data('show-sub-templates', '0');
			} else {
				$('.show-on-demand', oBody).css({
					'display': 'block',
					'border': '1px dotted black',
					'padding': '5px'
				});
				$(document).data('show-sub-templates', '1');
			}
		});
		
		/* Edit handler. */
		$('.aitsu_editable', oBody).bind('doEdit', function(e) {
			/(.*?)\-(.*?)\-(\d*)$/.exec($(this).attr('id'));
			doEditHandler({
				type: RegExp.$1,
				container: RegExp.$2,
				idartlang: RegExp.$3,
				params: $(this).find('code.aitsu_params').length > 0 ? $(this).find('code.aitsu_params').first().html() : ''
			});
		});
		
		/* Content replace handler. */
		$(document).bind('doReplace', function(event, type, container, idartlang, data) {
			$('#' + type + '-' + container + '-' + idartlang, oBody).html($('#.aitsu_hover:first', data));
			$(document).trigger('edit-page-content', [$('#edit-iframe-' + idartlang)]);
			$(document).trigger('toogle-sub-templates');
			$(document).trigger('toogle-sub-templates');
		});
	});
	
});