win = new Ext.Window({
	layout:'fit',
	width:700,
	height:500,
	modal: true,
	closable: false,
	plain: true,
	shadow: true,
	floating: true,
	items: new Ext.FormPanel({
		id: 'edit-content-form',
		border: false,
		layout: 'fit',
		items: {
			xtype:'tabpanel',
			activeTab: 0,
			items:[
				<?php for ($i = 0; $i < count($this->data->editInfo); $i++) : ?>
					<?php /* edit fields */ ?>
					<?php echo $this->partial('edit/content.phtml', array('field' => $this->data->editInfo[$i])); ?>
					<?php if ($i < count($this->data->editInfo) - 1) : ?>
						,
					<?php endif; ?>
				<?php endfor; ?>
				<?php if (!empty($this->data->configInfo)) : ?>
					<?php /* configuration */ ?>
					<?php if (!empty($this->data->editInfo)) : ?>
						,
					<?php endif; ?>
					{
						title: '<?php echo Aitsu_Translate :: translate('Configuration'); ?>', 
						layout: 'form',
						autoScroll: true,
						padding: '5px',
						items: [					
							<?php $counter = 1; foreach($this->data->configInfo as $fieldset => $config) : $counter++; ?>
								<?php echo $this->partial('edit/fieldset.phtml', array('fieldset' => $fieldset, 'config' => $config)); ?>
								<?php if ($counter < count($this->data->configInfo)) : ?>
								,
								<?php endif; ?>
							<?php endforeach; ?>
						]
					}
				<?php endif; ?>
			]
		}
	}),
	buttons: [{
		text:'<?php echo Aitsu_Translate :: translate('Cancel'); ?>',
		iconCls: 'cancel',
		handler: function(){
			win.destroy();
		}
	},{
		text: '<?php echo Aitsu_Translate :: translate('Save'); ?>',
		iconCls: 'save',
		handler: function(){
			win.destroy();
		}
	}]
});
win.show();
