(function( $ ){
	
	var origin;	
	var scrollTimerId;
	var scrolling = false;
	var bboffset = 0;
	var suppressHover = false;
	var markitup;
	
	var main = function() {
		origin = this;
		suppressHover = false;
		
		this.find('ul.flexcontent').sortable('destroy');
		this.find('*').off('.flexeditor');
				
		this.find('div.modules').css('width', Math.floor(($(this).parent().width() - 10) / 170) * 170);
				
		var id = $(this).closest('.flexeditor').attr('id');
  		/([^-]*)-([^-]*)-(\d*)/.exec(id);
		var index = RegExp.$2;
		var idart = RegExp.$3;
				
		this.find('div.flexcontent').mouseenter(function() {
			$(this).hide();
			$(this).closest('.flexeditor').find('ul.flexcontent').show();
		});
				
		this.find('ul.flexcontent').mouseleave(function() {
			if (suppressHover) {
				return;
			}
			$(this).hide();
			$(this).closest('.flexeditor').find('div.flexcontent').show();
		});
				
		this.find('ul.flexcontent').mouseover(function(e){
			e.stopPropagation();
		});
				
		/*
		 * As mouse events are not propagated above the current document
		 * boundaries this must be done explicitly.
		 */
		this.find('ul.flexcontent').on({
			mousemove: function(event) {
				$(parent.document).trigger(event);
			},
			mouseup: function(event) {
				$(parent.document).trigger(event);
			}
		});
				
		this.find('button.add span').css({
			'background-image': 'url(<?php echo Aitsu_Config :: get('sys.mainDir'); ?>adm/images/flex-ui-icons.png)',
			'background-position': '-16px -128px'
		})
		.attr('title', 'Add a block below the current position.');
		
		this.find('button.configure span').css({
			'background-image': 'url(<?php echo Aitsu_Config :: get('sys.mainDir'); ?>adm/images/flex-ui-icons.png)',
			'background-position': '-192px -112px'
		})
		.attr('title', 'Configure shortcode.');
		
		this.find('button.edit span').css({
			'background-image': 'url(<?php echo Aitsu_Config :: get('sys.mainDir'); ?>adm/images/flex-ui-icons.png)',
			'background-position': '-64px -112px'
		})
		.attr('title', 'Edit current block.');
		
		this.find('button.trash span').css({
			'background-image': 'url(<?php echo Aitsu_Config :: get('sys.mainDir'); ?>adm/images/flex-ui-icons.png)',
			'background-position': '-176px -96px'
		})
		.attr('title', 'Remove current block.')
		
		this.find('button.cancel span').css({
			'background-image': 'url(<?php echo Aitsu_Config :: get('sys.mainDir'); ?>adm/images/flex-ui-icons.png)',
			'background-position': '-32px -192px'
		})
		.attr('title', 'Cancel.')
				
		this.find('.buttonbar button.add').on('click.flexeditor', function() {
			var pos = $(this).closest('li').find('a.position').attr('href');
			var editor = $(this).closest('.flexeditor');
			doSuppressHover.apply(this);
			var modules = $(this).closest('.flexeditor').find('li.modules').clone();
			modules.find('a.position').attr('href', pos);
			modules.show();
			modules.insertAfter($(this).closest('li'));
			modules.find('div.modules button:not(.cancel)').one('click', function() {
				$.post($('#edit-iframe-' + idart).attr('src'), {
						renderOnly: "Content.Textile.Flex:" + index,
						edit: 1,
						pos: pos,
						add: $(this).val()
					},function(data) {
						var flexcontent = $('#' + id, data).html();
						editor.html(flexcontent);
						$(document).trigger('edit-page-content', [$('#edit-iframe-' + idart)]);
					});				
			});
			modules.find('div.modules button.cancel').one('click.flexeditor', function() {
				$(this).closest('li').remove();
				doSuppressHover.apply(this, false);
			});
		});
				
		this.find('.buttonbar button.configure').each(function() {
			if ($(this).closest('li').find('div.content .aitsu_editable').size() == 0) {
				$(this).remove();
			}
		});
				
		this.find('.buttonbar button.configure span').on('click.flexeditor', function() {
			$(this).closest('li').find('div.content .aitsu_editable').trigger('mouseenter');
			$(this).closest('li').find('div.content .aitsu_editable').trigger('click');
		});
				
		this.find('.buttonbar button.edit').on('click.flexeditor', function() {
			var pos = $(this).closest('li').find('a.position').attr('href');
			var element = $(this).closest('li');
			var editor = $(this).closest('.flexeditor');
			element.find('div.content').css('display', 'none');
			element.find('div.editor').css('display', 'block');
			doSuppressHover.apply(this);
			element.find('div.buttonbar').css({
				'display': 'none'
			});
			element.css({
				'background': 'none'
			});
			var setting = myFlexSettings;
			setting.markupSet[0] = {name:'Save', call: function() {
				$.post($('#edit-iframe-' + idart).attr('src'), {
						renderOnly: "Content.Textile.Flex:" + index,
						edit: 1,
						pos: pos,
						content: markitup.val()
					},function(data) {
						var flexcontent = $('#' + id, data).html();
						editor.html(flexcontent);
						$(document).trigger('edit-page-content', [$('#edit-iframe-' + idart)]);
						Ext.aitsu.setUnpublished();
					});				
			}, className:'save confirm'};
			setting.markupSet[1] = {name:'Cancel', call: function() {
				editor.enableFlexEditor('suppressHover', false);
				element.find('div.editor').css('display', 'none');
				element.find('div.content').css('display', 'block');
				element.trigger('mouseenter');
			}, className:'cancel deny'};
			markitup = element.find('div.editor > textarea').markItUp(setting);
			var editorContent = element.nextAll().find('div.editor textarea').map(function() {
				return $(this).val();
			}).get().join('\n\n');
			markitup.val(element.find('div.editor textarea').val() + '\n\n' + editorContent);
			doUiButtons.apply(this);
		});
				
		this.find('.buttonbar button.trash').on('click.flexeditor', function() {
			var pos = $(this).closest('li').find('a.position').attr('href');
			var editor = $(this).closest('.flexeditor');
			Ext.aitsu.confirm({
				title: '<?php echo $this->translate('Delete entry'); ?>',
				msg: '<?php echo $this->translate('Are you sure to delete the selected entry?'); ?>',
				ok: function() {
					$.post($('#edit-iframe-' + idart).attr('src'), {
							renderOnly: "Content.Textile.Flex:" + index,
							edit: 1,
							del: pos
						},function(data) {
							var flexcontent = $('#' + id, data).html();
							editor.html(flexcontent);
							$(document).trigger('edit-page-content', [$('#edit-iframe-' + idart)]);
							Ext.aitsu.setUnpublished();
						});
				},
				cancel: function() {
				}
			});
			
		});
				
		this.find('ul.flexcontent > li').on('mouseenter.flexeditor',
			function() {
				if (suppressHover) {
					return;
				}
				$(this).find('div.buttonbar').css({
					'display': 'block'
				});
				$(this).css({
					'background-color': '#DDD',
					'opacity': '0.8'
				});
			}
		).on('mouseleave.flexeditor', 
			function() {
				$(this).find('div.buttonbar').css('display', 'none');
				$(this).css({
					'background': 'none',
					'opacity': '1'
				});
			});
				
		this.find('ul.flexcontent').sortable({
			axis: 'y',
			handle: 'div.buttonbar',
			forceHelperSize: true,
			forcePlaceholderSize: true,
			placeholder: "placeholder",
			opacity: 0.7,
			helper: 'clone',
			update: function(event, ui) {
				var editor = $(this).closest('.flexeditor');
				var newpos = $(this).find('li > a.position').map(function(index) {
					return $(this).attr('href');
				}).get();
				$.post($('#edit-iframe-' + idart).attr('src'), {
					renderOnly: "Content.Textile.Flex:" + index,
					edit: 1,
					newpos: newpos
				},function(data) {
					var flexcontent = $('#' + id, data).html();
					editor.html(flexcontent);
					$(document).trigger('edit-page-content', [$('#edit-iframe-' + idart)]);
					Ext.aitsu.setUnpublished();
				});
			},
			start: function(event, ui) {
				moving = true;
				doSuppressHover.apply(this);
				$(this).closest('.flexeditor').find('div.buttonbar').hide();
  				/([^-]*)-([^-]*)-(\d*)/.exec($(this).closest('.flexeditor').attr('id'));
				var cframe =  $('#edit-iframe-' + RegExp.$3);
				var sbar = cframe.contents().find('body');
				var distance = 0;
				var maxOffset = $(this).closest('div').offset().top + $(this).height() - cframe.height() + 50;
				var minOffset = $(this).closest('div').offset().top;
				$(this).on('mousemove.flexeditor', function(e) {				
					if (!scrolling && (sbar.scrollTop() + cframe.height() - e.pageY < 100 || e.pageY - sbar.scrollTop() < 100)) {
						scrolling = true;
						scrollTimerId = window.setInterval(function() {
							if (distance > 0) {
								sbar.scrollTop(Math.min(sbar.scrollTop() + distance, maxOffset));
							} else {
								sbar.scrollTop(Math.max(sbar.scrollTop() + distance, minOffset));
							}
							if (sbar.scrollTop() >= maxOffset || sbar.scrollTop() <= minOffset) {
								distance = 0;
								scrolling = false;
								window.clearInterval(scrollTimerId);
								return;
							}
						}, 10);
					}
					if (sbar.scrollTop() + cframe.height() - e.pageY < 100) {
						distance = 200 / (sbar.scrollTop() + cframe.height() - e.pageY);
					} else if (e.pageY - sbar.scrollTop() < 100) {
						distance = -200 / (e.pageY - sbar.scrollTop());
					} else {
						distance = 0;
						scrolling = false;
						window.clearInterval(scrollTimerId);
					}
				});
			},
			stop: function(event, ui) {
				moving = false;
				suppressHover = false;
				$(this).closest('.flexeditor').find('div.buttonbar').hide();
				window.clearInterval(scrollTimerId);
				$(this).unbind('mousemove');
			},
			sort: function(event, ui) { 
				/([^-]*)-([^-]*)-(\d*)/.exec($(this).closest('.flexeditor').attr('id'));
				var cframe =  $('#edit-iframe-' + RegExp.$3);
				var sbar = cframe.contents().find('body');
        		ui.helper.css({'top' : ui.position.top + sbar.scrollTop() + 'px'});
    		}
		});		
	}
	
	var doUiButtons = function() {
		origin.find( ".markItUpButton.heading1 a").button({
			icons: {
				primary: "ui-icon-heading1"
			},
			text: false
		});
		origin.find( ".markItUpButton.heading2 a").button({
			icons: {
				primary: "ui-icon-heading2"
			},
			text: false
		});
		origin.find( ".markItUpButton.heading3 a").button({
			icons: {
				primary: "ui-icon-heading3"
			},
			text: false
		});
		origin.find( ".markItUpButton.heading4 a").button({
			icons: {
				primary: "ui-icon-heading4"
			},
			text: false
		});
		origin.find( ".markItUpButton.heading5 a").button({
			icons: {
				primary: "ui-icon-heading5"
			},
			text: false
		});
		origin.find( ".markItUpButton.heading6 a").button({
			icons: {
				primary: "ui-icon-heading6"
			},
			text: false
		});
		origin.find( ".markItUpButton.paragraph a").button({
			icons: {
				primary: "ui-icon-paragraph"
			},
			text: false
		});
		origin.find( ".markItUpButton.strong a").button({
			icons: {
				primary: "ui-icon-strong"
			},
			text: false
		});
		origin.find( ".markItUpButton.emphasis a").button({
			icons: {
				primary: "ui-icon-emphasis"
			},
			text: false
		});
		origin.find( ".markItUpButton.inserted a").button({
			icons: {
				primary: "ui-icon-inserted"
			},
			text: false
		});
		origin.find( ".markItUpButton.deleted a").button({
			icons: {
				primary: "ui-icon-deleted"
			},
			text: false
		});
		origin.find( ".markItUpButton.bulletlist a").button({
			icons: {
				primary: "ui-icon-numericlist"
			},
			text: false
		});
		origin.find( ".markItUpButton.numericlist a").button({
			icons: {
				primary: "ui-icon-bulletlist"
			},
			text: false
		});
		origin.find( ".markItUpButton.image a").button({
			icons: {
				primary: "ui-icon-image"
			},
			text: false
		});
		origin.find( ".markItUpButton.anchor a").button({
			icons: {
				primary: "ui-icon-link"
			},
			text: false
		});
		origin.find( ".markItUpButton.quote a").button({
			icons: {
				primary: "ui-icon-comment"
			},
			text: false
		});
		origin.find( ".markItUpButton.code a").button({
			icons: {
				primary: "ui-icon-script"
			},
			text: false
		});
		origin.find( ".markItUpButton.cancel a").button({
			icons: {
				primary: "ui-icon-circle-close"
			},
			text: false
		});
		origin.find( ".markItUpButton.save a").button({
			icons: {
				primary: "ui-icon-circle-check"
			},
			text: false
		});
	}
	
	var doDestroy = function() {
		this.find('ul.flexcontent').sortable('destroy');
		this.find('*').off('.flexeditor');
	}
				
	var doSuppressHover = function() {
		if (arguments.length == 1) {
			suppressHover = false;
			return;
		}
			
		origin.find('ul.flexcontent > li').trigger('mouseleave');
			
		suppressHover = true;
	}
	
	var methods = {
			init : function( options ) { 
				main.apply(this, arguments);
	    	}, 
	    	destroy : function() {
	    		doDestroy.apply(this);
	    	},
	    	suppressHover : function() { 
	    		doSuppressHover.apply(this, arguments);
	    	}
		};
	
	$.fn.enableFlexEditor = function(method) {
		
		if ( methods[method] ) {
			return methods[ method ].apply( this, Array.prototype.slice.call( arguments, 1 ));
		} else if ( typeof method === 'object' || ! method ) {
			return methods.init.apply( this, arguments );
		} else {
			$.error( 'Method ' +  method + ' does not exist on jQuery.enableFlexEditor' );
		}    
	};
})( jQuery );
