(function( $ ){
	$.fn.enableFlexEditor = function() {

		var scrollTimerId;
		var scrolling = false;

		this.find('.flexcontent').mouseover(function(e){
			e.stopPropagation();
		});
		
		/*
		 * As mouse events are not propagated above the current document
		 * boundaries this must be done explicitly.
		 */
		this.find('ul.flexcontent').on({
			mousemove: function(event) {
				$(parent.document).trigger(event);
			},
			mouseup: function(event) {
				$(parent.document).trigger(event);
			}
		});
		
		this.find('ul.flexcontent').sortable({
			update: function(event, ui) {
				var editor = $(this).closest('.flexeditor');
				var modules = $(this).find('li > a.module').map(function(index) {
					return $(this).attr('href');
				}).get();
				var id = $(this).closest('.flexeditor').attr('id');
				var regex = /([^-]*)-([^-]*)-(\d*)/;
  				regex.exec(id);
				var index = RegExp.$2;
				var idart = RegExp.$3;
				$.post($('#edit-iframe-' + idart).attr('src'), {
					renderOnly: "Flex:" + index,
					edit: 1,
					modules: modules
				},function(data) {
					var flexcontent = $('#' + id, data).html();
					editor.html(flexcontent);
					$(document).trigger('edit-page-content', [$('#edit-iframe-' + idart)]);
				});
			}
		});
	};
})( jQuery );
