<?php echo $this->partial('edit-hover.phtml'); ?>

var pageEditTabs = new Ext.TabPanel(
	{
		id: 'page-edit-tabs',
		title: '<?php echo Aitsu_Translate :: translate('Edit'); ?>',
		resizeTabs: false,
		minTabWidth: 115,
		tabWidth:135,
		enableTabScroll:true,
		defaults: {
			autoScroll:true
		},
		tabPosition: 'bottom'
	}
);

pageEditTabs.add({
	id: 'article-plugin-edit',
	title: '<?php echo Aitsu_Translate :: translate('Normal'); ?>',
	bodyCfg: {
		tag: 'iframe',
		id: 'edit-iframe-<?php echo $this->idartlang; ?>',
        src: '/adm/edit/<?php echo $this->idartlang; ?>',
        style: {
			border: '0px none'
        }
	},
	listeners: {
		render: function() {
			Ext.get('edit-iframe-<?php echo $this->idartlang; ?>').on('load', function(e, t, o) {
				$(document).trigger('edit-page-content', [$('#edit-iframe-<?php echo $this->idartlang; ?>')]);
			});
		}
	},
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Refresh'); ?>',
	            iconCls: 'tb-refresh',
	            handler: function(b, e) {
	            	Ext.get('edit-iframe-<?php echo $this->idartlang; ?>').set({
	            		src: '/adm/edit/<?php echo $this->idartlang; ?>'
	            	});
	            }
	        },
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Show template bars'); ?>',
	            iconCls: 'tb-templates',
	            handler: function(b, e) {
	            	$(document).trigger('toogle-sub-templates');
	            }
	        }
	    ]
	}
});

pageEditTabs.add({
	id: 'article-plugin-edit-boxmodel',
	title: '<?php echo Aitsu_Translate :: translate('Box model'); ?>',
	html: '<p>this feature is not implemented yet.</p>'
});

pageEditTabs.add({
	id: 'article-plugin-edit-preview',
	title: '<?php echo Aitsu_Translate :: translate('Preview'); ?>',
	bodyCfg: {
		tag: 'iframe',
		id: 'edit-iframe-preview-<?php echo $this->idartlang; ?>',
        src: '/adm/preview/<?php echo $this->idartlang; ?>',
        style: {
			border: '0px none'
        }
	},
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Refresh'); ?>',
	            iconCls: 'tb-refresh',
	            handler: function(b, e) {
					Ext.get('edit-iframe-preview-<?php echo $this->idartlang; ?>').set({
	            		src: '/adm/preview/<?php echo $this->idartlang; ?>'
	            	});
	            }
	        }
	    ]
	}
});

pageEditTabs.activate(0);

Ext.getCmp('page-edit-tab').add(pageEditTabs);

/*
Replaces the previously edited area.
$(document).trigger('doReplace', [p.type, p.container, p.idartlang, '<div><div class="aitsu_hover"><div id="PagetitleAsHeadline--440" class="aitsu_editable"><div class="aitsu_hover"><code class="aitsu_params" style="display:none;"> tag = h1 </code><h1>test</h1></div></div></div></div>']);
*/

var doEditHandler = function(p) {
	Ext.aitsu.load(['<?php echo $this->url(array('plugin' => 'edit', 'paction' => 'editcontent'), 'aplugin'); ?>?type=' + p.type + '&container=' + p.container + '&idartlang=' + p.idartlang + '&params=' + encodeURI(p.params)]);
}
