<!-- Standard -->
<?php foreach ($this->selectedImages as $image) : ?>
    <img src="image/<?php echo $this->imageWidth; ?>/<?php echo $this->imageHeight; ?>/<?php echo $this->imageRender; ?>/<?php echo $image->idart; ?>/<?php echo $image->filename; ?>" alt="<?php echo $image->subline; ?>" style="<?php if (!empty($this->imageFloat)) { echo 'float: ' . $this->imageFloat . ';'; } ?> <?php echo $this->imageStyle; ?>" />
<?php endforeach; ?>