<div id="col3">
	<div id="col3_content" class="clearfix">
		<script type="application/x-aitsu" src="Template:Sidebar">
       		defaultTemplate = html

       		template.html.file = templates/body/main/sidebar/html.phtml
       		template.html.name = HTML

       		template.htmli.file = templates/body/main/sidebar/htmli.phtml
       		template.htmli.name = HTMLi
		</script>
	</div>
	<div id="ie_clearing">&nbsp;</div>
</div>