<div id="col1" style="float:right;margin:0;width:746px;">
	<div id="col1_content" class="clearfix" style="padding:0 0 10px 18px;">
		<a id="content"></a>
		<script type="application/x-aitsu" src="PagetitleAsHeadline:Headline">
			tag = h2
		</script>
		<script type="application/x-aitsu" src="HTML:CopyCol1"></script>
		<script type="application/x-aitsu" src="Template:Subcolumn1">
			defaultTemplate = none
		    
			template.none.name = default (none)
    		template.none.file = templates/body/main/subcolumns/none.phtml

			template.100.name = 100%
    		template.100.file = templates/body/main/subcolumns/100.phtml

			template.25_75.name = 25% | 75%
    		template.25_75.file = templates/body/main/subcolumns/25_75.phtml

			template.33_33_33.name = 33% | 33% | 33%
    		template.33_33_33.file = templates/body/main/subcolumns/33_33_33.phtml
		</script>
	</div>
</div>
<div id="col3" style="float:none;margin-right:746px;width:234px;">
	<div id="col3_content" class="clearfix">
		<script type="application/x-aitsu" src="Navigation:Col3">
			idcat = 31
			template = sidebar
		</script>
		<script type="application/x-aitsu" src="HTML:CopyCol3"></script>
		<script type="application/x-aitsu" src="HTMLi:CopyCol3i"></script>
	</div>
</div>