<div id="col1">
	<div id="col1_content" class="clearfix" style="padding:0 0 10px 18px;">
		<a id="content"></a>
		<script type="application/x-aitsu" src="PagetitleAsHeadline:Headline">
			tag = h2
		</script>
		<script type="application/x-aitsu" src="HTML:CopyCol1"></script>
	</div>
</div>
<div id="col2">
	<div id="col2_content" class="clearfix">
		<script type="application/x-aitsu" src="Navigation:Col2">
			idcat = 1
			template = columns_stepped
		</script>
		<script type="application/x-aitsu" src="HTML:CopyCol2"></script>
	</div>
</div>
<div id="col3">
	<div id="col3_content" class="clearfix">
		<script type="application/x-aitsu" src="Template:Sidebar">
       		defaultTemplate = html

       		template.html.file = templates/body/main/sidebar/html.phtml
       		template.html.name = HTML

       		template.htmli.file = templates/body/main/sidebar/htmli.phtml
       		template.htmli.name = HTMLi
		</script>
	</div>
	<div id="ie_clearing">&nbsp;</div>
</div>