<div id="col1" style="float:right;margin:0;width:746px;">
	<div id="col1_content" class="clearfix" style="padding:0 0 10px 18px;">
		<a id="content"></a>
		<script type="application/x-aitsu" src="PagetitleAsHeadline:Headline">
			tag = h2
		</script>
		<script type="application/x-aitsu" src="HTML:CopyCol1"></script>
	</div>
</div>
<div id="col3" style="float:none;margin-right:746px;width:234px;">
	<div id="col3_content" class="clearfix">
		<script type="application/x-aitsu" src="Navigation:Col3">
			idcat = 1
			template = columns_stepped
		</script>
		<script type="application/x-aitsu" src="HTML:CopyCol3"></script>
	</div>
</div>