<?php $user = Aitsu_Adm_User :: getInstance(); ?>
<?php foreach (Zend_Registry :: get('nav') as $pos) : ?>
	<?php if ($pos->id != 'logout' && (!isset($pos->ac) || $user->isAllowed($pos->ac))) : ?>
		{
			text: '<?php echo $pos->label; ?>',
			<?php if (!empty($pos->icon)) : ?>
			iconCls: '<?php echo $pos->icon; ?>',
			<?php endif; ?>
			margins: '0 10 0 10',
			<?php if (count($pos->pages) > 0) : ?>
				menu: {
					items: [
					<?php foreach ($pos->pages as $subPage) : ?>
						<?php if (!isset($subPage->ac) || $user->isAllowed($subPage->ac)) : ?>
							{
								text: '<?php echo $subPage->label; ?>',
								<?php if (!empty($subPage->icon)) : ?>
									iconCls: '<?php echo $subPage->icon; ?>',
								<?php endif; ?>
								<?php if (count($subPage->pages) > 0) : ?>
									menu: {
										items: [
											<?php foreach ($subPage->pages as $subSubPage) : ?>
											<?php if (!isset($subSubPage->ac) || $user->isAllowed($subSubPage->ac)) : ?>
											{
												text: '<?php echo $subSubPage->label; ?>',
												<?php if (!empty($subSubPage->icon)) : ?>
													iconCls: '<?php echo $subSubPage->icon; ?>',
												<?php endif; ?>	
												listeners: {
													click: function() {
														window.location.href = '<?php echo $subSubPage->getHref(); ?>';
													}
												}									
											},
											<?php endif; ?>
											<?php endforeach; ?>
											{hidden:true}
										]
									}
								<?php else : ?>
								listeners: {
									click: function() {
										window.location.href = '<?php echo $subPage->getHref(); ?>';
									}
								}
								<?php endif; ?>
							},
						<?php endif; ?>
					<?php endforeach; ?>
					{hidden:true}
					]
				}
			<?php else : ?>
				listeners: {
					click: function() {
						Ext.Loader.load(['<?php echo $pos->getHref(); ?>?ajax=1'], null, this, false);
					}
				}
			<?php endif; ?>
		},
	<?php endif; ?>
<?php endforeach; ?>