{
	title:'<?php echo $this->field->index; ?>',
	layout:'fit',
	border: false,
	items: [{
		xtype: 'textarea',
		name: 'content[<?php echo $this->field->index; ?>]',
		value: '<?php echo str_replace("'", "\\'", str_replace("\r", '', str_replace("\n", '\n', str_replace("\\", "\\\\", $this->field->content)))); ?>',
		<?php if ($this->field->type == Aitsu_Content :: PLAINTEXT) : ?>
		listeners : {			
		}
		<?php elseif ($this->field->type == Aitsu_Content :: HTML) : ?>
		listeners: {
			afterrender: function(f) {
				CKEDITOR.replace(f.getId(), {
					toolbar: [
						['Source'],
						['Cut','Copy','PasteText'],
						['Undo','Redo','-','Replace','-','SelectAll','RemoveFormat'],
						['Styles','Format'],
						['Maximize', 'ShowBlocks'],
						'/',
						['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
						['NumberedList','BulletedList','-','Outdent','Indent','Blockquote','CreateDiv'],
						['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
						['Link','Unlink','Anchor'],
						['HorizontalRule','SpecialChar']
					],
               		toolbarCanCollapse: false,
               		skin: 'office2003',
               		height: win.getSize().height - 163,
               		resize_enabled: false
               	});
			},
			beforedestroy: function(f) {
				CKEDITOR.instances[f.getId()].destroy();
			}
		}
		<?php endif; ?>
	}]
}