<?php echo var_export($this->field, true); ?>
{
	xtype: 'radiogroup',
	<?php if (!empty($this->field->label)) : ?>
		fieldLabel: '<?php echo $this->field->label; ?>',
	<?php else : ?>
		hideLabel: true,
	<?php endif; ?>
	columns: 2,
	items: [
		<?php $counter = 0; foreach ($this->field->params['keyValuePairs'] as $key => $value) : $counter++; ?>
		{
			boxLabel: '',
			name: '', 
			inputValue: ''
			checked: false
		}
		<?php if ($counter < count($this->field->params['keyValuePairs'])) : ?>
		,
		<?php endif; ?>
		<?php endforeach; ?>
		/*{boxLabel: 'Item 1', name: 'rb-auto', inputValue: 1},
        {boxLabel: 'Item 2', name: 'rb-auto', inputValue: 2, checked: true},
        {boxLabel: 'Item 3', name: 'rb-auto', inputValue: 3},
        {boxLabel: 'Item 4', name: 'rb-auto', inputValue: 4},
        {boxLabel: 'Item 5', name: 'rb-auto', inputValue: 5}*/
	]
}