<?php echo var_export($this->field, true); ?>

{
	xtype: 'radiogroup',
	fieldLabel: 'Auto Layout',
	items: [
		{boxLabel: 'Item 1', name: 'rb-auto', inputValue: 1},
        {boxLabel: 'Item 2', name: 'rb-auto', inputValue: 2, checked: true},
        {boxLabel: 'Item 3', name: 'rb-auto', inputValue: 3},
        {boxLabel: 'Item 4', name: 'rb-auto', inputValue: 4},
        {boxLabel: 'Item 5', name: 'rb-auto', inputValue: 5}
	]
}