<!-- main -->
<ul data-role="listview" data-inset="true" style="margin-top: 20px; padding-top: 0;" >
<?php $i=1; foreach ($this->nav as $nav) : ?>
	<li class="woh" style=" margin-left: 75px; height: 45px; margin: 5px 0; background: url(/skin/images/icons/<?php echo $nav['name']; ?>.png) no-repeat 20px center; height: 45px;border-bottom: 1px solid #000;">
	<a style="margin-left: 80px; font-family: 'KieviBol'; font-size: 17px; text-transform: capitalize;" href="#<?php echo $nav['name']; ?>" data-transition="slide"><?php echo $nav['name']; ?></a>
	</li>
<?php $i++; endforeach; ?>
</ul>	