<ul class="horizontal-top-down">
	<?php foreach ($this->nav->children as $nav) : ?>
		<?php if ($nav->isvisible) : ?>
			<li<?php if($nav->iscurrent) : ?> class="active"<?php endif; ?>>
				<?php echo strtoupper($nav->name); ?>
				<?php if (count($nav->children) > 0) : ?>
					<ul>
					<?php foreach ($nav->children as $subnav) : ?>
						<?php if ($subnav->isvisible) : ?>
							<li<?php if($subnav->iscurrent) : ?> class="active"<?php endif; ?>>
								<a<?php if($subnav->iscurrent) : ?> class="active"<?php endif; ?> href="{ref:idcat-<?php echo $subnav->idcat; ?>}"><?php echo $subnav->name; ?></a>
							</li>	
						<?php endif; ?>					
					<?php endforeach; ?>
					</ul>
				<?php endif; ?>
			</li>
		<?php endif; ?>
	<?php endforeach; ?>
</ul>