<footer id='footerui0' style='background: white; height: 40px; border: 0; text-align: center;'>
	<div style="bottom: 0px; right:0; position: fixed;">
		<div style="float: right; padding: 0 30px 0 0;">
			<a href="" data-transition="fade">
	        <img src="/skin/images/icons/english.png" border="0" width="30px">
    	    </a>
		</div>  
	    <div style="float: right; padding: 0 30px 0 0;">
    		<a href="" data-transition="fade">
        	<img src="/skin/images/icons/facebook.png" border="0" width="30px">
            </a>
        </div>
    	<div style="float: right; padding: 0 30px 0 0;">
        	<a href="" data-transition="fade">
	        <img src="/skin/images/icons/twitter.png" border="0" width="30px">
    	    </a>
    	</div>
    </div>
</footer>