<div itemscope itemtype="http://schema.org/CreativeWork" class="SchemaOrg CreativeWork">
	<link itemprop="url" href="<?php echo $this->url; ?>" />
	<?php if (!empty($this->image)) : ?>
		<img itemprop="image" src="<?php echo Aitsu_Config :: get('sys.mainDir'); ?>image/100/100/2/<?php echo $this->idart; ?>/<?php echo $this->image; ?>" width="100" height="100" />
	<?php endif; ?>
	<div itemprop="description"><?php echo htmlentities($this->description, ENT_COMPAT, 'UTF-8'); ?></div>
	<dl>
		<dt>About:</dt>
			<dd itemprop="about">_[Schema.Org.Item:<?php echo $this->index; ?>_about]</dd>
		<dt>Aggregate rating:</dt>
			<dd itemprop="aggregateRating">_[Schema.Org.AggregateRating:<?php echo $this->index; ?>_aggregateRating]</dd>
		<?php if (!empty($this->name)) :?>
		<dt>Name:</dt>
			<dd itemprop="name"><?php echo htmlentities($this->name, ENT_COMPAT, 'UTF-8'); ?></dd>
		<?php endif; ?>
	</dl>
</div>