var categories = new Ext.grid.GridPanel({
	title: '<?php echo $this->categoryname; ?>',
	store: new Ext.data.ArrayStore({
		fields: [
			{name: 'id'},
			{name: 'title'},
			{name: 'pagetitle'},
			{name: 'urlname'},
			{name: 'online'},
			{name: 'published'},
			{name: 'isstart'}
		],
		data: <?php echo Aitsu_Util_Javascript :: getArrayString($this->articles, array('idart', 'title', 'pagetitle', 'urlname', 'online', 'published', 'isstart')); ?>
    }),
    columns: [
    	{
    		xtype: 'actioncolumn',
    		width: 30,
    		menuDisabled: true, 
            sortable: false,
    		items: [
    			{
                    getClass: function(v, meta, rec) {
                    	if (rec.get('online') == 1) {
                    		this.items[0].tooltip = 'Online';
                    		return 'page-online';
                    	} else {
                    		this.items[0].tooltip = 'Offline';
                    		return 'page-offline';
                    	}
                    },
                    handler: function(grid, rowIndex, colIndex) {
                    	if (categories.getStore().getAt(rowIndex).get('online') == 0) {
                    		categories.getStore().getAt(rowIndex).set('online', 1);
                    	} else {
                    		categories.getStore().getAt(rowIndex).set('online', 0);
                    	}
                    }
                },
    			{
                    getClass: function(v, meta, rec) {
                    	if (rec.get('published') == 1) {
                    		this.items[1].tooltip = 'Published';
                    		return 'page-published';
                    	} else {
                    		this.items[1].tooltip = 'Unpublished';
                    		return 'page-unpublished';
                    	}
                    },
                    handler: function(grid, rowIndex, colIndex) {
                    	if (categories.getStore().getAt(rowIndex).get('published') == 0) {
                    		categories.getStore().getAt(rowIndex).set('published', 1);
                    	} else {
                    		categories.getStore().getAt(rowIndex).set('published', 0);
                    	}
                    }
                },
    			{
                    getClass: function(v, meta, rec) {
                    	if (rec.get('isstart') == 1) {
                    		this.items[2].tooltip = 'Index article';
                    		return 'page-indexpage';
                    	}
                    }
                }
             ]
        },
    	{dataIndex: 'id', header: 'ID', menuDisabled: true, sortable: true, width: 20},
    	{dataIndex: 'title', header: 'Title', menuDisabled: true, sortable: true},
    	{dataIndex: 'pagetitle', header: 'Pagetitle', menuDisabled: true, sortable: true},
    	{dataIndex: 'urlname', header: 'URL name', menuDisabled: true, sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	border: false,
	tbar: {
		items: {
            text: 'Add new article',
            iconCls: 'tb-add',
            handler: function(b, e) {
            	Ext.Ajax.request({
            		url: '<?php echo $this->url(array('controller' => 'data', 'action' => 'newarticle'), 'default'); ?>',
            		success: function(response, opts) {
            			var rsp = Ext.decode(response.responseText);
            			rsp.id = rsp.idart;
            			var store = categories.getStore();
            			store.addSorted(new store.recordType(rsp));            			
            		},
            		failure: function() {
            			alert('something went wrong!');
            		},
            		params: { idcat: '<?php echo $this->idcat; ?>' }
            	});
            }
        }
	}
});

tabs.add(categories);
tabs.setActiveTab(0);

<?php return; ?>
<div class="toolbar">
	<button id="add-new-article" class="type-new"><?php echo $this->translate('Add new article'); ?></button>
	<button id="paste-article" class="type-clipboard<?php if ($this->isClipboardEmpty) {echo ' init-disabled';} ?>" style="margin-right:15px;"><?php echo $this->translate('Paste from clipboard'); ?></button>
	<button id="add-to-favorites" value="<?php echo $this->idcat; ?>" class="type-new<?php if ($this->isInFavories) {echo ' init-disabled';} ?>"><?php echo $this->translate('Add category to favorites'); ?></button>
	<button id="remove-from-favorites" value="<?php echo $this->idcat; ?>" class="type-delete<?php if (!$this->isInFavories) {echo ' init-disabled';} ?>"><?php echo $this->translate('Remove from favorites'); ?></button>
</div>
	
<div class="sized-content">
	<table border="0" cellpadding="0" cellspacing="0" class="full clickable editduplicatedelete">
		<thead>
			<tr>
				<th scope="col" style="width:68px;"><?php echo $this->translate('Status'); ?></th>
				<th scope="col"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Title'); ?></th>
				<th scope="col"><?php echo $this->translate('Page title'); ?></th>
				<th scope="col"><?php echo $this->translate('URL name'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $counter = -1; foreach ($this->articles as $art) : $art = (object) $art; $counter++; ?>
				<?php if ($art->isstart == 1 && $art->synced == 1) : ?>
					<tr id="idart-<?php echo $art->idart; ?>">
						<th>
							<?php if ($art->online == 1) : ?>
								<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Online'); ?>" class="article online">&nbsp;</a>
							<?php else : ?>
								<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Offline'); ?>" class="article offline">&nbsp;</a>
							<?php endif; ?>
							<?php if ($this->usePublishing) : ?>
								<?php if ($art->published == 1) : ?>
									<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Current version is online'); ?>" class="article published">&nbsp;</a>
								<?php else : ?>
									<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Differences to published version'); ?>" class="article unpublished">&nbsp;</a>
								<?php endif; ?>
							<?php endif; ?>
						</th>
						<th><?php echo $art->idart; ?> [<?php echo $art->idartlang; ?>]</th>
						<th><?php echo $art->title; ?></th>
						<th><?php echo $art->pagetitle; ?></th>
						<th><?php echo $art->urlname; ?></th>
					</tr>
				<?php else : ?>
					<tr id="idart-<?php echo $art->idart; ?>" class="<?php echo ($counter % 2 == 0 ? 'odd' : 'even'); ?><?php if ($art->synced == 0) {echo ' unsynced ui-state-disabled';} ?>">
						<td>
							<?php if ($art->online == 1) : ?>
								<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Online'); ?>" class="article online">&nbsp;</a>
							<?php else : ?>
								<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Offline'); ?>" class="article offline">&nbsp;</a>
							<?php endif; ?>
							<?php if ($this->usePublishing) : ?>
								<?php if ($art->published == 1) : ?>
									<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Current version is online'); ?>" class="article published">&nbsp;</a>
								<?php else : ?>
									<a href="<?php echo $art->idart; ?>" title="<?php echo $this->translate('Publish current version'); ?>" class="article unpublished">&nbsp;</a>
								<?php endif; ?>
							<?php endif; ?>
						</td>
						<td><?php echo $art->idart; ?> [<?php echo ($art->synced == 1 ? $art->idartlang : 'NS'); ?>]</td>
						<td><?php echo $art->title; ?></td>
						<td><?php echo $art->pagetitle; ?></td>
						<td><?php echo $art->urlname; ?></td>
					</tr>
				<?php endif; ?>
			<?php endforeach; ?>
		</tbody>
	</table>	
</div>		

<script type="text/javascript">
$(function() {
	
	$(document).trigger('refresh-category-overview');

	$('#paste-article').unbind('click');
	$('#paste-article').click(function() {
			if ($(this).hasClass('ui-state-disabled')) {
				return false;
			}
			$.post('<?php echo $this->url(array('controller' => 'data', 'action' => 'movehere'), 'default'); ?>', {idcat: <?php echo $this->idcat; ?>}, function(data) {
				$('#status').html(data.message);
	  			$(document).trigger('load-category-overview');
	  			$.jstree._reference('#art-tree').refresh(-1);
			});
		});
	
});
</script>