<?php foreach ($this->surveyXML->analysis[0] as $score) : ?>
	<?php if ($this->valueToBeUsed >= $score['min'] && $this->valueToBeUsed < $score['max']) : ?>
		<div class="surveyAnalysis"><h1><?php echo Aitsu_Translate :: _('Ihre Auswertung'); ?></h1>
		<div class="surveyAnalysisTitle"><h3>
			<?php echo $score['title']; ?>
		</h3></div>
		<div class="surveyAnalysisText">
			<?php echo $score; ?>
		</div>
		</div>
	<?php endif; ?>
<?php endforeach; ?>
