<?php $post = Module_Custom_Migros_Fitnesspark_Go_Class :: _getPost($this->number); ?>

<?php $answerNo = -1; foreach ($this->question->answer as $answer) : $answerNo++; $id = uniqid(); ?>
	<div class="surveyAnswer">
		<?php if ($post[$answerNo] == $answer['value']) : ?>
			<div class="surveySelectButton">
				<input type="checkbox" id="<?php echo $id; ?>" checked="checked" name="<?php echo $this->formNamePrefix; ?><?php echo $this->number; ?>[<?php echo $answerNo; ?>]" value="<?php echo $answer['value']; ?>" />
			</div>
		<?php else : ?>
			<div class="surveySelectButton">
				<input type="checkbox" id="<?php echo $id; ?>" name="<?php echo $this->formNamePrefix; ?><?php echo $this->number; ?>[<?php echo $answerNo; ?>]" value="<?php echo $answer['value']; ?>" />
			</div>
		<?php endif; ?>
		<label for="<?php echo $id; ?>" class="surveySelectButtonLabel">
			<?php echo $answer['answer']; ?>
		</label>
	</div>
<?php endforeach; ?>