<ul id="skiplinks">
  <li><a class="skip" href="#nav">Skip to navigation (Press Enter).</a></li>
  <li><a class="skip" href="#col1">Skip to main content (Press Enter).</a></li>
</ul>

<div class="page_margins">
  <div class="page">
    <div id="header">
      <div class="subcolumns">
        <div class="c25l">
          <div class="subcl">
            <script type="application/x-aitsu" src="Logo"></script>
          </div>
        </div>
        <div class="c50l">
          <div class="subc">
            <div class="subcolumns">
              <div class="c40l">
                <div class="subcl">
                  <ul>
                    <li><a href="#" title=""><span class="more">Alle Fitnessparks</span></a></li>
                    <li><a href="#" title="" style="white-space: nowrap">Puls 5</a></li>
                    <li><a href="#" title="" style="white-space: nowrap">Regensdorf</a></li>
                    <li><a href="#" title="" style="white-space: nowrap">Milandia</a></li>
                    <li><a href="#" title="" style="white-space: nowrap">Gesundheit im Zentrum</a></li>
                  </ul>
                </div>
              </div>
              <div class="c60r">
                <div class="subcr">
                  <div id="" class="vcard">
                    <div class="org"><strong>Fitnesspark Stockerhof</strong></div>
                    <div class="adr">
                      <div class="street-address">Dreikönigstrasse 31a</div>
                      <div><span class="postal-code">8002</span> <span class="locality">Zürich</span></div>
                    </div>
                    <div>Tel. <span class="tel">044 206 50 50</span></div>
                  </div>
                  <div><a href="#" title="">E-Mail</a></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="c25r">
          <div class="subcr">
            <div class="opening">
              <strong>Öffnungzeiten</strong>
              <p>Mo - Fr 08.00 - 22.00 Uhr<br/>
              Sa u. So 09.00 - 20.00 Uhr</p>
            </div>
            <form class="yform">
              <div class="type-text"><input type="text" value=""/> <input type="submit" value="Suchen" /></div>
            </form>
          </div>
        </div>
      </div>
    </div>
    <div id="nav">
      <div class="hlist">
      	<script type="application/x-aitsu" src="Navigation">
      		idcat = 1
      		template = top
      	</script>
      </div>
    </div>
    <div id="main">
      <div id="col1">
        <div id="col1_content" class="clearfix">
          <script type="application/x-aitsu" src="HeaderImage:Header"></script>
          
          <script type="application/x-aitsu" src="HTML:Main"></script>
          
          <script type="application/x-aitsu" src="Template:MainBottom">
          	defaultTemplate = promo
          	
          	template.promo.name = Promotion
          	template.promo.file = templates/promotion.phtml
          	
          	template.html.name = HTML
          	template.html.file = templates/htmlMainBottom.phtml
          	
          	template.none.name = --
          	template.none.file = templates/none.phtml
          </script>
          
        </div>
      </div>
      <div id="col3">
        <div id="col3_content" class="clearfix">
          <div class="info latest">
            <script type="application/x-aitsu" src="Aktuell"></script>
          </div>
          <div class="info course">
            <h3>Kurse heute 12.10.2010</h3>
            <ul>
              <li><a href="#" title="">09:30 Spinning</a></li>
              <li><a href="#" title="">11:00 Aquaplaning</a></li>
              <li><a href="#" title="">13:00 Kick-Power</a></li>
              <li><a href="#" title="">17:00 Nächster Kurs</a></li>
              <li><a href="#" title="">18:30 Noch ein Kurs</a></li>
              <li><a href="#" title=""><span class="more">Alle Kurse...</span></a></li>
            </ul>
          </div>
          <div class="info mostreaded">
            <script type="application/x-aitsu" src="MostImpressed"></script>
          </div>
        </div>
        <div id="ie_clearing">&nbsp;</div>
      </div>
    </div>
    <div id="footer">
    	<script type="application/x-aitsu" src="Template:Footer">
    		defaultTemplate = templates/footer.phtml
    	</script>
    </div>
  </div>
</div>
