<div class="subcolumns">
	<div class="c75l">
		<div class="subcl" style="padding-left:0; margin-left:0; font-size:10px;">
			<script type="application/x-aitsu" src="BreadCrumb"></script>
		</div>
	</div>

	<div class="c25r">
		<div class="subcr" style="padding-left:0; font-size:10px;">
			&copy; 2011 - Genossenschaft Migros Zürich
			<script type="application/x-aitsu" src="HitTrigger"></script>
		</div>
	</div>
</div>