var tagToken = new Ext.form.ComboBox({
	id: 'tagid',
    typeAhead: true,
    triggerAction: 'all',
    lazyRender:true,
  	width: 150,
  	minChars: 1,
  	emptyText: '<?php echo Aitsu_Translate :: translate('Choose tag'); ?>',
    store: new Ext.data.JsonStore({
    	autoDestroy: true,
    	url: '<?php echo $this->url(array('plugin' => 'tags', 'paction' => 'tagstore'), 'aplugin'); ?>',
    	storeId: 'tagsStore',
    	root: 'data',
    	idProperty: 'tagid',
    	fields: ['tagid', 'tag']
	}),
    valueField: 'tag',
    displayField: 'tag'
});

var tagValue = new Ext.form.TextField({
	id: 'tagvalue',
	width: 150,
	style: {
		margin: '0 5px 0 5px'
	},
	emptyText: 'NULL'
});

var tags = new Ext.grid.GridPanel({
	store: new Ext.data.JsonStore({
        autoDestroy: true,
        url: '<?php echo $this->url(array('plugin' => 'tags', 'paction' => 'store'), 'aplugin'); ?>',
        remoteSort: false,
        storeId: 'articleTagsStore',
        idProperty: 'tagid',
        root: 'data',
        fields: [{
            name: 'tagid'
        }, {
            name: 'tag'
        }, {
            name: 'value'
        }],
        baseParams: {
        	idart: <?php echo $this->idart; ?>
        }
    }),
    columns: [
    	{dataIndex: 'tag', header: '<?php echo Aitsu_Translate :: translate('Tag'); ?>', menuDisabled: true, sortable: true},
    	{dataIndex: 'value', header: '<?php echo Aitsu_Translate :: translate('Value'); ?>', menuDisabled: true, sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	hideHeaders: true,
	border: false,
	tbar: {
		items: [
			tagToken,
			tagValue,
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Save tag'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	var token = tagToken.getValue();
	            	var value = tagValue.getValue();
	            	Ext.Ajax.request({
	            		url: '<?php echo $this->url(array('plugin' => 'tags', 'paction' => 'add'), 'aplugin'); ?>',
	            		success: function(response, opts) {
	            			tags.getStore().load();
	            			tagToken.setValue('');
	            			tagValue.setValue('');
	            		},
	            		params: {
	            			idart: <?php echo $this->idart; ?>,
	            			token: token,
	            			value: value
	            		}
	            	});
	            }
	        }
	    ]
	},
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		},
		rowclick: function(grid, rowIndex, event) {
			var record = this.getStore().getAt(rowIndex);
			// put values to form.
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
	            	Ext.Ajax.request({
	            		url: '<?php echo $this->url(array('plugin' => 'tags', 'paction' => 'delete'), 'aplugin'); ?>',
	            		success: function(response, opts) {
	            			var rsp = Ext.decode(response.responseText);
	            			if (rsp.success) {
		            			var store = grid.getStore().remove(record); 
	            			}
	            		},
	            		params: {
	            			idart: <?php echo $this->idart; ?>,
	            			tagid: record.get('tagid')
	            		}
	            	});					 			
				}
			});
			
			menu.showAt(event.getXY());
		}
			
	}
});

Ext.getCmp('page-plugin-accordion').add({
	id: 'article-plugin-tags',
	title: '<?php echo Aitsu_Translate :: translate('Tags'); ?>',
	layout: 'fit',
	items: tags
});
