var center = Ext.getCmp('viewport-center');
center.removeAll();

var rewritehistoryGrid = new Ext.grid.GridPanel({
	title: '<?php echo Aitsu_Translate :: translate('Rewrite History'); ?>',
	id: 'rewritehistoryGrid',
	store: new Ext.data.JsonStore({
		url: '<?php echo $this->url(array('paction' => 'store')); ?>',
		root: 'data',
		fields: ['id', 'url', 'target', 'idart'],
		autoLoad: true
	}),
    columns: [
        {dataIndex: 'id', width: 60, fixed: true, header: 'id', sortable: true},
    	{dataIndex: 'url', header: '<?php echo Aitsu_Translate :: translate('URL'); ?>', sortable: true},
    	{dataIndex: 'target', header: '<?php echo Aitsu_Translate :: translate('Target'); ?>', sortable: true},
        {dataIndex: 'idart', width: 60, header: '<?php echo Aitsu_Translate :: translate('idart'); ?>', sortable: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Add new Rewrite Rule'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	Ext.aitsu.load(['<?php echo $this->url(array('paction' => 'edit')); ?>']);
	            }
	        }
	    ]
	},
	listeners: {
		rowclick: function(grid, rowIndex, event) {
			var rec = grid.getStore().getAt(rowIndex);
			Ext.aitsu.load(['<?php echo $this->url(array('paction' => 'edit')); ?>'], null, {
				id: rec.get('id')
			});
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete Rewrite Rule'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected rewrite rule?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('paction' => 'delete')); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Rule removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected rewrite rule has been removed.'); ?>');
					            			grid.getStore().load(); 
				            			}
				            		},
				            		params: { id: record.get('id') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}		
	}
});

center.add(rewritehistoryGrid);

Ext.getCmp('viewport').doLayout();