<div class="toolbar ui-corner-bottom">
	<button id="add-new-client" class="type-new confirm" title="<?php echo $this->translate('Add new client'); ?>"><?php echo $this->translate('Add new client'); ?></button>
</div>
		
<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
	<thead>
		<tr>
			<th scope="col"><?php echo $this->translate('ID'); ?></th>
			<th scope="col"><?php echo $this->translate('Name'); ?></th>
			<th scope="col"><?php echo $this->translate('Configuration'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $counter = 0; foreach ($this->clients as $client) : $counter++; ?>
			<tr id="client-<?php echo $client->idclient; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>">
				<td><?php echo $client->idclient; ?></td>
				<td><?php echo $client->name; ?></td>
				<td><?php echo $client->config; ?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>