var dashboard = Ext.getCmp('dashboard');

var store = new Ext.data.JsonStore({
		        autoDestroy: true,
		        url: '<?php echo $this->url(array('paction' => 'store')); ?>',
		        root: 'data',
		        fields: [{
		            name: 'pagetitle'
		        }, {
		            name: 'title'
		        }, {
		            name: 'duedate',
                            type: 'date',
                            dateFormat: 'Y-m-d H:i:s'
		        }, {
		            name: 'description'
		        }]
		    });
                    
var todoExpander = new Ext.ux.grid.RowExpander({
    tpl : new Ext.Template(
        '<pre style="padding:10px;">{description}</pre>'
    )
});	

var todos = new Ext.grid.GridPanel({
    id: 'todos',
    title: 'To-do List',
    store: store,
    sortInfo: {
        field: 'duedate',
        direction: 'ASC'
    },
    columns: [
    	todoExpander,
    	{dataIndex: 'pagetitle', header: '<?php echo Aitsu_Translate :: translate('Pagetitle'); ?>', menuDisabled: true, sortable: true, width: 50},
        {dataIndex: 'title', header: '<?php echo Aitsu_Translate :: translate('To Do'); ?>', menuDisabled: true, sortable: true},
    	{dataIndex: 'duedate', header: '<?php echo Aitsu_Translate :: translate('Due'); ?>', menuDisabled: true, sortable: true, width: 25, renderer: Ext.util.Format.dateRenderer('Y-m-d')}
    ],
    viewConfig: {
        forceFit: true,
        autoFill: true
    },
	listeners: {
		render: {
			fn: function(){
				this.getStore().load();
			}
		}
	},
	plugins: todoExpander
});

dashboard.add({
	columnWidth: 1/3,
	baseCls:'x-plain',
	bodyStyle:'padding:6px 4px 0 4px',
	items: {
		unstyled: true,
		height: 370,
		layout: 'fit',
		items: todos
	}
});
