<div class="tabs">
	<ul>
		<li>
			<a href="#tab-modules"><?php echo $this->translate('Modules'); ?></a>
		</li>
	</ul>
	
	<div id="tab-modules">
		<div class="tab-content">
			<div class="toolbar empty"></div>
			<?php echo $this->partial('list.phtml', array('modules' => $this->modules, 'category' => $this->category)); ?>
			<div class="clearfix"></div>
		</div>
	</div>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

	$("div.module-category").equalHeights();
	
});
<?php $this->inlineScript()->captureEnd(); ?>