<div class="sized-content-empty-toolbar">
	<table border="0" cellpadding="0" cellspacing="0" class="full" id="overview">
		<thead>
			<tr>
				<th scope="col"><?php echo $this->translate('Name'); ?></th>
				<th scope="col"><?php echo $this->translate('Class'); ?></th>
				<th scope="col"><?php echo $this->translate('Status'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $counter = 0; $cat = empty($this->category) ? 'All' : $this->category; $modules = $this->modules[$cat]; ?>
			<?php foreach ($modules as $module) : $counter++; ?>
				<tr class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>" style="cursor:pointer;">
					<td>
						<a href="<?php echo $this->url(array('area' => 'system', 'plugin' => 'modules', 'paction' => 'detail', 'category' => $cat, 'module' => $module->id), 'plugin'); ?>"></a>
						<?php echo $module->name; ?>
					</td>
					<td>
						<?php echo $module->className; ?>
					</td>
					<td>
						<?php echo $module->status; ?>
					</td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {
	
	$('table#overview tbody tr').click(function() {
		location.href = $(this).find('a').attr('href');
	});
	
});
<?php $this->inlineScript()->captureEnd(); ?>