<table border="0" cellpadding="0" cellspacing="0" class="full">
	<thead>
		<tr>
			<th scope="col" style="width:40px;">&nbsp;</th>
			<th scope="col"><?php echo $this->translate('File name'); ?></th>
			<th scope="col"><?php echo $this->translate('Media name'); ?></th>
			<th scope="col" style="text-align:right;"><?php echo $this->translate('Size'); ?></th>
			<th scope="col" style="text-align:right;"><?php echo $this->translate('Uploaded'); ?></th>
		</tr>
	</thead>
	<tbody>
		<?php $images = array('jpg', 'jpeg', 'png', 'gif'); foreach ($this->files as $file) : ?>
			<tr id="mediaid-<?php echo $file->mediaid; ?>" style="cursor:pointer;">
				<td>
					<?php if (in_array($file->extension, $images)) : ?>
						<img src="<?php echo $this->url(array('controller' => 'image', 'action' => 'media', 'width' => 32, 'height' => 32, 'boxed' => 1, 'id' => $file->mediaid), 'default'); ?>" width="32" height="32" alt="<?php echo $file->filename; ?>" />
					<?php else : ?>
						<img src="/adm/images/0.gif" width="32" height="32" alt="<?php echo $file->filename; ?>" />
					<?php endif; ?>
				</td>
				<td><?php echo $file->filename; ?></td>
				<td><?php echo $file->name; ?></td>
				<?php if ($file->size > 1024 * 1024) : ?>
					<td style="text-align:right;"><?php echo number_format($file->size / 1024 / 1024, 2); ?> MB</td>
				<?php else : ?>
					<td style="text-align:right;"><?php echo number_format($file->size / 1024, 2); ?> KB</td>
				<?php endif; ?>
				<td style="text-align:right;"><?php echo $file->uploaded; ?></td>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>