var mediaPreview = function(record) {
	var prev = Ext.getCmp('media-preview');
	prev.removeAll();
	prev.add(new Ext.ux.ImageCrop({
		initialHeight: 260,
		initialWidth: 260,
		imageUrl: '<?php echo $this->url(array('controller' => 'image', 'action' => 'media', 'width' => 260, 'height' => 260, 'boxed' => 0), 'default'); ?>/id/' + record.get('mediaid'),
		preserveRatio: false
	}));
	prev.doLayout();
}

var uploader = new Ext.ux.PluploadPanel({
    url: '<?php echo $this->url(array('plugin' => 'media', 'paction' => 'upload'), 'aplugin'); ?>',
    runtimes: 'html5,gears,flash,silverlight,html4',
    multipart: true,
    multipart_params: {
    	idart: <? echo $this->idart; ?>
    },
    max_file_size: '100mb',
    flash_swf_url: '<?php echo $this->baseUrl('/js/plupload/js/plupload.flash.swf'); ?>',
    silverlight_xap_url: '<?php echo $this->baseUrl('/js/plupload/js/plupload.silverlight.xap'); ?>',
    runtime_visible: false,
    addButtonCls: 'upload-add',
    uploadButtonCls: 'upload-start',
    cancelButtonCls: 'upload-stop',
    deleteButtonCls: 'upload-delete',
    addButtonText: '<?php Aitsu_Translate :: translate('Add files'); ?>',
    uploadButtonText: '<?php Aitsu_Translate :: translate('Upload'); ?>',
    cancelButtonText: '<?php Aitsu_Translate :: translate('Cancel'); ?>',
    deleteButtonText: '<?php Aitsu_Translate :: translate('Remove'); ?>',
    deleteSelectedText: '<b>Remove selected</b>',
    deleteUploadedText: 'Remove uploaded',
    deleteAllText: 'Remove ALL',
    statusQueuedText: 'Queued',
    statusUploadingText: 'Uploading ({0}%)',
    statusFailedText: '<span style="color: red">FAILED</span>',
    statusDoneText: '<span style="color: green">DONE</span>',
    statusInvalidSizeText: 'Too big',
    statusInvalidExtensionText: 'Invalid file type',
    emptyText: '<div class="plupload_emptytext"><span>Upload queue is empty</span></div>',
    emptyDropText: '<div class="plupload_emptytext"><span>Drop files here</span></div>',
    progressText: '{0}/{1} ({3} failed) ({5}/s)',
    listeners: {
        beforestart: function(uploadpanel) {
            uploadpanel.uploader.settings.url = '<?php echo $this->url(array('plugin' => 'media', 'paction' => 'upload'), 'aplugin'); ?>?_runtime=' + uploadpanel.runtime;
        },
        uploadcomplete: function(uploadpanel, success, failures) {
            if (success.length) {
                media.getStore().load({
					params: {
						idart: <?php echo $this->idart; ?>
					}
				});
            }
        }
    }
});

var media = new Ext.grid.GridPanel({
	title: '<?php echo Aitsu_Translate :: translate('Media'); ?>',
	store: new Ext.data.JsonStore({
        autoDestroy: true,
        url: '<?php echo $this->url(array('plugin' => 'media', 'paction' => 'store'), 'aplugin'); ?>',
        remoteSort: false,
        storeId: 'mediaStore',
        idProperty: 'mediaid',
        root: 'data',
        fields: [{
            name: 'mediaid'
        }, {
            name: 'idart'
        }, {
            name: 'filename'
        }, {
            name: 'extension'
        }, {
            name: 'size'
        }, {
            name: 'xtl'
        }, {
            name: 'ytl'
        }, {
            name: 'xbr'
        }, {
            name: 'ybr'
        }, {
            name: 'uploaded',
            type: 'date',
            dateFormat: 'Y-m-d H:i:s'
        }, {
            name: 'name'
        }, {
            name: 'subline'
        }, {
            name: 'description'
        }]
    }),
    columns: [
    	{dataIndex: 'mediaid', header: '<?php echo Aitsu_Translate :: translate('Preview'); ?>', width: 40, menuDisabled: false, sortable: false, renderer: function(value, metaData, record, rowIndex, colIndex, store) {
    		var extension = record.get('extension').toLowerCase();
    		if (extension != 'jpg' && extension != 'gif' && extension != 'jpeg' && extension != 'png') {
    			return '';
    		}
    		return '<img src="<?php echo $this->url(array('controller' => 'image', 'action' => 'media', 'width' => 32, 'height' => 32, 'boxed' => 2), 'default'); ?>/id/' + record.get('mediaid') + '" width="32" height="32" alt="' + record.get('filename') + '" />';
    	}},
    	{dataIndex: 'mediaid', header: 'ID', menuDisabled: false, sortable: true, width: 20},
    	{dataIndex: 'filename', header: '<?php echo Aitsu_Translate :: translate('File name'); ?>', menuDisabled: false, sortable: true},
    	{dataIndex: 'name', header: '<?php echo Aitsu_Translate :: translate('Media name'); ?>', menuDisabled: false, sortable: true},
    	{dataIndex: 'uploaded', header: '<?php echo Aitsu_Translate :: translate('Date'); ?>', menuDisabled: false, sortable: true, renderer: Ext.util.Format.dateRenderer('Y-m-d H:i:s')}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
	border: false,
	listeners: {
		render: {
			fn: function(){
				this.getStore().load({
					params: {
						idart: <?php echo $this->idart; ?>
					}
				});
				media.getSelectionModel().on('rowselect', function(selectionModel, rowIndex, record) {
					var form = Ext.getCmp('media-edit-form').getForm();
						form.findField('mediaid').setValue(record.get('mediaid'));
						form.findField('filename').setValue(record.get('filename'));
						form.findField('name').setValue(record.get('name'));
						form.findField('subline').setValue(record.get('subline'));
						form.findField('description').setValue(record.get('description'));
						Ext.getCmp('media-edit-form-save-button').enable();
						mediaPreview(record);
				});
			}
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			var selectionModel = this.getSelectionModel();
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete files'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected file(s)?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
					 			selectionModel.each(function(record) {
					            	Ext.Ajax.request({
					            		url: '<?php echo $this->url(array('plugin' => 'media', 'paction' => 'delete'), 'aplugin'); ?>',
					            		success: function(response, opts) {
					            			var rsp = Ext.decode(response.responseText);
					            			if (rsp.success) {
						            			grid.getStore().remove(record); 
					            			}
					            		},
					            		params: { 
					            			mediaid: record.get('mediaid'),
					            			idart: record.get('idart')	
					            		}
					            	});					 			
								});
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}
			
	},
	plugins: [
		new Ext.ux.grid.GridFilters({
			encode: false,
	        local: false,
	        filters: [{
	            type: 'numeric',
	            dataIndex: 'roleid'
	        }, {
	            type: 'string',
	            dataIndex: 'identifier'
	        }]
		})
	]
});

Ext.getCmp('page-edit-tab').add({
	id: 'article-plugin-media',
	title: '<?php echo Aitsu_Translate :: translate('Media'); ?>',
	layout: 'border',
	items: [
		{
			region: 'center',
			split: true,
			layout: 'fit',
			items: media
		},
		{
			region: 'south',
			split: true,
			height: 300,
			border: false,
			items: {
				layout: 'column',
				items: [
					{
						width: 500,
						height: 300,
						border: false,
						layout: 'fit',
						items: new Ext.FormPanel({
							url: '<?php echo $this->url(array('plugin' => 'media', 'paction' => 'save'), 'aplugin'); ?>',
							labelAlign: 'left',
							id: 'media-edit-form',
							frame: true,
							border: false,
							bodyStyle:'padding:5px 5px 0',
							items: [
								{
									xtype:'textfield',
									fieldLabel: '<?php echo Aitsu_Translate :: translate('File name'); ?>',
									name: 'filename',
									anchor: '100%'
								}, {
									xtype:'textfield',
									fieldLabel: '<?php echo Aitsu_Translate :: translate('Media name'); ?>',
									name: 'name',
									anchor: '100%'
								}, {
									xtype:'textfield',
									fieldLabel: '<?php echo Aitsu_Translate :: translate('Subline'); ?>',
									name: 'subline',
									anchor: '100%'
								}, {
									xtype:'textarea',
									fieldLabel: '<?php echo Aitsu_Translate :: translate('Description'); ?>',
									name: 'description',
									anchor: '100%',
									height: 160
								}, {
									xtype: 'hidden',
									name: 'mediaid'
								}, {
									xtype: 'hidden',
									name: 'idartlang',
									value: <?php echo $this->idartlang; ?>
								}
							],
							buttons: [{
								id: 'media-edit-form-save-button',
								text: '<?php echo Aitsu_Translate :: translate('Save'); ?>',
            					iconCls: 'save',
            					disabled: true,
            					handler: function(b, e) {
            						Ext.getCmp('media-edit-form').getForm().submit({
										success: function(form, action) {
											media.getStore().load({
												params: {
													idart: <?php echo $this->idart; ?>
												}
											});
										} 
									});
            					}
        					}]
						})
					},
					{
						columnWidth: 1,
						border: false,
						padding: 20,
						id: 'media-preview'
					}
				]
			}
		},
		{
			region: 'east',
			split: true,
			width: 350,
			layout: 'fit',
			items: uploader
		}
	]
});
