<?php $this->headScript()->appendFile('/adm/js/uploadify/v2_1_0/swfobject.js', 'text/javascript'); ?>
<?php $this->headScript()->appendFile('/adm/js/uploadify/v2_1_0/jquery.uploadify.v2.1.0.min.js', 'text/javascript'); ?>

<?php $this->headLink()->appendStylesheet('/adm/js/uploadify/v2_1_0/uploadify.css'); ?>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

});
<?php $this->inlineScript()->captureEnd(); ?>