var dashboard = Ext.getCmp('dashboard');

dashboard.add({
	columnWidth: 1/3,
	baseCls:'x-plain',
	bodyStyle:'padding:6px 4px 0 4px',
	items: {
		unstyled: true,
		height: 370,
		layout: 'vbox',
		items: [
			new Ext.grid.PropertyGrid({
				title: '<?php echo Aitsu_Translate :: translate('Overall performance'); ?>',
				hideHeaders: true,
				source: {
					'<?php echo Aitsu_Translate :: translate('Number of impressions (n)'); ?>': '<?php echo $this->overall['n']; ?>',
					'<?php echo Aitsu_Translate :: translate('Average rendering (ms)'); ?>': '<?php echo $this->overall['avg']; ?>',
					'<?php echo Aitsu_Translate :: translate('Fastest rendering (ms)'); ?>': '<?php echo $this->overall['fastest']; ?>',
					'<?php echo Aitsu_Translate :: translate('Slowest rendering (ms)'); ?>': '<?php echo $this->overall['slowest']; ?>'
				},
				viewConfig : {
					forceFit: true,
					scrollOffset: 2
				},
				listeners: {
					beforeedit: function(e) {
						e.cancel = true;
					}
				}
			}),
			new Ext.grid.PropertyGrid({
				title: '<?php echo Aitsu_Translate :: translate('Slowest page'); ?>',
				hideHeaders: true,
				source: {
					'<?php echo Aitsu_Translate :: translate('Number of impressions (n)'); ?>': '<?php echo $this->slowest['n']; ?>',
					'<?php echo Aitsu_Translate :: translate('Average rendering (ms)'); ?>': '<?php echo $this->slowest['avg']; ?>',
					'<?php echo Aitsu_Translate :: translate('Fastest rendering (ms)'); ?>': '<?php echo $this->slowest['fastest']; ?>',
					'<?php echo Aitsu_Translate :: translate('Slowest rendering (ms)'); ?>': '<?php echo $this->slowest['slowest']; ?>',
					'<?php echo Aitsu_Translate :: translate('URL'); ?>': '<?php echo $this->slowest['url']; ?>',
					'<?php echo Aitsu_Translate :: translate('Page title'); ?>': '<?php echo $this->slowest['pagetitle']; ?>'
				},
				viewConfig : {
					forceFit: true,
					scrollOffset: 2
				},
				listeners: {
					beforeedit: function(e) {
						e.cancel = true;
					}
				},
				flex: 1,
				margins: '5 0 0 0'
			})
		]
	}
});
