<?php
/*
 * The navigation tree. Do not change.
 */
$nav = $this->nav;

/*
 * First level to be displayed.
 * 
 * If you want to display the whole tree, use 0
 * to get valid HTML and change the start category
 * accordingly.
 */
$startLevel = 0;

/*
 * Levels (depth) to be displayed.
 */
$levels = 2;

echo Aitsu_Html_Helper_Navigation_Ul :: get($nav, $startLevel, $levels, array (
	0 => array (
		'ul' => 'main',
		'li' => array (
			'first' => 'first',
			'active' => 'active',
			'parent' => 'parent',
			'inactive' => 'inactive'
		)
	),
	1 => array (
		'ul' => 'sub',
		'li' => array (
			'first' => 'first',
			'active' => 'active',
			'parent' => 'parent',
			'inactive' => 'inactive'
		)
	)
), false);