<footer class="row">
    <div class="large-12 columns"><hr>
        <div class="row">

            <div class="large-6 columns">
                <p>&copy; 2013 - <a href="http://www.webtischlerei.de" target="_blank">webtischlerei</a></p>
            </div>

            <div class="large-6 columns">
                <script type="application/x-moraso" src="Navigation:meta">
                    template = meta
                </script>
            </div>
        </div>
    </div>
</footer>