<!DOCTYPE html>
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="de"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="de"> <!--<![endif]-->
<html> 
	<head>
	<meta charset="UTF-8">	
	<script type="application/x-moraso" src="HTML.Meta.PageTitle">
 	   suffix = " | Wohlmuth Weine"
    </script>
        
    <!-- BaseHref :: Start -->
    <script type="application/x-moraso" src="HTML.Meta.BaseHref"></script>
    <!-- BaseHref :: End -->  
    
    <!-- CanonicalTag :: Start -->
    <script type="application/x-moraso" src="HTML.Meta.CanonicalTag"></script>
    <!-- CanonicalTag :: End -->      

    <!-- Meta Geo Tags :: Start -->
    <meta name="geo.region" content="AT-ST" />
    <meta name="geo.placename" content="Fresing" />
    <meta name="geo.position" content="46.755658;15.441332" />
    <meta name="ICBM" content="46.755658, 15.441332" />
    <!-- Meta Geo Tags :: End -->
    
    <!-- Meta Tags :: Start -->
    <script type="application/x-moraso" src="HTML.Meta.Tags"></script>
    <!-- Meta Tags :: End -->

    <!-- Windows 8 Tile :: Start -->
    <meta name="application-name" content="moraso CMS" /> 
    <!--<meta name="msapplication-TileImage" content="<?php echo Aitsu_Config::get('sys.webpath'); ?>skin/gfx/tileImage.png" />-->
    <meta name="msapplication-TileColor" content="#FFFFFF" />
    <!-- Windows 8 Tile :: End -->
	
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	
	<!-- CSS :: Start -->
    <link rel="stylesheet" href="/skin/css/jquery.mobile.structure-1.0.1.css" />
    <link rel="stylesheet" href="/skin/css/jquery.mobile-1.0.1.css" />
	<link rel="stylesheet" href="/skin/css/custom.css" />
    <!-- CSS :: End -->
	
    <!-- JS :: Start -->
    <script type="text/javascript" charset="utf-8" src="/skin/js/jq.mobi.js"></script> 
    <!-- include jq.desktopBrowsers.js on desktop browsers only -->
    <script><script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.debug.js"></script> 
    <script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.swipe.js"></script> 
    <script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.carousel.js"></script> 
    <script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.drawer.js"></script> 
    <script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.shake.js"></script> 
    <script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.alphatable.js"></script> 
    <script type="text/javascript" charset="utf-8" src="/skin/plugins/jq.template.js"></script> 

    <!-- JS :: End -->	
	
	<link rel="apple-touch-icon" href="images/launch_icon_57.png" />
	<link rel="apple-touch-icon" sizes="72x72" href="images/launch_icon_72.png" />
	<link rel="apple-touch-icon" sizes="114x114" href="images/launch_icon_114.png" />

	<!-- IE Fix for HTML5 Tags -->
    <!--[if lt IE 9]>
    <script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->
    
    </head>
    
    <body>
        <!-- Header :: Start -->
        <script type="application/x-moraso" src="Template:Header">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/header/default.phtml 
            
            template.start.name = Start
            template.start.file = templates/header/start.phtml 
            
        </script>
        <!-- Header :: End -->
        
        <!-- Content :: Start -->
        <script type="application/x-moraso" src="Template:Content">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/content/default.phtml 
            
            template.start.name = Start
            template.start.file = templates/content/start.phtml 
            
        </script>
        <!-- Content :: End -->

        <!-- Footer :: Start -->
        <script type="application/x-moraso" src="Template:Footer">
            defaultTemplate = default

            template.default.name = Standard
            template.default.file = templates/footer/default.phtml 
            
            template.start.name = Start
            template.start.file = templates/footer/start.phtml 
        </script>
        <!-- Footer :: End -->

        <!-- JS :: Start -->
        <!-- JS :: End -->
        
    </body>
</html>
