<!DOCTYPE html> 
<html> 
	<head>
  <meta charset="UTF-8">	
	<script type="application/x-moraso" src="HTML.Meta.PageTitle">
		suffix = " | Wohlmuth Weingut"
	</script>  
	
	<meta name="viewport" content="width=device-width, initial-scale=1"> 
	<link rel="stylesheet" href="/skin/css/jquery.mobile.structure-1.0.1.css" />
	<link rel="apple-touch-icon" href="/skin/images/launch_icon_57.png" />
	<link rel="apple-touch-icon" sizes="72x72" href="/skin/images/launch_icon_72.png" />
	<link rel="apple-touch-icon" sizes="114x114" href="/skin/images/launch_icon_114.png" />
	<link rel="stylesheet" href="/skin/css/jquery.mobile-1.2.0.css" />
	<link rel="stylesheet" href="/skin/css/custom.css" />
	<script src="/skin/js/jquery-1.7.1.min.js"></script>
	<script src="/skin/js/jquery.mobile.js"></script>
</head> 

<body> 
<div data-role="page" id="home" data-theme="c">
	<div id="header" style="height: 95px; background: #000 url(/skin/images/wohlmuth-logo.png) no-repeat 20px 50px;">
	</div>

	<div data-role="content" style="padding:0; margin:0;">
		<div class="choice_list"> 
			<script type="application/x-moraso" src="Navigation:Main"> 
				idcat = 1
				template = main
			</script>
		</div>
	</div>
	
	<div id="footer" data-position="fixed" style="background-image: none; background-color: white; height: 40px; border: 0; text-align: center; box-shadow: none;">
		<div style="bottom: 0px; right:0; position: fixed;">
			<div style="float: right; padding: 0 10px 0 0; height: 15px;">
				<a href="javascript:history.go(0);">
	            <img src="/skin/images/icons/english.png" border="0" width="15px" height="15px">
    	        </a>
			</div>  
	        <div style="float: right; padding: 0 10px 0 0;">
    	    	<a href="" data-transition="fade">
        	    <img src="/skin/images/icons/facebook.png" border="0" width="15px">
            	</a>
			</div>
    	    <div style="float: right; padding: 0 10px 0 0;">
        		<a href="" data-transition="fade">
	            <img src="/skin/images/icons/twitter.png" border="0" width="15px">
    	        </a>
			</div>
		</div>

	</div>
	
</div><!-- /page -->

<div data-role="page" id="Weingut" data-theme="c">
	<div id="header" style="">
	</div>

	<div data-role="content">
		<script type="application/x-moraso" src="List.Articles:Weingut">
				categories = 7
				useOfStartArticle = 1
				template = weingut
				populateWith.intro.index = Teaser
				populateWith.content.index = Content
				populateWith.bild.type = property
				populateWith.bild.index = ModuleConfig_bild:Image_Media
		</script>
	</div>
	
	<div id="footer" data-position="fixed" style="background-image: none; background-color: white; height: 40px; border: 0; text-align: center; box-shadow: none;">
		<div style="z-index: 1;"><a href="#home" data-transition="slideup"><img src="/skin/images/icons/home.png" border="0"></a></div>
    	<div id="carousel_dots" style="margin: -20px 0 0 0; padding-top: 5px; position: relative;  height: 20px; z-index: 10; background: black; width: 100%"></div>
	</div>
	
</div><!-- /page -->

</body>
</html>
