<!DOCTYPE html><!--HTML5 doctype-->
<html>
<head>
<script type="application/x-moraso" src="HTML.Meta.PageTitle">
	suffix = " | Wohlmuth Weingut"
</script>   

<meta http-equiv="Content-type" content="text/html; charset=utf-8"> 
<meta name="viewport" content="width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black" />

<link rel="stylesheet" type="text/css" href="/skin/css/icons.css" /> 
<link rel="stylesheet"  type="text/css" href="/skin/css/jq.ui.css" title="default" />

<script type="text/javascript" charset="utf-8" src="/skin/js/jq.ui.min.js"></script> 
<script type="text/javascript" charset="utf-8" src="/skin/js/subpanels.js"></script> 

<!-- include touch.js on desktop browsers only -->
<script>
if(!((window.DocumentTouch&&document instanceof DocumentTouch)||'ontouchstart' in window)){
    var script=document.createElement("script");
    script.src="js/jq.desktopBrowsers.js";
    var tag=$("head").append(script);
}

$(document).ready(function(){
});
</script>

<script type="text/javascript">
    /* This function runs once the page is loaded, but appMobi is not yet active */
	var webRoot="./";
	$.ui.autoLaunch=false;
    $.ui.resetScrollers=false;
    var init = function(){
	   $.ui.backButtonText="Back";  
	   window.setTimeout(function(){$.ui.launch();},1500);
       $.ui.removeFooterMenu(); This would remove the bottom nav menu
    };
    document.addEventListener("DOMContentLoaded",init,false);  
	$.ui.ready(function(){console.log('ready');});
   
    /* This code is used to run as soon as appMobi activates */
    var onDeviceReady=function(){
		AppMobi.device.setRotateOrientation("portrait");
        AppMobi.device.setAutoRotate(false);
		webRoot=AppMobi.webRoot+"/";
	    //hide splash screen
	    AppMobi.device.hideSplashScreen();	
    };
    document.addEventListener("appMobi.device.ready",onDeviceReady,false);    
</script>
</head>


<body>
<div id="jQUi">
<!-- <div id="splashscreen" class='ui-loader'>
        <img src="/skin/images/splash.png">
        <br><br>
        <span class='ui-icon ui-icon-loading spin'></span><h1 >Starting app</h1>
</div> -->
    

<div id="header" style="height: 95px; background: #000 url(/skin/images/wohlmuth-logo.png) no-repeat 20px 50px;">
	<a id='menubadge' onclick='jq.ui.toggleSideMenu()' style='float:right;margin-top:0px;display:none' class='menuButton'></a>
</div>

<div id="content">

	<div title='' id="main" class="panel" selected="true" data-load="loadedPanel" data-unload="unloadedPanel" data-footer="footerui0">
		<!-- <h2 class='expanded' onclick='showHide(this,"main_info");'>Welcome</h2> -->
		<script type="application/x-moraso" src="Navigation:Main"> 
			idcat = 1
		</script>
	</div> 
	
	<div id="Weingut" title="Weingut" class="panel" scrolling="no" data-header="testheader" data-footer="footerui1">
		<script type="application/x-moraso" src="List.Articles:Weingut">
				categories = 7
				useOfStartArticle = 1
				template = weingut
				populateWith.intro.index = Teaser
				populateWith.content.index = Content
				populateWith.bild.type = property
				populateWith.bild.index = ModuleConfig_bild:Image_Media
		</script>
	</div>

	<div title="Sortiment" id="sortiment" class="panel" data-header="testheader" data-footer="footerui2" scrolling="no" style="width: 330px; height: 460px;">
		<script type="application/x-moraso" src="ArtikelList:4">
			idcat = 11
			template = weine
		</script>
	</div>

	<div title="News" id="news" class="panel" data-header="testheader" data-footer="footerui1" >
		NEWS news
	</div>

	<header id="testheader" style="background: black; height: 0px; ">
	<!--<a id="backButton"  class='button' style='left:0px;left:auto;overflow:hidden'>Go Back</a>
    	<h1>Custom Header</h1> -->
	</header>


	<footer id='footerui0' style='background-image: none; background-color: white; height: 40px; border: 0; text-align: center; box-shadow: none;'>
    	<div style="bottom: 0px; right:0; position: fixed;">

			

						
			
			<div style="float: right; padding: 0 10px 0 0;">
				<a href="javascript:history.go(0);">
	            <img src="/skin/images/icons/english.png" border="0" width="30px">
    	        </a>
			</div>  
	        <div style="float: right; padding: 0 10px 0 0;">
    	    	<a href="" data-transition="fade">
        	    <img src="/skin/images/icons/facebook.png" border="0" width="30px">
            	</a>
			</div>
    	    <div style="float: right; padding: 0 10px 0 0;">
        		<a href="" data-transition="fade">
	            <img src="/skin/images/icons/twitter.png" border="0" width="30px">
    	        </a>
			</div>
		</div>
	</footer>

	<footer id="footerui1" style="text-align: center;">
		<div style="z-index: 1;"><a href="#main" data-transition="up"><img src="/skin/images/icons/home.png" border="0"></a></div>
    	<div id="carousel_dots" style="margin: -20px 0 0 0; padding-top: 5px; position: relative;  height: 20px; z-index: 10; background: black; width: 100%"></div>
	</footer>

	<footer id='footerui2' style='background: white; height: 40px; border: 0; text-align: center;'>
		<div style="z-index: 1;"><a href="#main" data-transition="up"><img src="/skin/images/icons/home.png" border="0"></a></div>
	    <div id="carousel_dots2" style="margin: -20px 0 0 0; position: relative;  height: 20px; z-index: 10; background: black; width: 100%"></div>
	</footer>

	<footer id='footerui3'>
    	<a href="#main" id='navbar_home' class='icon home' >Home <span class='jq-badge lr'>6</span></a>
    	<a href="#jqmtransitions" id='navbar_js' class="icon stack" >Trans</a>
		<a href="#jqmui" id='navbar_ui'  class="icon picture" >ui</a>
		<a href="#uiapi" id='navbar_plugins'  class="icon info" >api</a>
	</footer>	

	<nav>
   		<div class='title'>Home</div>
		<script type="application/x-moraso" src="Template:Main">
			defaultTemplate = templates/startseite.phtml
		</script>	  
	</nav>

</div>
</body>
</html>