Ext.MessageBox.alert('<?php echo Aitsu_Translate :: translate('Not implemented'); ?>', '<?php echo Aitsu_Translate :: translate('This feature has not yet been implemented.'); ?>');
<?php return; ?>
<div class="tabs">
	<ul>
		<li>
			<a href="#tab-data" id="data"><?php echo $this->translate('Data'); ?></a>
		</li>
	</ul>
	
	<div id="tab-data">
		<div class="tab-content">
			<div class="toolbar ui-corner-bottom">
				<button id="add-entry" class="type-new confirm" title="<?php echo $this->translate('Add new entry'); ?>"><?php echo $this->translate('Add new entry'); ?></button>
			</div>
			
			<div id="table-content" class="sized-content">
				<p>
					<?php echo $this->translate('Please select a data table on the left hand side to show, filter and edit its data.'); ?>
				</p>
			</div>			
		</div>
	</div>
		
</div>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

	$('ul#table-list > li').bind('click', function() {
		$('#table-content').load('<?php echo $this->url(array('paction' => 'list')); ?>', {table: $(this).find('a').attr('href')});
		return false;
	});
	
	setTimeout("$('#add-entry').button('disable');", 500);
	
	$('a.freehand-column-filter').live('click', function() {
		$(this).parents('li').first().toggleClass('invisible-input');
	});

	$('a.freehand-column-filter input').live('click', function() {
		return false;
	});
});
<?php $this->inlineScript()->captureEnd(); ?>