<?php if (!is_array($this->rows) || empty($this->rows)) : ?>
<p>
	<?php echo $this->translate('There are no data to be displayed.'); ?>
</p>
<?php else : ?>
<table id="data-table" border="0" cellpadding="0" cellspacing="0" class="full">
	<thead>
		<tr>
			<?php foreach ($this->rows[0] as $field) : ?>
				<th scope="col" class="column-<? echo $field->meta->table; ?>-<? echo $field->meta->column; ?>">
					<?php echo $field->meta->column; ?>
					<input type="hidden" name="table" value="<? echo $field->meta->table; ?>" />
					<input type="hidden" name="column" value="<? echo $field->meta->column; ?>" />
				</th>
			<?php endforeach; ?>
		</tr>
	</thead>
	<tbody>
		<?php $counter = 0; foreach ($this->rows as $row) : $counter++; ?>
			<tr class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>" style="cursor:pointer;">
				<?php foreach ($row as $field) : ?>
					<td style="white-space:nowrap;" class="column-<? echo $field->meta->table; ?>-<? echo $field->meta->column; ?>">
						<?php echo htmlentities(substr($field->value, 0, 32), ENT_COMPAT, 'UTF-8'); ?>
						<?php if (strlen($field->value) > 32) : ?>
							[...]
							<div style="display:none">
								<?php echo htmlentities($field->value, ENT_COMPAT, 'UTF-8'); ?>
							</div>
						<?php endif; ?>
					</td>
				<?php endforeach; ?>
			</tr>
		<?php endforeach; ?>
	</tbody>
</table>
<?php endif; ?>

<script type="text/javascript">
$(function() {
	
	$('#add-entry').button('enable');
	
	$('#data').html('<?php echo $this->table; ?>');
	
	if ($('#columns-to-be-shown').data('table') != '<?php echo $this->table; ?>') {
		$('#columns-to-be-shown').data('table', '<?php echo $this->table; ?>');
		
		var colList = $('#columns-to-be-shown ul.vlist');
		colList.empty();
		$('#data-table > thead > tr > th').each(function() {
			colList.append('<li><a href="column-' + $(this).find('input[name=table]').val() + '-' + $(this).find('input[name=column]').val() + '" title="' + $(this).find('input[name=table]').val() + '.' + $(this).find('input[name=column]').val() + '">' + $(this).find('input[name=column]').val() + '</a></li>');
		});

		$('#columns-to-be-shown ul li a:not(.colhidden)').live('click', function() {
			$('.' + $(this).attr('href')).css('display', 'none');
			$(this).addClass('colhidden');
			return false;
		});
		
		$('#columns-to-be-shown ul li a.colhidden').live('click', function() {
			$('.' + $(this).attr('href')).css('display', 'table-cell');
			$(this).removeClass('colhidden');
			return false;
		});

		var filterList = $('#applicable-filter ul.vlist');
		filterList.empty();
		$('#data-table > thead > tr > th').each(function() {
			var content = '<li class="invisible-input"><a href="column-' + $(this).find('input[name=table]').val() + '-' + $(this).find('input[name=column]').val() + '"  title="' + $(this).find('input[name=table]').val() + '.' + $(this).find('input[name=column]').val() + '" class="freehand-column-filter">' + $(this).find('input[name=column]').val() + '';
			content += '<div><input type="text" name="' + $(this).find('input[name=table]').val() + '" /></div></a>';
			content += '</li>';
			filterList.append(content);
		});

		$('#applicable-filter ul li a').live('click', function() {
			return false;
		});
		
	} else {
		$('#columns-to-be-shown ul li a.colhidden').each(function() {
			$('.' + $(this).attr('href')).css('display', 'none');
		});
	}
		
});
</script>