<div id="subnav-accordion">
	<div class="accordion">
		<h3><a href="#"><?php echo $this->translate('Data tables'); ?></a></h3>
		<div>
			<ul class="vlist" id="table-list">
				<?php foreach ($this->tables as $table) : ?>
					<li>
						<a href="<?php echo $table; ?>">
							<?php echo $table; ?>
						</a>
					</li>
				<?php endforeach; ?>
			</ul>
		</div>
		<h3><a href="#"><?php echo $this->translate('Columns'); ?></a></h3>
		<div id="columns-to-be-shown">
			<ul class="vlist">
				<li style="display:none;"></li>
			</ul>
		</div>
		<h3><a href="#"><?php echo $this->translate('Filter'); ?></a></h3>
		<div id="applicable-filter">
			<ul class="vlist">
				<li style="display:none;"></li>
			</ul>
		</div>
	</div>
</div>		