<ul id="cm-category" class="contextMenu">
    <li class="add">
        <a href="#add">Add new child</a>
    </li>
    <li class="edit">
        <a href="#edit">Edit</a>
    </li>
    <li class="online">
        <a href="#online">Online</a>
    </li>
    <li class="offline">
        <a href="#offline">Offline</a>
    </li>
    <li class="lock">
        <a href="#lock">Lock</a>
    </li>
    <li class="delete">
        <a href="#delete">Delete</a>
    </li>
</ul>