<ul id="editduplicatedelete" class="contextMenu">
    <li class="make-index">
        <a href="#make-index"><?php echo $this->translate('Index article'); ?></a>
    </li>
    <li class="edit separator">
        <a href="#edit"><?php echo $this->translate('Edit'); ?></a>
    </li>
    <li class="copy">
        <a href="#duplicate"><?php echo $this->translate('Duplicate'); ?></a>
    </li>
    <li class="delete">
        <a href="#delete"><?php echo $this->translate('Delete'); ?></a>
    </li>
    <li class="cut">
        <a href="#cut"><?php echo $this->translate('Cut'); ?></a>
    </li>
</ul>