<div class="page_margins">
	<div class="page">
		<div id="header">
			<script type="application/x-aitsu" src="Template:Header">
				defaultTemplate = templates/body/header/header.phtml
			</script>
		</div>
		<!-- 
		<div id="teaser">
			<script type="application/x-aitsu" src="Template:Teaser">
	    		defaultTemplate = templates/body/teaser/teaser.phtml
    		</script>
    	</div>
    	 -->
		<div id="main">
			<script type="application/x-aitsu" src="Template:Main">
				defaultTemplate = templates/body/main/main.phtml
			</script>
		</div>
		<div id="footer">
			<script type="application/x-aitsu" src="Template:Footer">
				defaultTemplate = templates/body/footer/footer.phtml
			</script>
		</div>
	</div>
</div>