<div id="header" role="banner">

	<div id="topnav" role="contentinfo">
		<span>
			<a href="http://www.aitsu.org/" target="_blank">aitsu</a> | 
			<a href="http://www.php.net/" target="_blank">PHP</a> | 
			<a href="http://www.jquery.com/" target="_blank">jQuery</a> | 
			<a href="http://www.yaml.de/" target="_blank">YAML</a>
		</span>
	</div>
	
	<script type="application/x-aitsu" src="HTML.Meta.PagetitleAsHeadline">
		tag = h1
	</script>

</div>