<?php $this->headStyle()->captureStart(); ?>
div.boxmodel-root, div.boxmodel-root div.shortcode {
	border:1px solid #CCC;
	padding:8px;
	padding-bottom:0;
	-moz-border-radius: 5px;
    -webkit-border-radius: 5px;
    border-radius: 5px;
}
div.boxmodel-root div.shortcode {
	margin-bottom:8px;
	cursor:pointer;
}
div.boxmodel-root div.shortcode-title {
	margin-bottom:8px;
}
div.boxmodel-root div.shortcode.hover {
	background-color:#EEE;
}
div.boxmodel-root div.shortcode.focused {
	background-color:#CCC;
}
<?php $this->headStyle()->captureEnd(); ?>

<?php $this->inlineScript()->captureStart(); ?>
$(function() {

		$(document).bind('doBoxModelEdit', function(e, ui, idartlang) {
			$('form#aitsu-content-edit-form').remove();
			$('#box-edit-save').css('visibility', 'hidden');
			
	  		var type = ui.children('input[name=method]').val();
	  		var container = ui.children('input[name=index]').val();
	  		var params = '';
	  		if (ui.find('code.params').length > 0) {
	  			params = ui.find('code.params').first().html();
	  		}

			$.post("<?php echo $this->url(array('plugin' => 'edit', 'paction' => 'editcontent'), 'aplugin'); ?>", { type: type, container: container, idartlang: idartlang, params: params },
	  			function(data){
					$('#edit-box-edit-area').html(data);
					
					var height = $('#edit-box-edit-area').parent().height();	  				
					$('#tabs').css('height', (height - 50) + 'px');
					
	  				CKEDITOR.config.toolbar_normal=[
					  ['Source','Templates'],
					  ['Cut','Copy','Paste','PasteText'],
					  ['Undo','Redo','-','Find','Replace','-','SelectAll','RemoveFormat'],
					  ['Bold','Italic','Underline','Strike','-','Subscript','Superscript'],
					  ['NumberedList','BulletedList','-','Outdent','Indent','Blockquote'],
					  '/',
					  ['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],
					  ['Link','Unlink','Anchor'],
					  ['Image','Flash','Table','HorizontalRule','SpecialChar'],
					  ['Styles','Format'],
					  ['Maximize', 'ShowBlocks','-','About']
					 ];
					 
					$('.jquery_ckeditor').ckeditor({
					  skin : 'office2003',
					  toolbar : 'normal',
					  height : (height - 245) + 'px',
					  customConfig : ''
					});
					
					$("#tabs").tabs();
					$('#tabs').children('div').css('height', (height - 120) + 'px');
	  				$("#tabs textarea.plaintext-editor").css({
	  					height: (height - 200) + 'px',
	  					width: '100%',
	  					padding: 0,
	  					margin: 0
	  				});
	  				$(".jqDatePicker").datepicker({ dateFormat: 'yy-mm-dd' });
	  				$(".ui-datepicker").css('z-index', 5000);
	  				$('.category-breadcrumb').trigger('click');
	  				
	  				$('#box-edit-save').css('visibility', 'visible');
	  			}, "html");
		});
	
});
<?php $this->inlineScript()->captureEnd(); ?>