<?php 
	$m = $this->modulo; 
	$total = count($this->images); 
?>
<?php $i=0; foreach ($this->images as $image) : ?>
<?php if ($i%$m == 0) : ?><div><?php endif; ?>
<img src="<?php echo Aitsu_Config :: get('sys.webpath'); ?>image/100/100/2/<?php echo $this->images[$i]->idart; ?>/<?php echo $this->images[$i]->filename; ?>" <?php echo $this->title; ?> <?php if(isset($this->alt)) : ?><?php echo $this->alt; ?><?php else : ?> alt="<?php echo $this->images[$i]->name; ?>" style="margin:0 10px 10px 0;" /><?php endif; ?>
<?php if ($i%$m == ($m-1) || ($i%$m == ($total-$i)  && $total%$m !== 0) || $total == ($i+1)) : ?></div><?php endif; ?>
<?php $i++; endforeach; ?>