<a class="skip" href="#navigation" title="skip link">skip to navigation</a>
<span class="hideme">.</span>
<a class="skip" href="#content" title="skip link">skip to content</a>
<span class="hideme">.</span>
<script type="application/x-aitsu" src="Navigation:Service">
	idcat = 59
	template = service
</script>
<div class="subcolumns">
	<div class="c20l" style="width:234px;">
		<div class="subcl">
			<h1>
				<a href="/" title="home">
					<img class="logo" src="/skin/images/0.gif" alt="home" title="home" width="150" height="50" />
				</a>
			</h1>
		</div>
	</div>
	<div class="c80r" style="width:728px;">
		<div class="subcl">
			<div id="nav">
				<a id="navigation"></a>
				<div class="hlist">
					<script type="application/x-aitsu" src="Navigation:Top">
						idcat = 31
						template = top
					</script>
				</div>
			</div>
		</div>
	</div>
</div>