<?php echo $this->form; ?>

<script type="text/javascript">
$(function() {
	$('#tab-track button.cancel').button({icons: {primary: 'ui-icon-circle-close'}});
	$('#tab-track button.save').button({icons: {primary: 'ui-icon-circle-check'}});
	
	$( "#project-autocomplete" ).autocomplete({
		source: "<?php echo $this->url(array('paction' => 'projectjson')); ?>",
		minLength: 2,
		select: function( event, ui ) {
			$('#projectid').val(ui.item.id);
		}
	});
	
});
</script>