<form action="<?php echo $this->url(array('paction' => 'listtracks')); ?>" method="post" style="display:inline;">	
	<div class="toolbar">
		<button id="add-new-track" class="type-new"><?php echo $this->translate('Add new track'); ?></button>
		<input type="text" name="filter-track" value="<?php echo $this->filterterm; ?>" class="button-input ui-button ui-corner-all" />
		<button id="filter-track" class="filter-button"><?php echo $this->translate('Filter'); ?></button>
	</div>
</form>
		
<div class="sized-content" id="tracklist">	
	<table border="0" cellpadding="0" cellspacing="0" class="full hasctxmenu">
		<thead>
			<tr>
				<th scope="col"><?php echo $this->translate('ID'); ?></th>
				<th scope="col"><?php echo $this->translate('Title'); ?></th>
				<th scope="col"><?php echo $this->translate('Type'); ?></th>
				<th scope="col"><?php echo $this->translate('Project'); ?></th>
				<th scope="col"><?php echo $this->translate('Customer'); ?></th>
			</tr>
		</thead>
		<tbody>
			<?php $counter = 0; foreach ($this->tracks as $track) : $counter++; ?>
				<tr id="track-<?php echo $track->trackid; ?>" class="<?php echo ($counter % 2 == 0 ? 'even' : 'odd'); ?>" style="cursor:pointer;">
					<td><?php echo $track->trackid; ?></td>
					<td class="track-title"><?php echo $track->title; ?></td>
					<td><?php echo $track->tracktype; ?></td>
					<td><?php echo $track->project; ?></td>
					<td><?php echo $track->customer; ?></td>
				</tr>
			<?php endforeach; ?>
		</tbody>
	</table>
</div>