<div itemscope itemtype="http://schema.org/Rating" class="SchemaOrg Rating">
	<link itemprop="url" href="<?php echo $this->url; ?>" />
	<?php if (!empty($this->image)) : ?>
		<img itemprop="image" src="<?php echo Aitsu_Config :: get('sys.mainDir'); ?>image/100/100/2/<?php echo $this->idart; ?>/<?php echo $this->image; ?>" width="100" height="100" style="float:right; margin: 0 0 5px 5px;" />
	<?php endif; ?>
	<?php if (!empty($this->description)) : ?>
	<div itemprop="description" style="margin-bottom:10px;"><?php echo htmlentities($this->description, ENT_COMPAT, 'UTF-8'); ?></div>
	<?php endif; ?>
	<dl>
		<?php if (!empty($this->name)) :?>
		<dt>Name:</dt>
			<dd itemprop="name"><?php echo htmlentities($this->name, ENT_COMPAT, 'UTF-8'); ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->email)) :?>
		<dt>Email:</dt>
			<dd>
				<a href="mailto:<?php echo $this->email; ?>" itemprop="email"><?php echo $this->email; ?></a>
			</dd>
		<?php endif; ?>
		<?php if (!empty($this->bestRating)) :?>
		<dt>Best rating:</dt>
			<dd itemprop="bestRating"><?php echo $this->bestRating; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->ratingValue)) :?>
		<dt>Rating value:</dt>
			<dd itemprop="ratingValue"><?php echo $this->ratingValue; ?></dd>
		<?php endif; ?>
		<?php if (!empty($this->worstRating)) :?>
		<dt>Worst rating:</dt>
			<dd itemprop="worstRating"><?php echo $this->worstRating; ?></dd>
		<?php endif; ?>
	</dl>
</div>