var center = Ext.getCmp('viewport-center');
center.removeAll();

var reader = new Ext.data.JsonReader({
    idProperty: 'id',
    root: 'data',
    fields: [
        {
            name: 'id',
            type: 'int'
        }, {
            name: 'config',
            type: 'String'
        }, {
            name: 'env',
            type: 'String'
        }, {
            name: 'identifier',
            type: 'String'
        }, {
            name: 'value',
            type: 'String'
        }
    ]
});

var store = new Ext.data.GroupingStore({
    reader: reader,
    url: '<?php echo $this->url(array('paction' => 'store')); ?>',
    groupField: 'env',
    autoLoad: true,
    remoteGroup: true
});
                
var configurationGrid = new Ext.grid.GridPanel({
    title: '<?php echo Aitsu_Translate::translate('Configuration'); ?>',
    id: 'configurationGrid',
    store: store,
    columns: [
        {dataIndex: 'config', width: 60, fixed: true, header: '<?php echo Aitsu_Translate::translate('Config'); ?>', sortable: true},
    	{dataIndex: 'env', header: '<?php echo Aitsu_Translate::translate('Environment'); ?>', sortable: true},
    	{dataIndex: 'identifier', header: '<?php echo Aitsu_Translate::translate('Identifier'); ?>', sortable: true},
        {dataIndex: 'value', width: 60, header: '<?php echo Aitsu_Translate::translate('Value'); ?>', sortable: true}
    ],
    view: new Ext.grid.GroupingView({
        forceFit:true,
        groupTextTpl: '{text} ({[values.rs.length]} {[values.rs.length > 1 ? "Configurations" : "Configuration"]})'
    }),
    viewConfig: {
        forceFit: true,
        autoFill: true
    },
	tbar: {
		items: [
			{
	            tooltip: '<?php echo Aitsu_Translate::translate('Add new Configuration'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	Ext.aitsu.load(['<?php echo $this->url(array('paction' => 'edit')); ?>']);
	            }
	        }
	    ]
	},
	listeners: {
		rowclick: function(grid, rowIndex, event) {
			var rec = grid.getStore().getAt(rowIndex);
			Ext.aitsu.load(['<?php echo $this->url(array('paction' => 'edit')); ?>'], null, {
				id: rec.get('id')
			});
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete Configuration'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected configuration?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('paction' => 'delete')); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate::translate('Configuration removed'); ?>', '<?php echo Aitsu_Translate::translate('The selected rewrite rule has been removed.'); ?>');
					            			grid.getStore().load(); 
				            			}
				            		},
				            		params: { id: record.get('id') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}		
	}
});

center.add(configurationGrid);

Ext.getCmp('viewport').doLayout();