<?php
$langId = Aitsu_Registry :: get()->env->idlang ? Aitsu_Registry :: get()->env->idlang : 1;
switch($langId) {
	case 1:
		$language = 'de';
		break;
	case 2:
		$language = 'en';
		break;
	default:
		$language = 'de';
}
?>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="content-language" content="<?php echo $language; ?>" />
<script type="application/x-aitsu" src="HTML.Meta.BaseHref"></script>
<script type="application/x-aitsu" src="HTML.Meta.PageTitle"></script>
<script type="application/x-aitsu" src="CanonicalTag"></script>
<script type="application/x-aitsu" src="MetaTags"></script>
<script type="application/x-aitsu" src="HTML.Meta.ResourceBundle">
  type = css
  res.0 = /yaml/core/base.css
  res.1 = /yaml/navigation/nav_slidingdoor.css
  res.2 = /yaml/navigation/nav_vlist.css
  res.3 = /yaml/screen/forms.css
  res.4 = /css/screen/basemod.css
  res.5 = /css/screen/basemod_2col_advanced.css
  res.6 = /css/screen/content.css
  res.7 = /yaml/print/print_100_draft.css
  res.8 = /css/style.css
</script>
<!--[if lte IE 7]>
<link href="/skin/css/patches/patch_2col_advanced.css" rel="stylesheet" type="text/css" />
<![endif]-->
<link rel="shortcut icon" type="image/x-icon" href="/skin/favicon.ico" />