<div class="toolbar ui-corner-bottom">
	<div class="subcolumns">
		<div class="c38l">
			<div class="subcl">
				<button id="add-new-serial" class="type-new"><?php echo $this->translate('Add new serial'); ?></button>
				<button id="delete-serials" class="type-delete"><?php echo $this->translate('Delete selected serials'); ?></button>
			</div>
		</div>
	
		<div class="c62r">
			<div class="subcr">
				<button id="add-new-date" class="type-new"><?php echo $this->translate('Add new date'); ?></button>
				<button id="delete-dates" class="type-delete"><?php echo $this->translate('Delete selected dates'); ?></button>
			</div>
		</div>
	</div>
</div>
		
<div class="subcolumns">
	<div class="c38l">
		<div class="subcl">
			<div class="sized-content rounded-corners" style="border:1px solid #CCC; padding:10px;">
				<ul>
					<li>Bezeichner</li>
					<li>Erstmals</li>
					<li>Letztmals</li>
					<li>Startzeit</li>
					<li>Endzeit</li>
					<li>Wiederholung
						<ul>
							<li>Wochentag(e) [Checkboxen]</li>
							<li>Interval (in Tagen)</li>
							<li>Gleiches Datum im Monat</li>
							<li>n-ter Wochentag im Monat</li>
							<li>n-letzter Wochentag im Monat</li>
						</ul>
					</li>
				</ul>
			</div>
		</div>
	</div>

	<div class="c62r">
		<div class="subcr">
			<div id="current-dates" class="sized-content rounded-corners" style="border:1px solid #CCC; padding:10px;">
				hier kommen die termine hin
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(function() {
	
	$('button#add-new-serial').button({icons: {primary: 'ui-icon-circle-plus'}});
	$('button#delete-serials').button({icons: {primary: 'ui-icon-circle-close'}});
	$('button#add-new-date').button({icons: {primary: 'ui-icon-circle-plus'}});
	$('button#delete-dates').button({icons: {primary: 'ui-icon-circle-close'}});
	
});
</script>