<script type="text/javascript" src="/skins/default/js/swfobject.js"></script>
<script type="text/javascript">
  var flashvars = {};
  var params = {};
  var attributes = {wmode: "transparent"};
  swfobject.embedSWF("/file/<?php echo $this->files[0]->idart; ?>/<?php echo $this->files[0]->filename; ?>", "SWF-Object", "<?php echo $this->width; ?>", "<?php echo $this->height; ?>", "9.0.0", flashvars, params, attributes);
</script>
<div id="SWF-Object" style="z-index:-100;">
<?php if(!empty($this->images[0]->filename)) : ?>
<img src="/image/<?php echo $this->width; ?>/<?php echo $this->height; ?>/0/<?php echo $this->images[0]->idart; ?>/<?php echo $this->images[0]->filename; ?>" />
<?php else : ?>
<?php endif; ?>
<p><a href="http://www.adobe.com/go/getflashplayer" target="_blank"><img
      src="http://www.adobe.com/images/shared/download_buttons/get_flash_player.gif"
      alt="Get Adobe Flash player" /></a></p>
</div>