<div class="subcolumns equalize box-top"><?php $i=0; foreach ($this->nav->children as $nav1) : ?>
<?php if($i%3==0) : ?>
<div class="c33l">
<div class="subcl"><?php $j=0; foreach ($nav1->children as $nav2) : ?> <?php if($j==0) : ?>
<h3 class="corner_top ui-widget-header ui-state-default"><a
	title="<?php echo $nav2->name; ?>"
	href="{ref:idcat-<?php echo $nav2->idcat; ?>}"><?php echo $nav2->name; ?></a>
</h3>
<?php endif; ?> <?php $j++; endforeach; ?>
<dl class="clearfix">
	<dd class="img"><img width="100" height="100"
		src="/skin/images/cms_grey.png" alt="Content Management System"></dd>
	<dd>
	<ul>
	<?php $j=0; foreach ($nav1->children as $nav2) : ?>
	<?php if($j>0) : ?>
		<li><a title="<?php echo $nav2->name; ?>"
			href="{ref:idcat-<?php echo $nav2->idcat; ?>}"><?php echo $nav2->name; ?></a></li>
			<?php endif; ?>
			<?php $j++; endforeach; ?>
	</ul>
	</dd>
</dl>
</div>
</div>
			<?php elseif($i%3==1) : ?>
<div class="c33l">
<div class="subcl"><?php $j=0; foreach ($nav1->children as $nav2) : ?> <?php if($j==0) : ?>
<h3 class="corner_top ui-widget-header ui-state-default"><a
	title="<?php echo $nav2->name; ?>"
	href="{ref:idcat-<?php echo $nav2->idcat; ?>}"><?php echo $nav2->name; ?></a>
</h3>
<?php endif; ?> <?php $j++; endforeach; ?>
<dl class="clearfix">
	<dd class="img"><img width="100" height="100"
		src="/skin/images/dokumentation_grey.png" alt="Dokumentation"></dd>
	<dd>
	<ul>
	<?php $j=0; foreach ($nav1->children as $nav2) : ?>
	<?php if($j>0) : ?>
		<li><a title="<?php echo $nav2->name; ?>"
			href="{ref:idcat-<?php echo $nav2->idcat; ?>}"><?php echo $nav2->name; ?></a></li>
			<?php endif; ?>
			<?php $j++; endforeach; ?>
	</ul>
	</dd>
</dl>
</div>
</div>
			<?php elseif($i%3==2) : ?>
<div class="c33r">
<div class="subcl"><?php $j=0; foreach ($nav1->children as $nav2) : ?> <?php if($j==0) : ?>
<h3 class="corner_top ui-widget-header ui-state-default"><a
	title="<?php echo $nav2->name; ?>"
	href="{ref:idcat-<?php echo $nav2->idcat; ?>}"><?php echo $nav2->name; ?></a>
</h3>
<?php endif; ?> <?php $j++; endforeach; ?>
<dl class="clearfix">
	<dd class="img"><img width="100" height="100"
		src="/skin/images/community_grey.png" alt="Community"></dd>
	<dd>
	<ul>
	<?php $j=0; foreach ($nav1->children as $nav2) : ?>
	<?php if($j>0) : ?>
		<li><a title="<?php echo $nav2->name; ?>"
			href="{ref:idcat-<?php echo $nav2->idcat; ?>}"><?php echo $nav2->name; ?></a></li>
			<?php endif; ?>
			<?php $j++; endforeach; ?>
	</ul>
	</dd>
</dl>
</div>
</div>
<?php endif; ?> <?php $i++; endforeach; ?></div>
<div class="subcolumns equalize no-ie-padding box-bottom">
<div class="c33l">
<div class="subcl">&nbsp;</div>
</div>
<div class="c33l">
<div class="subcl">&nbsp;</div>
</div>
<div class="c33r">
<div class="subcl">&nbsp;</div>
</div>
</div>
