<?php $i=0; foreach ($this->nav->children as $nav) : ?>
<?php if ($nav->iscurrent || $nav->isparent) : ?>
<?php if(count($nav->children) > 0 && $i <= 0) : ?>
<ul class="vlist corner">
<?php endif; ?>
	<?php $j=1; foreach ($nav->children as $mainNav) : ?>
	<li<?php if ($mainNav->iscurrent) : ?> class="active"<?php endif; ?><?php if($this->type == 'divider' || $mainNav->name == 'divider') : ?> class="divider"<?php endif; ?>>
		<?php if($this->type == 'divider' || $mainNav->name == 'divider') : ?> 
	
		<?php else: ?>
		<?php 
			$class = NULL;
			if($j==1) {
				$class = "corner_first";
			} elseif ($j== count($nav->children)) {
				$class = "corner_last";
			}
		?>
		<a<?php if ($mainNav->iscurrent) : ?> class="active<?php echo ' '.$class; ?>"<?php endif; ?> <?php if($class) : ?> class="<?php echo $class; ?>"<?php endif; ?> href="{ref:idcat-<?php echo $mainNav->idcat; ?>}"><?php echo $mainNav->name; ?></a>
		<?php endif; ?> 

		<?php if (count($mainNav->children) > 0 && ($mainNav->iscurrent || $mainNav->isparent)) : ?>
		<ul>
			<?php foreach ($mainNav->children as $subNav) : ?>
			<li<?php if ($subNav->iscurrent || $subNav->isparent) : ?> class="active"<?php endif; ?><?php if($this->type == 'divider' || $subNav->name == 'divider') : ?> class="divider" <?php endif; ?>>
				<?php if($this->type == 'divider' || $subNav->name == 'divider') : ?>
		
				<?php else: ?> 
				<a<?php if ($subNav->iscurrent || $subNav->isparent) : ?>  class="active"<?php endif; ?>href="{ref:idcat-<?php echo $subNav->idcat; ?>}"><?php echo $subNav->name; ?></a>
				<?php endif; ?> 

				<?php if (count($subNav->children) > 0 && ($subNav->iscurrent || $subNav->isparent)) : ?>
				<ul>
					<?php foreach ($subNav->children as $subSubNav) : ?>
					<li<?php if ($subSubNav->iscurrent || $subSubNav->isparent) : ?> class="active"<?php endif; ?><?php if($this->type == 'divider' || $subSubNav->name == 'divider') : ?> class="divider" <?php endif; ?>>
						<?php if($this->type == 'divider' || $subSubNav->name == 'divider') : ?>
						
						<?php else: ?> 
						<a<?php if ($subSubNav->iscurrent || $subSubNav->isparent) : ?> class="active"<?php endif; ?> href="{ref:idcat-<?php echo $subSubNav->idcat; ?>}"><?php echo $subSubNav->name; ?></a>
						<?php endif; ?>
					</li>
					<?php endforeach; ?>
				</ul>
				<?php endif; ?>
			</li>
			<?php endforeach; ?>
		</ul>
		<?php endif; ?>
	</li>
	<?php $j++; endforeach; ?>
<?php if(count($nav->children) > 0 && $i <= 0) : ?>
</ul>
<?php endif; ?>
<?php endif; ?>
<?php endforeach; ?>