
<div class="c33r">
<div class="subcr"><?php $i=0; foreach ($this->nav->children as $nav1) : ?>
<?php if($i==0) : ?>
<h3 class="corner_top ui-widget-header ui-state-default"><a
	title="<?php echo $nav1->name; ?>"
	href="{ref:idcat-<?php echo $nav1->idcat; ?>}"><?php echo $nav1->name; ?></a>
</h3>
<?php endif; ?> <?php $i++; endforeach; ?>
<dl class="clearfix">
	<dd class="img"><img width="100" height="100"
		src="/skin/images/community_grey.png" alt="Content Management System"></dd>
	<dd>
	<ul>
	<?php $i=0; foreach ($this->nav->children as $nav1) : ?>
	<?php if($i>0) : ?>
		<li><a title="<?php echo $nav1->name; ?>"
			href="{ref:idcat-<?php echo $nav1->idcat; ?>}"><?php echo $nav1->name; ?></a></li>
			<?php endif; ?>
			<?php $i++; endforeach; ?>
	</ul>
	</dd>
</dl>
</div>
</div>
