var urlValue = new Ext.form.TextField({
	id: 'urlvalue',
	width: 150,
	style: {
		margin: '0 5px 0 5px'
	}
});

var rewritehistoryGrid = new Ext.grid.GridPanel({
	id: 'rewritehistoryGrid',
	store: new Ext.data.JsonStore({
		url: '<?php echo $this->url(array('plugin' => 'rewritehistory', 'paction' => 'store'), 'aplugin'); ?>',
		root: 'data',
		fields: ['id', 'url'],
                baseParams: {
                        idart: <?php echo $this->idart; ?>
                }
	}),
    columns: [
    	{dataIndex: 'id', width: 60, fixed: true, header: 'id', menuDisabled: true},
        {dataIndex: 'url', header: '<?php echo Aitsu_Translate :: translate('url'); ?>', menuDisabled: true}
	],
	viewConfig: {
		forceFit: true,
		autoFill: true
	},
        hideHeaders: true,
	border: false,
	tbar: {
		items: [
		urlValue,
			{
	            tooltip: '<?php echo Aitsu_Translate :: translate('Add new Rewrite Rule'); ?>',
	            iconCls: 'tb-add',
	            handler: function(b, e) {
	            	var value = urlValue.getValue();
	            	Ext.Ajax.request({
	            		url: '<?php echo $this->url(array('plugin' => 'rewritehistory', 'paction' => 'add'), 'aplugin'); ?>',
	            		success: function(response, opts) {
	            			rewritehistoryGrid.getStore().load();
	            			urlValue.setValue('');
	            		},
	            		params: {
	            			idart: <?php echo $this->idart; ?>,
	            			value: value
	            		}
	            	});
	            }
	        }
	    ]
	},
	listeners: {
                render: {
			fn: function(){
				this.getStore().load();
			}
		},
		rowclick: function(grid, rowIndex, event) {
			var record = this.getStore().getAt(rowIndex);
			// put values to form.
		},
		rowcontextmenu: function(grid, rowIndex, event) {
			
			this.getSelectionModel().selectRow(rowIndex);
			var record = this.getStore().getAt(rowIndex);
			
			var menu = new Ext.menu.Menu();
			
			menu.addItem({
				text: '<?php echo $this->translate('Delete'); ?>',
				iconCls: 'delete',
				handler: function() {
					 Ext.MessageBox.show({
					 	title: '<?php echo $this->translate('Delete Rewrite Rule'); ?>',
					 	msg: '<?php echo $this->translate('Are you sure to delete the selected rewrite Rule?'); ?>',
					 	buttons: Ext.MessageBox.OKCANCEL,
					 	fn: function(result) {
					 		if (result == 'ok') {
				            	Ext.Ajax.request({
				            		url: '<?php echo $this->url(array('plugin' => 'rewritehistory', 'paction' => 'delete'), 'aplugin'); ?>',
				            		success: function(response, opts) {
				            			var rsp = Ext.decode(response.responseText);
				            			if (rsp.success) {
				            				Ext.aitsu.msg('<?php echo Aitsu_Translate :: translate('Entry removed'); ?>', '<?php echo Aitsu_Translate :: translate('The selected Rewrite Rule has been removed.'); ?>');
					            			grid.getStore().load(); 
				            			}
				            		},
				            		params: { id: record.get('id') }
				            	});					 			
					 		}
					 	}
					 });
				}
			});
			
			menu.showAt(event.getXY());
		}		
	}
});

Ext.getCmp('page-plugin-accordion').add({
	id: 'article-plugin-rewrite-history',
	title: '<?php echo Aitsu_Translate :: translate('Rewrite History'); ?>',
	layout: 'fit',
	items: rewritehistoryGrid
});